### ISSUE TITLE
hydra_ax_sweeper integration tests failing

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1093]
I will follow up on this today 

CircleCI job link https://app.circleci.com/pipelines/github/jieru-hu/hydra/843/workflows/e6ba88e9-abb8-4724-bd98-4ac16fbbae3d/jobs/8622

```
----------------------------- Captured stderr call -----------------------------
Subprocess error:
Traceback (most recent call last):
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/utils.py", line 109, in instantiate
    return target(*args, **final_kwargs)
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra_plugins/hydra_ax_sweeper/ax_sweeper.py", line 16, in __init__
    from ._core import CoreAxSweeper
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra_plugins/hydra_ax_sweeper/_core.py", line 6, in <module>
    from ax.core import types as ax_types  # type: ignore
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/ax/__init__.py", line 31, in <module>
    from ax.modelbridge import Models
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/ax/modelbridge/__init__.py", line 10, in <module>
    from ax.modelbridge.factory import (
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/ax/modelbridge/factory.py", line 375, in <module>
    torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/torch/cuda/__init__.py", line 52, in is_available
    return torch._C._cuda_getDeviceCount() > 0
UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/_internal/utils.py", line 196, in run_and_report
    return func()
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/_internal/utils.py", line 356, in <lambda>
    overrides=args.overrides,
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in multirun
    config=cfg, config_loader=self.config_loader, task_function=task_function
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/core/plugins.py", line 116, in instantiate_sweeper
    sweeper = self._instantiate(config.hydra.sweeper)
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/core/plugins.py", line 90, in _instantiate
    plugin = instantiate(config=config, _target_=clazz)
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/utils.py", line 116, in instantiate
    ).with_traceback(sys.exc_info()[2])
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra/utils.py", line 109, in instantiate
    return target(*args, **final_kwargs)
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra_plugins/hydra_ax_sweeper/ax_sweeper.py", line 16, in __init__
    from ._core import CoreAxSweeper
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/hydra_plugins/hydra_ax_sweeper/_core.py", line 6, in <module>
    from ax.core import types as ax_types  # type: ignore
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/ax/__init__.py", line 31, in <module>
    from ax.modelbridge import Models
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/ax/modelbridge/__init__.py", line 10, in <module>
    from ax.modelbridge.factory import (
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/ax/modelbridge/factory.py", line 375, in <module>
    torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
  File "/home/circleci/project/.nox/test_plugins-3-7/lib/python3.7/site-packages/torch/cuda/__init__.py", line 52, in is_available
    return torch._C._cuda_getDeviceCount() > 0
UserWarning: Error instantiating/calling 'hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper' : CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)

```

**Comment by shagunsodhani** [comment]
This could be triggered because of the new PyTorch release? I do not know wether Ax pins the torch version when they setup Ax.

**Comment by shagunsodhani** [comment]
https://github.com/pytorch/botorch/blob/master/setup.py#L71 - botorch is using >= 1.6.0

**Comment by omry** [comment]
Since this seems like some upgrade issues from the PyTorch 1.7.0 upgrade, I think a better solution is to report to Ax and pin to 1.6.0 until the fix it.

**Comment by jieru-hu** [comment]
> Since this seems like some upgrade issues from the PyTorch 1.7.0 upgrade, I think a better solution is to report to Ax and pin PyTorch in the plugin to 1.6.0 until the fix it.

:) since the change is already in, I will keep this issue open  and revert the change once they fixed it on ax side.
