### ISSUE TITLE
[Bug] Pytorch Lightning loggers cannot be instantiated by hydra

### ISSUE THREAD

**Issue by piraka9011** [facebookresearch/hydra#1266]
# 🐛 Bug
## Description

When attempting to instantiate a pytorch lightning `Trainer`, passing an instantiated pytorch Logger does not work.

## Checklist
- [X] I checked on the latest version of Hydra (1.0.4)
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

Requires `pytorch-lightning`

```python
import hydra

@dataclass
class TrainerConf:
    _target_: str = "pytorch_lightning.trainer.Trainer"
    logger: Any = True # Union[LightningLoggerBase, Iterable[LightningLoggerBase], bool]
    # There are other params but left out for brevity

@dataclass
class WandbLoggerConfig:
    _target_: str = "pytorch_lightning.loggers.WandbLogger"
    save_dir: Optional[str] = None
    offline: bool = False,
    id: Optional[str] = None,
    anonymous: bool = False,
    version: Optional[str] = None,
    project: Optional[str] = None,
    log_model: bool = False,
    experiment = None,
    prefix: str = ''

# This works
logger_config = WandbLoggerConfig()
logger = hydra.utils.instantiate(config=logger_config)

# This doesn't. Throws error below
trainer_config = TrainerConf()
trainer = hydra.utils.instantiate(
        config=trainer_config,
        logger=logger,
    )
```

<details>
<summary>Stack trace/error message</summary>
<br>
<pre>
Traceback (most recent call last):
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 499, in _instantiate_class
    final_kwargs = _get_kwargs(config, **kwargs)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 598, in _get_kwargs
    params.merge_with(config_overrides)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 427, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/base.py", line 107, in _format_and_raise
    format_and_raise(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 613, in format_and_raise
    _raise(ex, cause)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 425, in merge_with
    self._merge_with(*others)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 444, in _merge_with
    other = _ensure_container(other, flags=my_flags)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 729, in _ensure_container
    target = OmegaConf.create(target, flags=flags)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 198, in create
    return OmegaConf._create_impl(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 277, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 613, in format_and_raise
    _raise(ex, cause)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 248, in _create_impl
    return DictConfig(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 106, in __init__
    format_and_raise(node=None, key=None, value=None, cause=ex, msg=str(ex))
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 613, in format_and_raise
    _raise(ex, cause)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 104, in __init__
    self._set_value(content, flags=flags)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 570, in _set_value
    raise e
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 567, in _set_value
    self._set_value_impl(value, flags)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 618, in _set_value_impl
    self.__setitem__(k, v)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 297, in __setitem__
    self._format_and_raise(key=key, value=value, cause=e)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/base.py", line 107, in _format_and_raise
    format_and_raise(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 678, in format_and_raise
    _raise(ex, cause)
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.UnsupportedValueType: Value 'TensorBoardLogger' is not a supported primitive type
	full_key: logger
	reference_type=Optional[Dict[Union[str, Enum], Any]]
	object_type=dict
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/allabana/sandbox/deepspeech.pytorch/train.py", line 21, in hydra_main
    train(cfg=cfg)
  File "/home/allabana/sandbox/deepspeech.pytorch/deepspeech_pytorch/training.py", line 62, in train
    trainer = hydra.utils.instantiate(
  File "/home/allabana/.virtualenvs/sttpy/lib/python3.8/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'pytorch_lightning.trainer.Trainer' : Value 'TensorBoardLogger' is not a supported primitive type
	full_key: logger
	reference_type=Optional[Dict[Union[str, Enum], Any]]
	object_type=dict
</pre>
</details>

## Expected Behavior

Trainer and logger should be instantiated correctly.

## System information
- **Hydra Version** :  1.0.4
- **Python version** : 3.8
- **Virtual environment type and version** : `virtualenv` 20.1.0
- **Operating system** : Ubuntu 20.04

**Comment by omry** [comment]
Thanks for reporting.
A workaround here is to set the logger to MISSING.

```
@dataclass
class TrainerConf:
    _target_: str = "pytorch_lightning.trainer.Trainer"
    logger: Any = omegaconf.MISSING
```

There are some major changes to instantiate coming in Hydra 1.1 that are already in master, including recursive instantiation.
You can learn about it [here](https://hydra.cc/docs/next/patterns/instantiate_objects/overview).
I tried your snippet and it worked as is, but I think you can actually much better by leveraging recursive instantiation there.

Hydra 1.1 is available as a dev release, check the README.

**Comment by piraka9011** [comment]
I'll try the latest Hydra 1.1, but I assumed from the docs recursive instantiation was already in 1.0.x.

**Comment by omry** [comment]
What in the 1.0 docs made you think that?

**Comment by piraka9011** [comment]
I was able to get this working on 1.1 using the suggested workaround.
It would be nice if there is support for `Union` types and direct support for these types as well :)

I think I was getting confused between the next and 1.0 docs, that's an issue on my end.

**Comment by omry** [comment]
> I was able to get this working on 1.1 using the suggested workaround.

I think you don't even need the workaround in 1.1

> It would be nice if there is support for Union types and direct support for these types as well :)

Nice indeed. This is planned and with some luck will be supported in 1.1.
