### ISSUE TITLE
[Bug] Submitit crashes when sweep dir contains `\=`

### ISSUE THREAD

**Issue by shubham-goel** [facebookresearch/hydra#1314]
# 🐛 Bug
## Description
Submitit crashes with an error when sweep directory contains `\=`, but the default launcher doesn't.
This could be a rather common occurence when the app contains `hydra.job.override_dirname` in the sweep dir, and a filename (say a checkpoint from a previous experiment) is passed in command line.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

test.py
```python
import hydra
@hydra.main(config_name="test")
def main(cfg):
    print(cfg.a)
main()
```
test.yaml 
```yaml
hydra:
  run:
    dir: outputs/${hydra.job.config_name}_${hydra.job.override_dirname}
  sweep:
    dir: ${hydra.run.dir}
``` 

**Stack trace/error message**
Submitit works when arguments don't contain `\=`
```
$ python test.py +a="0" hydra/launcher=submitit_slurm hydra.launcher.partition=dev -m
[2021-01-21 08:05:17,637][HYDRA] Submitit 'slurm' sweep output dir : outputs/test_+a=0
[2021-01-21 08:05:17,639][HYDRA]        #0 : +a=0
```

Default launcher works when arguments contain `\=`:
```
$ python test.py +a="\=0" +b=0                                                                                             
=0
```

Submitit fails when arguments contain `\=`
```
$ python test.py +a="\=0" hydra/launcher=submitit_slurm hydra.launcher.partition=dev -m
[2021-01-21 08:06:01,298][HYDRA] Submitit 'slurm' sweep output dir : outputs/test_+a=\=0
[2021-01-21 08:06:01,302][HYDRA]        #0 : +a=\=0
Traceback (most recent call last):
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 373, in <lambda>
    lambda: hydra.multirun(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 139, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 150, in launch
    return [j.results()[0] for j in jobs]
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 150, in <listcomp>
    return [j.results()[0] for j in jobs]  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 289, in results
    outcome, result = self._get_outcome_and_result()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 368, in _get_outcome_and_result    raise utils.UncompletedJobError(submitit.core.utils.UncompletedJobError: Job 35092817 (task: 0) with path /private/home/shubhamgoel/code/3Dify/hydra_test/outputs/test_+a=\=0/.submitit/35092817/35092817_0_result.pkl
has not produced any output (state: FAILED)
Error stream produced:
----------------------
None
```

Files produced:
```
$ tree -a outputs/
outputs/
├── test_+a=0
│   ├── .submitit
│   │   └── 35092688
│   │       ├── 35092688_0_log.err
│   │       ├── 35092688_0_log.out
│   │       ├── 35092688_0_result.pkl
│   │       ├── 35092688_submission.sh
│   │       └── 35092688_submitted.pkl
│   ├── 0
│   │   ├── .hydra
│   │   │   ├── config.yaml
│   │   │   ├── hydra.yaml
│   │   │   └── overrides.yaml
│   │   └── test.log
│   └── multirun.yaml
├── test_+a=\=0
│   ├── .submitit
│   │   └── 35092817
│   │       ├── 35092817_submission.sh
│   │       └── 35092817_submitted.pkl
│   └── multirun.yaml
└── test_+a=\=0,+b=0
    ├── .hydra
    │   ├── config.yaml
    │   ├── hydra.yaml
    │   └── overrides.yaml
    └── test.log

10 directories, 17 files
```

## Expected Behavior
Submitit plugin should not throw an error.

## System information
- **Hydra Version** :  1.1.0dev1
- **Python version** : 3.8.5
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Ubuntu 20.04.1 LTS

**Comment by omry** [comment]
Thanks for reporting.
1. Can you look at the submitit stdout and stderr files? (they should be somewhere under the job output dir). anything interesting there?
2. Can you try to reproduce it using submitit directly?
It will help understand if this is something in the plugin or in submitit itself.

**Comment by jieru-hu** [comment]
Hi @shubham-goel 

This [wiki](https://hydra.cc/docs/next/advanced/override_grammar/basic/#working-with-your-shell) might also be helpful for your to do commandline override.

for example a recommended way to do overrides
```
python my_app.py '+foo="a=b"'
```
`echo` is a helpful way to see what the shell is doing before passing the override. You can see more examples in the doc linked above.

**Comment by shubham-goel** [comment]
Thanks for pointing to it, @jieru-hu! FYI - problem persists even if I override using this recommended way.

@omry the stdout/stderr files aren't even created! Notice that only the `_submission.sh` and `_submission.pkl` files are created in `outputs/test_+a=\=0`. Let me try replicating the issue with submitit.

**Comment by shubham-goel** [comment]
I could replicate the error with submitit directly! Created issue facebookincubator/submitit#1600

submitit_test.py
```python
import submitit

def add(a, b):
    return a + b

executor = submitit.AutoExecutor(folder='submitit_outputs/test_+a="=0"/%j')
executor.update_parameters(timeout_min=4, slurm_partition="priority", slurm_comment='iccv')

job = executor.submit(add, 5, 7)  # will compute add(5, 7)
print(job.job_id)  # ID of your job

output = job.result()  # waits for the submitted function to complete and returns its output
# if ever the job failed, job.result() will raise an error with the corresponding trace
assert output == 12  # 5 + 7 = 12...  your addition was computed in the cluster
```

Output
```
$ python submitit_test.py 
35101372
Traceback (most recent call last):
  File "submitit_test.py", line 22, in <module>
    output = job.result()  # waits for the submitted function to complete and returns its output
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 266, in result
    r = self.results()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 289, in results
    outcome, result = self._get_outcome_and_result()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 368, in _get_outcome_and_result
    raise utils.UncompletedJobError(
submitit.core.utils.UncompletedJobError: Job 35101372 (task: 0) with path /private/home/shubhamgoel/code/3Dify/hydra_test/submitit_outputs/test_+a="=0"/35101372/35101372_0_result.pkl
has not produced any output (state: FAILED)
Error stream produced:
----------------------
None
```

**Comment by omry** [comment]
Great.
Now, about your underlying issue:
I am guessing that your problem is that you are trying to use a checkpoint path in a parameter and it has `=` inside:

```
$ python train.py checkpoint_file=/foo/bar/a=10,b=20
```
And because you have `override_dirname` in your path, the checkpoint_file variable is encoded into the new path.
inception!

If that's the case, you should be able to solve it by excluding that variable from the `override_dirname`.
See the [docs](https://hydra.cc/docs/configure_hydra/job#hydrajoboverride_dirname).

**Comment by shubham-goel** [comment]
Hi @omry, thank you so much for the suggestion, and your prompt responses! That's what I'm doing right now, but with an additional cmd-line option to change the path slightly to reflect this checkpoint choice. That makes it a little ugly though.

As a slightly more elegant solution that avoids using the extra option, I also created a separate `test1.yaml` config file containing `checkpoint_file: "/foo/bar/a=10,b=20"`. However, I ran into an orthogonal error while using `python test.py --config-name=test1`. Here is a minimal repro. Is this a bug, or am I doing something wrong?

`test.py` is same as above.

**test.yaml**
```yaml
a: ${hydra:job.config_name}
```

**test1.yaml**
```yaml
defaults:
  - test
a: 1
```

`python test.py --config-name=test1` causes an error, trace below. The error goes away when I change `test.yaml` to `a: ${hydra.job.config_name}` but then `python test.py` stops working.

Error trace:
```
$ python test.py --config-name=test1
Traceback (most recent call last):
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    lambda: hydra.run(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 101, in run
    cfg = self.compose_config(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 542, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    return self._load_configuration_impl(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 191, in _load_configuration_impl
    cfg, composition_trace = self._compose_config_from_defaults_list(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 424, in _compose_config_from_defaults_list
    merged = OmegaConf.merge(cfg, loaded.config)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 355, in merge
    target.merge_with(*others[1:])
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 427, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/base.py", line 107, in _format_and_raise
    format_and_raise(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/_utils.py", line 678, in format_and_raise
    _raise(ex, cause)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
ValueError: HydraConfig was not set
        full_key: job.config_name
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
        full_key: 
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```

Setting `OC_CAUSE=1`:
```
$ OC_CAUSE=1 python test.py --config-name=test1
Traceback (most recent call last):
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/base.py", line 373, in _resolve_simple_interpolation
    value = resolver(root_node, inter_key)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 388, in caching
    cache[key] if key in cache else resolver(*OmegaConf._tokenize_args(key))
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/core/utils.py", line 153, in <lambda>
    lambda path: OmegaConf.select(cast(DictConfig, HydraConfig.get()), path),
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/core/hydra_config.py", line 31, in get
    raise ValueError("HydraConfig was not set")
ValueError: HydraConfig was not set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 425, in merge_with
    self._merge_with(*others)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 447, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 317, in _map_merge
    target_node = dest_node._dereference_node(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/base.py", line 135, in _dereference_node
    v = parent._resolve_simple_interpolation(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/base.py", line 382, in _resolve_simple_interpolation
    self._format_and_raise(key=inter_key, value=None, cause=e)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/base.py", line 107, in _format_and_raise
    format_and_raise(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/_utils.py", line 678, in format_and_raise
    _raise(ex, cause)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
ValueError: HydraConfig was not set
        full_key: job.config_name
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    lambda: hydra.run(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 101, in run
    cfg = self.compose_config(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 542, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    return self._load_configuration_impl(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 191, in _load_configuration_impl
    cfg, composition_trace = self._compose_config_from_defaults_list(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 424, in _compose_config_from_defaults_list
    merged = OmegaConf.merge(cfg, loaded.config)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 355, in merge
    target.merge_with(*others[1:])
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 427, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/base.py", line 107, in _format_and_raise
    format_and_raise(
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/_utils.py", line 678, in format_and_raise
    _raise(ex, cause)
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
ValueError: HydraConfig was not set
        full_key: job.config_name
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
        full_key: 
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```

**Comment by omry** [comment]
This is probably a bug. Please file a separate issue.

**Comment by omry** [comment]
> Hi @omry, thank you so much for the suggestion, and your prompt responses! That's what I'm doing right now, but with an additional cmd-line option to change the path slightly to reflect this checkpoint choice. That makes it a little ugly though.

Well, you can also exclude that additional option from override dirname, right?

**Comment by shubham-goel** [comment]
> > Hi @omry, thank you so much for the suggestion, and your prompt responses! That's what I'm doing right now, but with an additional cmd-line option to change the path slightly to reflect this checkpoint choice. That makes it a little ugly though.
> 
> Well, you can also exclude that additional option from override dirname, right?

Yes! Thanks @omry. To clarify: I'm able to run my code successfully by adding `checkpoint_file` to override dirname and running `python train.py checkpoint_file=/foo/bar/a=10,b=20 +chkpt_a20b20=xyz`. I was just looking for other solutions because this isn't the most elegant, but it's okay if they don't exist right now :)

Closing this issue since it needs to be addressed by submitit.
