### ISSUE TITLE
[Bug] hydra-joblib-launcher cannot find context for 'locky'  when run with wandb

### ISSUE THREAD

**Issue by qshzh** [facebookresearch/hydra#1320]
# 🐛 Bug
## Description
Hydra-joblib-launcher reports `cannot find context for 'locky' ` when run with wandb

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
[gist](https://gist.github.com/tomsercu/72acb8a435afcda0043ba351536d821a) 

> cat testconf.yaml
```
defaults:
  - hydra/launcher: joblib
learning_rate: 0.8
```
** Stack trace/error message **

**hydra-1.0.0**
> python bug.py -m learning_reate=1
```
[2021-01-21 21:55:52,794][HYDRA] Joblib.Parallel(n_jobs=-1,backend=loky,prefer=processes,require=None,verbose=0,timeout=None,pre_dispatch=2*n_jobs,batch_size=auto,temp_folder=None,max_nbytes=None,mmap_mode=r) is launching 1 jobs
[2021-01-21 21:55:52,794][HYDRA] Launching jobs, sweep output dir : multirun/2021-01-21/21-55-52
[2021-01-21 21:55:52,794][HYDRA]        #0 : learning_rate=1
wandb: Currently logged in as: qinsheng (use `wandb login --relogin` to force relogin)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/spawn.py", line 220, in prepare
    set_start_method(data['start_method'], force=True)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/context.py", line 238, in get_context
    return super().get_context(method)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'loky'
Problem at: bug.py 15 run_train
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra_plugins/hydra_joblib_launcher/_core.py", line 47, in execute_job
    job_subdir_key="hydra.sweep.subdir",
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "bug.py", line 15, in run_train
    project='foo'
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 618, in init
    run = wi.init()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 462, in init
    raise UsageError(error_message)
wandb.errors.error.UsageError: Error communicating with backend
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/utils.py", line 358, in <lambda>
    overrides=args.overrides,
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra_plugins/hydra_joblib_launcher/joblib_launcher.py", line 46, in launch
    launcher=self, job_overrides=job_overrides, initial_job_idx=initial_job_idx
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra_plugins/hydra_joblib_launcher/_core.py", line 110, in launch
    for idx, overrides in enumerate(job_overrides)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
wandb.errors.error.UsageError: Error communicating with backend
[2021-01-21 21:56:35,480][HYDRA] Internal process exited
```

**hydra-1.1.0**
```
/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:394: UserWarning: In testconf: Invalid overriding of hydra/launcher:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/defaults_list_override for more information.

  warnings.warn(msg, UserWarning)
[2021-01-21 21:45:35,072][HYDRA] Joblib.Parallel(n_jobs=-1,backend=loky,prefer=processes,require=None,verbose=0,timeout=None,pre_dispatch=2*n_jobs,batch_size=auto,temp_folder=None,max_nbytes=None,mmap_mode=r) is launching 1 jobs
[2021-01-21 21:45:35,072][HYDRA] Launching jobs, sweep output dir : multirun/2021-01-21/21-45-34
[2021-01-21 21:45:35,072][HYDRA]        #0 : learning_rate=1
/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:394: UserWarning: In testconf: Invalid overriding of hydra/launcher:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/defaults_list_override for more information.

  warnings.warn(msg, UserWarning)
wandb: Currently logged in as: qinsheng (use `wandb login --relogin` to force relogin)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/spawn.py", line 220, in prepare
    set_start_method(data['start_method'], force=True)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/context.py", line 238, in get_context
    return super().get_context(method)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/multiprocessing/context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'loky'
Problem at: bug.py 15 run_train
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra_plugins/hydra_joblib_launcher/_core.py", line 47, in execute_job
    job_subdir_key="hydra.sweep.subdir",
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/core/utils.py", line 129, in run_job
    ret.return_value = task_function(task_cfg)
  File "bug.py", line 15, in run_train
    project='foo'
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 618, in init
    run = wi.init()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 462, in init
    raise UsageError(error_message)
wandb.errors.error.UsageError: Error communicating with backend
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/utils.py", line 376, in <lambda>
    overrides=args.overrides,
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 139, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra_plugins/hydra_joblib_launcher/joblib_launcher.py", line 46, in launch
    launcher=self, job_overrides=job_overrides, initial_job_idx=initial_job_idx
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/hydra_plugins/hydra_joblib_launcher/_core.py", line 110, in launch
    for idx, overrides in enumerate(job_overrides)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/zqs/anaconda3/envs/dev/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
wandb.errors.error.UsageError: Error communicating with backend
```

## System information
- **Hydra Version** :  1.0.0 / 1.1.0
- **Python version** : 3.7
- **Virtual environment type and version** : conda 4.9.1, wandb, version 0.10.14
- **Operating system** : ubuntu 20.04

## Additional context

Error [wandb/client#1314](https://github.com/wandb/client/issues/1314) drives me to try joblib launcher instead the default one .  If without wandb, the launcher works well.

**Comment by omry** [comment]
Thanks for reporting.
This seems to be the same issue reported [here](https://github.com/wandb/client/issues/1525), which probably means it has nothing to do with Hydra.

**Comment by omry** [comment]
Someone even reported there that it works with Hydra. Give it a shot. closing for now.

**Comment by qshzh** [comment]
Ohhh. Great thanks for your help! Sorry, I should check possible duplicate wandb issues. :/
