### ISSUE TITLE
[Bug] Incorrect subtyping in hydra-core-1.1.0.dev3

### ISSUE THREAD

**Issue by lematt1991** [facebookresearch/hydra#1351]
# 🐛 Bug
## Description
Incorrect subtyping in hydra-core-1.1.0.dev3

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```Python
from dataclasses import dataclass, field
from hydra.core.config_store import ConfigStore
import hydra
from omegaconf import MISSING
from typing import Any

@dataclass
class Super:
    x: int = MISSING

@dataclass
class Sub(Super):
    x: int = 4

@dataclass
class Config:
    defaults: Any = field(default_factory=lambda: [
        {"instance": "sub"}
    ])
    instance: Super = Super()
    
cs = ConfigStore.instance()
cs.store(group="instance", name="super", node=Super)
cs.store(group="instance", name="sub", node=Sub)
cs.store( name="config", node=Config)


@hydra.main( config_path=".", config_name="config" )
def main(cfg):
    print(cfg)

main()
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 425, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 455, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/base.py", line 147, in _format_and_raise
    format_and_raise(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/_utils.py", line 683, in format_and_raise
    _raise(ex, cause)
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/_utils.py", line 593, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: Invalid type assigned : Super is not a subclass of Sub. value: {'x': '???'}
        full_key: 
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 33, in <module>
    main()
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/main.py", line 33, in decorated_main
    _run_hydra(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/utils.py", line 364, in _run_hydra
    run_and_report(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/utils.py", line 215, in run_and_report
    raise ex
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    lambda: hydra.run(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 101, in run
    cfg = self.compose_config(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 542, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration_impl(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 192, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 427, in _compose_config_from_defaults_list
    raise ConfigCompositionException(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 425, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 455, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/base.py", line 147, in _format_and_raise
    format_and_raise(
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/_utils.py", line 683, in format_and_raise
    _raise(ex, cause)
  File "/private/home/mattle/.conda/envs/ricci-filtering/lib/python3.8/site-packages/omegaconf/_utils.py", line 593, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
hydra.errors.ConfigCompositionException: In 'config': Validation error while composing config:
Invalid type assigned : Super is not a subclass of Sub. value: {'x': '???'}
        full_key: 
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```

## Expected Behavior
This should not produce an error (and doesn't produce an error in hydra-1.0.5)

## System information
- **Hydra Version** :  1.1.0.dev3
- **Python version** : 3.8.6
- **Virtual environment type and version** : conda 4.9.2
- **Operating system** : linux

**Comment by omry** [comment]
You are hitting on one of the subtle changes in Hydra 1.1 (which is a breaking change).
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/default_composition_order

**Comment by lematt1991** [comment]
Ah makes sense, thanks for the clarification @omry!

**Comment by omry** [comment]
One more thing:
A cleaner way to deal with it is to leave the instance MISSING in config and allow the defaults list to compose the right version in.
This works without changing the composition order.

I mentioned "new handling of MISSING fields to make this a bit more intuitive".
This is what makes it possible:

```python
from dataclasses import dataclass, field
from hydra.core.config_store import ConfigStore
import hydra
from omegaconf import MISSING
from typing import Any

@dataclass
class Super:
    x: int = MISSING

@dataclass
class Sub(Super):
    x: int = 4

@dataclass
class Config:
    defaults: Any = field(default_factory=lambda: [
        {"instance": "sub"}
    ])
    instance: Super = MISSING   # <<-- HERE!
    
cs = ConfigStore.instance()
cs.store(group="instance", name="super", node=Super)
cs.store(group="instance", name="sub", node=Sub)
cs.store( name="config", node=Config)


@hydra.main( config_path=".", config_name="config" )
def main(cfg):
    print(cfg)

main()
```

```
$ python 1.py 
{'instance': {'x': 4}}
$ python 1.py instance=sub
{'instance': {'x': 4}}
$ python 1.py instance=super
{'instance': {'x': '???'}}
```

**Comment by addisonklinke** [comment]
Could we eventually have something like `@hydra.main(config_name: str, defaults_list_overrides: bool = False)` so that the behavior could be managed in a central location rather than adjusting all relevant config nodes? This would also make the writer's intent more clear for someone reading the code who's unfamiliar with this particular Hydra migration

**Comment by omry** [comment]
It's hard to understand exactly what you mean by "defaults_list_overrides", but if I understand you correctly:
No. there are no plans to allow for the default composition order to be changed in a central place. 
This is in conflict with the fact that Hydra enables you to compose configs different libraries at the same time.

**Comment by addisonklinke** [comment]
My intention was to mimic the two composition approaches described in the migration [doc](https://hydra.cc/docs/next/upgrades/1.0_to_1.1/default_composition_order/)

- `defaults_list_overrides=False`: config.yaml is overriding configs from the Defaults List (1.1)
- `defaults_list_overrides=True`: configs from the Defaults List are overriding config.yaml (1.0)

From what you said, it sounds like the changes in 1.1 are more involved than a simple boolean flag though

**Comment by omry** [comment]
The changes in 1.1 are a complete rewrite of the config composition logic in Hydra that took 3 months of blood and sweat.

If I end up getting a complaints from many people getting bit by the change to the default composition order I may require people to specify `_self_` in all Default Lists in Hydra 1.1 to force an explicit decision.
I would rather avoid it because I think this is only tripping a small percentage of the users.
