### ISSUE TITLE
[Bug][Ax-plugin]Plugin raises SearchSpaceExhausted Exception when the search space is exhausted.

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#1386]
# 🐛 Bug
## Description

Same as title.

## Checklist
- [ y] I checked on the latest version of Hydra
- [ y] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```
cd hydra/plugins/hydra_ax_sweeper
python tests/apps/polynomial.py -m polynomial.y=1 'polynomial.x=range(2,4)'
```

** Stack trace/error message **
```
[2021-02-07 09:03:38,001][HYDRA] AxSweeper is optimizing the following parameters: 
polynomial.x: choice=[2, 3]
polynomial.y: fixed=1
[INFO 02-07 09:03:38] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter polynomial.x. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-07 09:03:38] ax.modelbridge.dispatch_utils: Using Sobol generation strategy.
Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 373, in <lambda>
    lambda: hydra.multirun(
  File "/private/home/sodhani/projects/hydra/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/private/home/sodhani/projects/hydra/plugins/hydra_ax_sweeper/hydra_plugins/hydra_ax_sweeper/ax_sweeper.py", line 29, in sweep
    return self.sweeper.sweep(arguments)
  File "/private/home/sodhani/projects/hydra/plugins/hydra_ax_sweeper/hydra_plugins/hydra_ax_sweeper/_core.py", line 142, in sweep
    batch_of_trials = get_one_batch_of_trials(
  File "/private/home/sodhani/projects/hydra/plugins/hydra_ax_sweeper/hydra_plugins/hydra_ax_sweeper/_core.py", line 79, in get_one_batch_of_trials
    parameters, trial_index = ax_client.get_next_trial()
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/utils/common/executils.py", line 98, in actual_wrapper
    return func(*args, **kwargs)
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/service/ax_client.py", line 307, in get_next_trial
    generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/service/ax_client.py", line 910, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/modelbridge/generation_strategy.py", line 400, in gen
    return self._gen_multiple(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/modelbridge/generation_strategy.py", line 479, in _gen_multiple
    generator_run = model.gen(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/modelbridge/base.py", line 621, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/modelbridge/random.py", line 86, in _gen
    X, w = self.model.gen(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/models/random/sobol.py", line 112, in gen
    points, weights = super().gen(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/models/random/base.py", line 109, in gen
    points, attempted_draws = rejection_sample(
  File "/private/home/sodhani/.conda/envs/hydra/lib/python3.8/site-packages/ax/models/model_utils.py", line 111, in rejection_sample
    raise SearchSpaceExhausted(
ax.exceptions.core.SearchSpaceExhausted: Rejection sampling error (specified maximum draws (10000) exhausted, without finding sufficiently many (1) candidates). This likely means that there are no new points left in the search space.
```

## Expected Behavior
Handle the exception in the plugin

## System information
- **Hydra Version** :  master
- **Python version** : 3.8
- **Virtual environment type and version** : 
- **Operating system** : ubuntu 20.04

## Additional context
Originally reported by Omry

**Comment by bernardbeckerman** [comment]
@shagunsodhani I just want to make sure I understand the desired behavior. Right now Ax is exiting with an error, and you'd prefer that it not fail, but instead simply stop suggesting new points, complete the search, and return the best objective and the corresponding parameters found thus far? Do I have that right?

**Comment by shagunsodhani** [comment]
Yes that is correct.

Cheers,
Shagun
https://shagunsodhani.com

**Comment by omry** [comment]
@shagunsodhani, @bernardbeckerman, is there a plan to do anything here?

**Comment by shagunsodhani** [comment]
Not on the Hydra side. We handled the exception on Hydra side with this [PR](https://github.com/facebookresearch/hydra/pull/1387)

**Comment by omry** [comment]
Thanks.
Closing this. If there is an Ax change that requires followup it should be in a new issue.
