### ISSUE TITLE
Cannot overwrite a field called 'wandb' when using structured configs

### ISSUE THREAD

**Issue by MatiasFrank** [facebookresearch/hydra#1533]
When using structured configs, I cannot overwrite a field in my Config-class `wandb` from the terminal. More specifically, I have the following minimal file `config.py`

```
from dataclasses import dataclass
import hydra
from hydra.core.config_store import ConfigStore


@dataclass
class Config:
    wandb: int = 1


cs = ConfigStore.instance()
cs.store(name="config", node=Config)


@hydra.main(config_name="config")
def main(cfg):
    print(cfg)


if __name__ == "__main__":
    main()
```

And when running
`python3 config.py wandb=2`
I get the following error
```
Traceback (most recent call last):
  File "/Users/macbook/Developer/speciale/graph/python/config.py", line 21, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()  
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 100, in run
    cfg = self.compose_config(
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(  
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 252, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_defaults(config_group_overrides, defaults)
  File "/usr/local/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 453, in _apply_overrides_to_defaults
    raise ConfigCompositionException(msg)
hydra.errors.ConfigCompositionException: Could not override 'wandb'. No match in the defaults list.
To append to your default list use +wandb=2
```
yet it should just overwrite the `wandb` value without a problem.
I am running Python 3.9.1 and Hydra 1.0.6 on macOS 11.2.3. 
I have tried with some other names close to `wandb` e.g. `wand`, `wndb`, `andb` and they work fine.

**Comment by omry** [comment]
You have a directory wandb next to your script that is interpreted as a config group.

The following is on master, but it should be similar on 1.0.6:
```
$ python 1533.py wandb=3
{'wandb': 3}
$ mkdir wandb
$ python 1533.py wandb=3
Traceback (most recent call last):
  File "/home/omry/dev/hydra/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/omry/dev/hydra/hydra/_internal/utils.py", line 370, in <lambda>
    lambda: hydra.run(
  File "/home/omry/dev/hydra/hydra/_internal/hydra.py", line 87, in run
    cfg = self.compose_config(
  File "/home/omry/dev/hydra/hydra/_internal/hydra.py", line 534, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/omry/dev/hydra/hydra/_internal/config_loader_impl.py", line 145, in load_configuration
    return self._load_configuration_impl(
  File "/home/omry/dev/hydra/hydra/_internal/config_loader_impl.py", line 231, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/omry/dev/hydra/hydra/_internal/defaults_list.py", line 711, in create_defaults_list
    overrides = Overrides(repo=repo, overrides_list=overrides_list)
  File "/home/omry/dev/hydra/hydra/_internal/defaults_list.py", line 92, in __init__
    raise ValueError(
ValueError: Config group override must be a string or a list. Got int

$ python 1533.py wandb=aa
Could not override 'wandb'. No match in the defaults list.
To append to your default list use +wandb=aa

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

If you do not pass a config path, the directory of your script is added to the config search path.
Options:
1. pass config_path e.g: `@hydra.main(config_path="conf", config_name="config")` (recommended)
2. delete your wandb directory

**Comment by MatiasFrank** [comment]
Thanks, that fixes it!
