### ISSUE TITLE
[Bug] Additional config search paths are not included when using --info defaults commands

### ISSUE THREAD

**Issue by brian-bazyk** [facebookresearch/hydra#1557]
# 🐛 Bug
## Description
When running hydra apps with additional paths added to the hydra search paths and the command line option `--info defaults` or `--info` is used it seems the additional config search paths are not included. If the config refers to another config in one of the additional config search path locations then a missing config exception will be raised.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** SIMPLER REPRO **
Run `python examples/advanced/config_search_path/my_app.py dataset=imagenet --info`

** ORIGINAL REPRO - Minimal Code/Config snippet to reproduce **

In `examples/advanced/config_search_path/conf/config.yaml` change `dataset: cifar10` to `dataset: imagenet`
Run `python examples/advanced/config_search_path/my_app.py --info defaults`

** Stack trace/error message **
```
~/hydra$ python examples/advanced/config_search_path/my_app.py --info defaults
Traceback (most recent call last):
  File "examples/advanced/config_search_path/my_app.py", line 13, in <module>
    my_app()
  File "/venv/lib/python3.8/site-packages/hydra/main.py", line 29, in decorated_main
    _run_hydra(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 400, in _run_hydra
    hydra.show_info(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 610, in show_info
    options[info](config_name=config_name, overrides=overrides)
  File "/venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 447, in _print_defaults_list
    defaults = self.config_loader.compute_defaults_list(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 525, in compute_defaults_list
    defaults_list = create_defaults_list(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 712, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 682, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 337, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 420, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 262, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 532, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 475, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 451, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/venv/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 766, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'config': Could not find 'dataset/imagenet'

Available options in 'dataset':
        cifar10
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/brian/hydra/examples/advanced/config_search_path/conf
        provider=schema, path=structured://
```

## Expected Behavior
Expect no exception to occur and for both `imagenet` and `cifar10` to appear as available options in `dataset` from the `--info defaults` output.
Also expect `additional_conf` to appear in the `Config search path:` listing in `--info defaults` output.

## System information
- **Hydra Version** :  1.1.0dev5
- **Python version** : 3.8.7
- **Virtual environment type and version** : 
- **Operating system** : 18.04.5 LTS (Bionic Beaver)

## Additional context
n/a

**Comment by omry** [comment]
Looks like it's working on master:
```
$ python examples/advanced/config_search_path/my_app.py --info defaults

Defaults List
*************
| Config path                 | Package             | _self_ | Parent       | 
------------------------------------------------------------------------------
| hydra/output/default        | hydra               | False  | hydra/config |
| hydra/launcher/basic        | hydra.launcher      | False  | hydra/config |
| hydra/sweeper/basic         | hydra.sweeper       | False  | hydra/config |
| hydra/help/default          | hydra.help          | False  | hydra/config |
| hydra/hydra_help/default    | hydra.hydra_help    | False  | hydra/config |
| hydra/hydra_logging/default | hydra.hydra_logging | False  | hydra/config |
| hydra/job_logging/default   | hydra.job_logging   | False  | hydra/config |
| hydra/env/default           | hydra.env           | False  | hydra/config |
| hydra/config                | hydra               | True   | <root>       |
| dataset/cifar10             | dataset             | False  | config       |
| config                      |                     | True   | <root>       |
------------------------------------------------------------------------------
```

**Comment by brian-bazyk** [comment]
Did you change dataset to refer to `imagenet` which is in the other config location?

**Comment by brian-bazyk** [comment]
Updated with even simpler repro that doesn't involve changing example's config.yaml.
