### ISSUE TITLE
[Bug] Removing multiple items from the defaults list

### ISSUE THREAD

**Issue by fses91** [facebookresearch/hydra#1608]
# 🐛 Bug 
## Description 
Hi, my problem is the following:

I am trying to run two different config settings: Setting1 and Setting2 as shown below, with the repository mentioned below, for the Setting2 I got an IndexError. I just want to remove *grp2* and *grp4* from the defaults list. If I remove only one then it works. I am using https://hydra.cc/docs/advanced/override_grammar/basic#modifying-the-defaults-list as reference.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repository (https://github.com/fses91/improved-spork).

### Setting 1:
Command-line arguments:
```
python main.py ~grp2 
```
Output:
```
grp1:
  text: grp1
grp3:
  text: grp3
grp4:
  text: grp4
```

### Setting 2:
Command-line arguments:
```
python main.py ~grp2 ~grp4
```

Output:
```
Traceback (most recent call last):
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run
    run_mode=RunMode.RUN,
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 252, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_defaults(config_group_overrides, defaults)
  File "/home/florian/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 418, in _apply_overrides_to_defaults
    del defaults[pair.idx]
IndexError: list assignment index out of range
```

## Expected Behavior
I expect the following output for Setting2, where *grp2* and *grp4* are removed.
```
grp1:
  text: grp1
grp3:
  text: grp3
```

## System information
- **Hydra Version** :  1.0.6
- **Python version** : 3.7.9
- **Virtual environment type and version** : [just using hydra and python for illustration purposes]
- **Operating system** : Ubuntu 20.04.2 LTS

## Additional context
I think the problem lies here https://github.com/facebookresearch/hydra/blob/v1.0.6/hydra/_internal/config_loader_impl.py#L418, because we are removing configs based on the index, it is no problem for the first removal, but for 2 or more the indices in the list are not valid anymore, because some items were already removed. Another problem that can occur is that we are removing the wrong default values because the indices are not matching anymore.

**Comment by omry** [comment]
Please try on Hydra 1.1. There have been a complete rewrite of the logic related to this.

**Comment by fses91** [comment]
With Hydra 1.1 it works as expected.

**Comment by omry** [comment]
Great.
