### ISSUE TITLE
[bug] Interpolation of `hydra/launcher` configuration name in defaults list causes `hydra.errors.ConfigCompositionException`

### ISSUE THREAD

**Issue by nikvaessen** [facebookresearch/hydra#1668]
**Describe the bug**
By switching from version `1.0` to `1.1`, this configuration:

```yaml
defaults:
  ...
  - override hydra/launcher: ${oc.env:HYDRA_LAUNCHER}
```
throws the following error:
```
$ HYDRA_FULL_ERROR=1 python main.py
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    run_hydra_config()
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 87, in run
    cfg = self.compose_config(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 564, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 146, in load_configuration
    return self._load_configuration_impl(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 239, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 719, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 689, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 337, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 420, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 262, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/nik/.cache/pypoetry/virtualenvs/hydra-bug-report-rkSIWX38-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 550, in _create_defaults_tree_impl
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: In 'hydra/config': Defaults List interpolation is only supported in the primary config

```

**To Reproduce**

zip file with a stand-alone repo to reproduce: [hydra-core-bug-report.zip](https://github.com/omry/omegaconf/files/6636823/hydra-core-bug-report.zip)

#### environment variables
```
# either `basic` or `slurm`
HYDRA_LAUNCHER=basic
```
#### main python script 
``` python
# main.py
import hydra
from omegaconf import DictConfig, OmegaConf
from dotenv import load_dotenv


@hydra.main(config_path="config", config_name="main")
def run_hydra_config(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    load_dotenv()
    run_hydra_config()
```
#### configuration directory
```yaml
# config/main.yaml
defaults:
  - override hydra/launcher: ${oc.env:HYDRA_LAUNCHER}
```

**Expected behavior**

The configuration should behave the same as explicitly writing down the configuration name instead of interpolating it:

```yaml
defaults:
  - override hydra/launcher: slurm
```

**Additional context**
- [ ] - **Hydra Version** :   version: 1.1
- [ ] Python version: 3.8
- [ ] Operating system: ubuntu 20.04

**Comment by omry** [comment]
Thanks for reporting, we will take a look.

**Comment by omry** [comment]
This was never formally supported and worked accidentally.
I have a solution that enables it, but there is a possibility that we will need to officially drop support for this.

I recommend that you override your defaults list from the command line and not from an environment variable.

**Comment by rikrd** [comment]
This issue also occurs when using the experiments setup https://hydra.cc/docs/patterns/configuring_experiments  and trying to set in the defaults nested numeric parameters.

**Comment by omry** [comment]
@rikrd, It sounds like a different issue (and it's not very clear too). Please file a separate bug report with a minimal repro.
