### ISSUE TITLE
[Bug] Top level config has to be OmegaConf DictConfig, plain dict, or a Structured Config class or instance

### ISSUE THREAD

**Issue by ishandutta0098** [facebookresearch/hydra#1704]
# 🐛 Bug
## Description
I am creating a Multilingual Text Classifier using PyTorch Lightning and Hydra. I am using [this](https://github.com/ashleve/lightning-hydra-template) template as reference for the project. However when I try to run the `run.py` file I keep getting an error.

# Relevant Files

## run.py
```
import dotenv
import hydra
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig
from pathlib import Path

dotenv.load_dotenv(override = True)

import sys
sys.path.append("/workspace/data/multilingual-text-classifier/src")

@hydra.main(config_path="/workspace/data/multilingual-text-classifier/configs/", config_name="config.yaml")
def main(config: DictConfig):

    # Imports should be nested inside @hydra.main to optimize tab completion
    # Read more here: https://github.com/facebookresearch/hydra/issues/934
    
    hydra_dir = Path(HydraConfig.get().run.dir)
    
    from train import train

    # Train model
    return train(config)

if __name__ == "__main__":
    main()
``` 

 ## train.py
```
import hydra
from omegaconf import DictConfig
from pytorch_lightning import (
                        LightningDataModule,
                        LightningModule,
                        Trainer,
                        seed_everything
                    )

from datamodules.datamodule import JigsawDataModule

# Lightning
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping
from pytorch_lightning.loggers import TensorBoardLogger

from models.model import BERTModel

from termcolor import colored
import time

from typing import Optional

def train(config: DictConfig) -> Optional[float]:
       
    model: LightningModule =  hydra.utils.instantiate(config.model)

    logger = TensorBoardLogger("lightning_logs", name="toxic-comments")

    early_stopping_callback = EarlyStopping(monitor='val_loss', patience=2)

    trainer = pl.Trainer(
                logger=logger,
                callbacks=[early_stopping_callback],
                max_epochs=2,
                gpus=[0],
                progress_bar_refresh_rate=30,
                precision= 32
            )

    trainer.fit(model, datamodule = JigsawDataModule)

    trainer.save_checkpoint("/workspace/data/multilingual-text-classifier/model.ckpt")
```
## config.yaml
```
model: model.yaml
```

## model.yaml
```
_target_: src.models.model.BERTModel

TRAIN_BATCH_SIZE: 32
VALID_BATCH_SIZE: 64
EPOCHS: 2
LEARNING_RATE: 0.5 * 1e-5
```

## Error
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/hydra/main.py", line 53, in decorated_main
    config_name=config_name,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
    lambda: hydra.run(
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 371, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/opt/conda/lib/python3.6/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/opt/conda/lib/python3.6/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "run.py", line 38, in main
    return train(config)
  File "/workspace/data/multilingual-text-classifier/src/train.py", line 41, in train
    model: LightningModule =  hydra.utils.instantiate(config.model)
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 183, in instantiate
    "Top level config has to be OmegaConf DictConfig, plain dict, or a Structured Config class or instance"
hydra.errors.InstantiationException: Top level config has to be OmegaConf DictConfig, plain dict, or a Structured Config class or instance
```

## System information
- **Hydra Version** :  1.1.0
- **Python version** : 3.6.10
- **Virtual environment type and version** : conda 4.8.4
- **Operating system** : Windows

**Comment by omry** [comment]
Please reach out to the template author for help.
It is possible that the template was tested against Hydra 1.0 and is not working with 1.1.

**Comment by ishandutta0098** [comment]
Hi @omry, the code in the template was tested with hydra 1.1

**Comment by omry** [comment]
What is the type of the object you are passing to instantiate?

**Comment by omry** [comment]
Looking at your config, I don't think it does what you think it does.
Please go over the basic tutorial. Using templates is not a replacement to understanding the basics of how Hydra works.

My guess is that your config is the dictionary contains the key `model` with the value `model.yaml`.
Instantiate does not operate on strings and telepathically understand your intention.
You need the config you are passing to instantiate to contain the proper content.
