### ISSUE TITLE
[Bug] Run out of the box Multi-Objective Optimization.

### ISSUE THREAD

**Issue by dalnoguer** [facebookresearch/hydra#1718]
Hi,

It seems there is a bug in the NSGAIISampler __init__ function.

Following the run instructions: 

```
To run the optimization, use the following command in the plugins/hydra_optuna_sweeper directory:

python example/multi-objective.py --multirun
```

Leads to the following error:

multiobj ❯ python example/multi-objective.py --multirun
Traceback (most recent call last):
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'constraints_func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/utils.py", line 379, in <lambda>
    overrides=args.overrides,
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 135, in multirun
    task_function=task_function,
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/core/plugins.py", line 174, in instantiate_sweeper
    sweeper = self._instantiate(config.hydra.sweeper)
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/core/plugins.py", line 93, in _instantiate
    plugin = instantiate(config=config, _target_=clazz)
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 246, in instantiate_node
    value, convert=convert, recursive=recursive
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(target, *args, **kwargs)
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 66, in _call_target
    ).with_traceback(sys.exc_info()[2])
  File "/home/dnoguer/miniconda3/envs/multiobj/lib/python3.6/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
TypeError: Error instantiating 'optuna.samplers._nsga2.NSGAIISampler' : __init__() got an unexpected keyword argument 'constraints_func'

Thanks!

**Comment by omry** [comment]
Thanks for reporting.
Looks like the Optuna version in the plugin is restricted to < 2.5 which does not support this.
can you try with the latest version of Optuna?

**Comment by dalnoguer** [comment]
It worked fine, even though pip complained that hydra core requires optuna < 2.4.

Thanks!!

**Comment by omry** [comment]
We will need to fix the dependency, and also ensure that the multi objective optimization is covered by tests. (I suspect it's not).

**Comment by jieru-hu** [comment]
this has been fixed.
