### ISSUE TITLE
[Bug] AttributeError: 'functools.partial' object has no attribute 'hydra'

### ISSUE THREAD

**Issue by IgorKasianenko** [facebookresearch/hydra#1723]
# 🐛 Bug
## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://github.com/IgorKasianenko/hydra-bug-AttributeError.git) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
`git clone https://github.com/IgorKasianenko/hydra-bug-AttributeError.git`
`cd hydra-bug-AttributeError/hydra`
`python test_hydra.py experiment=my`

** Stack trace/error message **
```
HYDRA_FULL_ERROR=1 python test_hydra.py experiment=my
Traceback (most recent call last):
  File "test_hydra.py", line 11, in <module>
    app()
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 97, in run
    ret = run_job(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/hydra/core/utils.py", line 122, in run_job
    working_dir = str(OmegaConf.select(config, job_dir_key))
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 685, in select
    format_and_raise(node=cfg, key=key, value=None, cause=e, msg=str(e))
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 677, in select
    return select_value(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/_impl.py", line 58, in select_value
    node = select_node(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/_impl.py", line 93, in select_node
    _root, _last_key, node = cfg._select_impl(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/base.py", line 429, in _select_impl
    value = root._maybe_resolve_interpolation(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/base.py", line 616, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/base.py", line 482, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/base.py", line 662, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 205, in accept
    return visitor.visitConfigValue(self)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 339, in accept
    return visitor.visitText(self)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 911, in accept
    return visitor.visitInterpolationNode(self)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/base.py", line 643, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/home/exx/anaconda3/envs/py38gpu/lib/python3.8/site-packages/omegaconf/base.py", line 573, in _resolve_node_interpolation
    raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'project.name' not found
    full_key: hydra.run.dir
    object_type=dict
```

## Expected Behavior
Print config as in hydra version 1.0.0rc1 before upgrade

## System information
- **Hydra Version** :  1.1.0
- **Python version** : Python 3.8.8
- **Virtual environment type and version** : 4.9.2
- **Operating system** : Ubuntu 20.04.2 LTS

## Additional context
OmegaConf is latest version 2.1

**Comment by omry** [comment]
Is this a regression from Hydra 1.0 to Hydra 1.1? please test on 1.0.7 (the latest 1.0 version) and confirm. 1.0.0rc1 is not a supported version.

**Comment by IgorKasianenko** [comment]
Hi Omry,
Thank you for your reply and question.
Actually I confused and I have 2 different errors. One in conda env that I described with the error log. This is resolved with going to latest stable 1.0 version by `pip install hydra-core==1.0.7`

Second one like you mentioned in the title is coming from another env - nvidia gpu docker with same python and ubuntu version. This question led me to find the bug in the class that I want to instantiate and I will continue debugging it without hydra. Funny thing that in conda there is no bug, but in docker container there is.

**Comment by IgorKasianenko** [comment]
One more update: I had really messed up env, I was getting 
```
>>> import torch
Segmentation fault (core dumped)
```
And this was hidden under instantiate. Simple reboot solved all issues.

**Comment by omry** [comment]
Gotcha.

FYI: The stable and recommended version is Hydra 1.1.0, I only suggested you install 1.0.7 because you seemed to be using 1.0 already.
