### ISSUE TITLE
[Bug] `config_path` search path is relative to file path, not python working directory

### ISSUE THREAD

**Issue by SunQpark** [facebookresearch/hydra#1788]
# 🐛 Bug
## Description
When I launch python script outside of the directory where script lies, it fails to locate config directory.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Project directory looks like
```
hydra-reprod
├── conf
│   └── a.yaml
└── script
    └── reprod.py
```
`reprod.py` contains
```python
import hydra
from pathlib import Path


@hydra.main(config_path='conf/', config_name='a.yaml')
def main(config):
    print('hello')

if __name__ == '__main__':
    cwd = Path.cwd()
    print(cwd)
    print((cwd / 'conf').exists())

    main()
```
and script is launched with `HYDRA_FULL_ERROR=1 python3 -m script.reprod`

** Stack trace/error message **
```
/home/louis/projects/hydra-reprod
True
Traceback (most recent call last):
  File "script/reprod.py", line 14, in <module>
    main()
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 88, in run
    cfg = self.compose_config(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 227, in _load_configuration_impl
    self.ensure_main_config_source_available()
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 129, in ensure_main_config_source_available
    self._missing_config_error(
  File "/home/louis/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 103, in _missing_config_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: Primary config directory not found.
Check that the config directory '/home/louis/projects/hydra-reprod/script/conf' exists and readable
```

## Expected Behavior
I think relative path is used for `config_path` it should be relative to python working directory, not to the location of python script.

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.8.5
- **Virtual environment type and version** : conda 4.10.0
- **Operating system** : ubuntu

**Comment by jieru-hu** [comment]
This is how Hydra is designed to work. 🙂 I don't see us changing this any time soon.

**Comment by Jasha10** [comment]
@SunQpark I believe that Hydra's [Compose API](https://hydra.cc/docs/advanced/compose_api) is appropriate in your use-case:
```python
# script/reprod.py
from pathlib import Path
from hydra import compose, initialize_config_dir

if __name__ == "__main__":
    cwd = Path.cwd()
    print(cwd)
    conf = cwd / "conf"
    conf = conf.resolve()
    print(conf.exists())
    with initialize_config_dir(str(conf)):
        cfg = compose(config_name="a.yaml")

    print(cfg)
```
```text
$ python -m script.reprod
/Users/jasha10/hydra.git/tmp1788
True
{}
```
