### ISSUE TITLE
[Question] How to get configure using a function imported from another file

### ISSUE THREAD

**Issue by slongle** [facebookresearch/hydra#1821]
I want to get configure in `a.py` by using a function named `get_config()` in `b.py`.
For example, I have two python files as belows, and run `python a.py`, but this code is wrong.

a.py: 
```
from b import get_config

if __name__ == "__main__":
    cfg = get_config()
```

b.py:
```
import hydra

@hydra.main(config_name='config')
def get_config(cfg) -> None:
    return cfg
```

The error info is
```
b.py:3: UserWarning:
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main(config_name='config')
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    cfg = get_config()
  File "/home/d/.local/lib/python3.7/site-packages/hydra/main.py", line 52, in decorated_main
    config_name=config_name,
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    lambda: hydra.run(
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 380, in <lambda>
    overrides=args.overrides,
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 92, in run
    run_mode=RunMode.RUN,
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 562, in compose_config
    from_shell=from_shell,
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 145, in load_configuration
    from_shell=from_shell,
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 227, in _load_configuration_impl
    self.ensure_main_config_source_available()
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 130, in ensure_main_config_source_available
    config_name=None, msg=msg, with_search_path=False
  File "/home/d/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 104, in _missing_config_error
    missing_cfg_file=config_name, message=add_search_path()
hydra.errors.MissingConfigException: Primary config module is empty.
Python requires resources to be in a module with an __init__.py file
```

**Comment by omry** [comment]
Using `@hydra.main()` like this is an anti-pattern and will not work.
Use the Compose API if you want to compose a config.

**Comment by slongle** [comment]
Thanks! But if I use Compose API, I can't override parameters in the command line, right?

**Comment by Jasha10** [comment]
Yes, the compose API does not parse command line args.
```
def compose(
    config_name: Optional[str] = None,
    overrides: List[str] = [],
    return_hydra_config: bool = False,
    strict: Optional[bool] = None,
) -> DictConfig:
```
You can pass overrides via the `overrides` argument in the compose function signature.
```
cfg = compose(config_name="config", overrides=["foo=bar", "+baz=123"])
```
If you want, you could do `import sys` and pass the trailing elements of `sys.argv` as overrides.

**Comment by slongle** [comment]
Great! Thanks a lot for your help!

**Comment by omry** [comment]
> Thanks! But if I use Compose API, I can't override parameters in the command line, right?

Correct, not in the same way.
What you should probably do is something like:
``python
def train(cfg):
  ...

@hydra.main(...)
def main(cfg): 
  train(cfg)
```

Other entry points (like tests, where you don't have the command line) can use the compose API and call `train` with the composed config object.

**Comment by alexisthual** [comment]
Thanks for the nice library!
I would be very interested in being able to access the result of `@hydra.main` in a more simple way than having to pass it as an argument to every function that needs it (which becomes very cumbersome when such functions are nested).

I initially switched to the compose API to achieve this, and now realize I need to switch back to `@hydra.main` because I need to include command line arguments to use "--multirun".
The other reason I was using the compose API is because I use other decorators like `@memory.cache` from `joblib` and that I wanted them to access information from my config (in particular, a path to the tmp folder).
