### ISSUE TITLE
Remove generic `except Exception` from `_internal/utils.py::_locate`

### ISSUE THREAD

**Issue by robogast** [facebookresearch/hydra#1823]
In the internal `utils`' `_locate` function, a generic `Exception` is caught and an ImportError is raised: 
https://github.com/facebookresearch/hydra/blob/b16baa73df33e5a2e7ac811983f9ef60e6f130d8/hydra/_internal/utils.py#L567-L576

This swallowing of the stacktrace has already cost me quite some time in debugging; `Error loading module` is not a very helpful message when the true error might be something trivial like a forgotten bracket, especially if that exception happens during a non-local run, e.g. when using `submitit`.

If you want to make the error 'pretty', at least make the true exception available with `HYDRA_FULL_ERROR=1`, which is now not the case.
(although making errors 'pretty' is not my preference; this is not customer facing software, and exceptions are verbose in general for a reason...)

**Comment by Jasha10** [comment]
Hi @robogast,

Thanks for the suggestion!
Note that this try/except block makes use of [exception chaining](https://docs.python.org/3/tutorial/errors.html#exception-chaining): `raise ... from ...`.
This means that, in theory, the original exception should appear as part of the stack trace.
```python
$ cat tmp.py
try:
    raise RuntimeError("foo")
except Exception:
    raise ImportError("bar")
```
```text
$ python3 tmp.py
Traceback (most recent call last):
  File "/Users/jasha10/hydra.git/tmp1823/tmp.py", line 2, in <module>
    raise RuntimeError("foo")
RuntimeError: foo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jasha10/hydra.git/tmp1823/tmp.py", line 4, in <module>
    raise ImportError("bar") from e
ImportError: bar
```
(both `RuntimeError: foo` and `ImportError: bar` appear in the stacktrace above)

Are you encountering this issue when you call `hydra.utils.instantiate`? When I call `instantiate`, I'm seeing a stacktrace similar to the one above.

**Comment by Jasha10** [comment]
> Especially when debugging non-local runs, such as when using submitit, debugging without a clear stacktrace is difficult.

I did not see this part of your comment earlier.
When you're using submitit, do you not see the stacktrace that results from the exception chaining?

**Comment by omry** [comment]
There is an existing bug report about submitit exceptions handling.

**Comment by robogast** [comment]
Before removing the try/except (stacktrace is not preserved, and only shows 'Error loading module'):
```python
$ python train.py <certain-overrides> --multirun
[2021-09-16 15:31:13,993][HYDRA] Submitit 'slurm' sweep output dir : multirun/2021-09-16/15-31-11
[2021-09-16 15:31:13,995][HYDRA] 	#0 : <name>
Error executing job with overrides: [<certain-overrides>]
Traceback (most recent call last):
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 386, in <lambda>
    lambda: hydra.multirun(
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 140, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 161, in sweep
    _ = r.return_value
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
ImportError: Error loading module 'vq_ae.model.VQAE'
```
After removing the try/except (stacktrace is not preserved, but does point to what I actually did wrong):
```python
$ python train.py <certain-overrides> --multirun --multirun
[2021-09-16 15:10:04,679][HYDRA] Submitit 'slurm' sweep output dir : multirun/2021-09-16/15-10-02
[2021-09-16 15:10:04,681][HYDRA] 	#0 : <name>
Error executing job with overrides: [<certain-overrides>]
Traceback (most recent call last):
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 386, in <lambda>
    lambda: hydra.multirun(
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 140, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 161, in sweep
    _ = r.return_value
  File "/home/robertsc/.conda/envs/2D-VQ-AE-2/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
ValueError: resolver 'path.stem' is already registered
```
Does seem related to #1698, following omry's comment

**Comment by Jasha10** [comment]
I see. Thank you @robogast for the additional information.

> Does seem related to #1698, following omry's comment
Yes indeed.

My sense is that the `raise ImportError(f"Error loading module '{path}'") from e` error message is intended to provide context about the `{path}` variable, which is also useful for debugging.
