### ISSUE TITLE
[Bug] RecursionError when input config loads itself via defaults list

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1828]
# 🐛 Bug
I've been able to trigger a RecursionError by using the defaults list in `conf.yaml` to load `conf`.
```yaml
# conf.yaml
defaults:
  - conf
```
```python
# repro.py
import hydra

@hydra.main(config_path=".", config_name="conf")
def main(cfg):
    pass

main()
```
```text
$ python repro.py
Traceback (most recent call last):
  File "/home/jasha10/hydra.git/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/jasha10/hydra.git/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/jasha10/hydra.git/hydra/_internal/hydra.py", line 88, in run
    cfg = self.compose_config(
  File "/home/jasha10/hydra.git/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 239, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 751, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 721, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 458, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 578, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 521, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 578, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 521, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/defaults_list.py", line 578, in _create_defaults_tree_impl
    add_child(children, new_root)
...
RecursionError: maximum recursion depth exceeded in comparison
```

## Expected Behavior:
An error message about not including `conf` in the defaults list of `conf`.

## System information
- **Hydra Version** :  1.2.0dev1
- **Python version** : 3.9.6

**Comment by omry** [comment]
Well, a config should not load itself.
I actually thing that a recursion error is a reasonable error here.

**Comment by Jasha10** [comment]
> Well, a config should not load itself.

Agreed.

I was surprised by this because I did it by accident -- I was trying to load a structured config as schema, but the schema had the same name as the yaml file.

> I actually thing that a recursion error is a reasonable error here.

Fair enough.

**Comment by omry** [comment]
In principle we could apply the same logic we used to detect interpolation cycles here, but I dunno if it's worth it.
