### ISSUE TITLE
Dict[non-string, ...] crashes when looking for key `__HYDRA_REMOVE_TOP_LEVEL_DEFAULTS__`

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1834]
# 🐛 Bug
## Description
There is a bug in the logic to remove top-level defaults lists from structured configs.
Specifically, if a `DictConfig` instance has `key_type` that is typed as something like `int` or as a subclass of `Enum`, then the defaults list logic raises a `ConfigCompositionException` when `getattr(cfg, "__HYDRA_REMOVE_TOP_LEVEL_DEFAULTS__")` is called.

## To reproduce

** Minimal Code/Config snippet to reproduce **
Here is `app.py`:
```python
from enum import Enum
from dataclasses import dataclass, field
from typing import Dict
import hydra
from hydra.core.config_store import ConfigStore

cs = ConfigStore.instance()

class Category(Enum):
    X = 0
    Y = 1
    Z = 2

@dataclass
class Conf:
    enum_dict: Dict[Category, str] = field(default_factory=dict)
    int_dict: Dict[int, str] = field(default_factory=dict)
    str_dict: Dict[str, str] = field(default_factory=dict)

cs.store(name="conf", node=Conf)

@hydra.main(config_path=None, config_name="conf")
def app(cfg):
    assert cfg == {"enum_dict": {}, "int_dict": {}, "str_dict": {}}

if __name__ == "__main__":
    app()
```
Here is the output from running `app.py`:
```text
$ HYDRA_FULL_ERROR=1 python app.py
Traceback (most recent call last):
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 140, in load_configuration
    return self._load_configuration_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 248, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 537, in _compose_config_from_defaults_list
    strip_defaults(cfg)
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 535, in strip_defaults
    strip_defaults(value)
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 530, in strip_defaults
    if getattr(cfg, "__HYDRA_REMOVE_TOP_LEVEL_DEFAULTS__", False):
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 457, in _get_node
    key = self._validate_and_normalize_key(key)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 275, in _validate_and_normalize_key
    return self._s_validate_and_normalize_key(self._metadata.key_type, key)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 300, in _s_validate_and_normalize_key
    raise KeyValidationError(
omegaconf.errors.KeyValidationError: Key '__HYDRA_REMOVE_TOP_LEVEL_DEFAULTS__' is incompatible with the enum type 'Category', valid: [X, Y, Z]
    full_key: enum_dict.__HYDRA_REMOVE_TOP_LEVEL_DEFAULTS__
    reference_type=Dict[Category, str]
    object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jasha10/hydra_tmp/D30996424/app.py", line 27, in <module>
    app()
  File "/home/jasha10/hydra.git/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/jasha10/hydra.git/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/jasha10/hydra.git/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/jasha10/hydra.git/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/jasha10/hydra.git/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/jasha10/hydra.git/hydra/_internal/hydra.py", line 88, in run
    cfg = self.compose_config(
  File "/home/jasha10/hydra.git/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 147, in load_configuration
    raise ConfigCompositionException().with_traceback(sys.exc_info()[2]) from e
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 140, in load_configuration
    return self._load_configuration_impl(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 248, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 537, in _compose_config_from_defaults_list
    strip_defaults(cfg)
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 535, in strip_defaults
    strip_defaults(value)
  File "/home/jasha10/hydra.git/hydra/_internal/config_loader_impl.py", line 530, in strip_defaults
    if getattr(cfg, "__HYDRA_REMOVE_TOP_LEVEL_DEFAULTS__", False):
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 457, in _get_node
    key = self._validate_and_normalize_key(key)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 275, in _validate_and_normalize_key
    return self._s_validate_and_normalize_key(self._metadata.key_type, key)
  File "/home/jasha10/miniconda3/envs/hydra/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 300, in _s_validate_and_normalize_key
    raise KeyValidationError(
hydra.errors.ConfigCompositionException
```

## Expected Behavior
The above repro should not crash, and the assertion in they python code should pass.

## System information
- **Hydra Version** :  `main` branch
- **Python version** : 3.9

**Comment by Jasha10** [comment]
I'm filing the issue against Hydra initially, but the solution may involve a change on the OmegaConf side.
