### ISSUE TITLE
Parallel Job Submission with sbatch instead of sequential submission with srun

### ISSUE THREAD

**Issue by amansouri3476** [facebookresearch/hydra#1892]
Hi, thanks for your great project!

I have a few questions for which I couldn't find an answer in the docs.

1. I want to use hydra multirun and submitit plugin to run many jobs on a cluster managed by SLURM. However I notice that a command like `python3 run.py seed=1,2 --multirun` will submit the jobs sequentially, i.e. it uses `srun` to submit a job with seed=1, then __after__ it's finished it again uses `srun` with the second seed. I think the desired behavior is that all these jobs are submitted in parallel with sbatch. If hydra supports that, could you please let me know how it's done?
2. From the [docs](https://github.com/facebookresearch/hydra/blob/1.1_branch/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py) I think that I should pass all the commands that I want to be submitted before the actual job submission under the `setup` key. However, I have some commands that need to be executed before the python application, like activating the conda environment, wandb login and providing its API key. How can I do that, where should I pass those command?

Here's how my submitit_slurm.yaml:

```
# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 1440 # 24 hrs
cpus_per_task: 4
gpus_per_node: null
gres: gpu:1
tasks_per_node: 1
mem_gb: 6
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: long
# comment: null
# constraint: null
# exclude: null
# cpus_per_gpu: null
# gpus_per_task: null
# mem_per_gpu: null
# mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
# additional_parameters: {}
array_parallelism: 256
setup: # A list of commands to run in sbatch befure running srun
    - module load miniconda/3
    - conda activate bb
    - export WANDB_API_KEY=MY_KEY
    - wandb login
```

**Comment by jieru-hu** [comment]
hi 
> I want to use hydra multirun and submitit plugin to run many jobs on a cluster managed by SLURM. However I notice that a command like python3 run.py seed=1,2 --multirun will submit the jobs sequentially, i.e. it uses srun to submit a job with seed=1, then after it's finished it again uses srun with the second seed. I think the desired behavior is that all these jobs are submitted in parallel with sbatch. If hydra supports that, could you please let me know how it's done?


I don't think the launcher submits the job sequentially -  it submits through submitit's support for slurm job arrays. see launcher code [here](https://github.com/facebookresearch/hydra/blob/1.1_branch/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py#L145) and submitit doc [here](https://github.com/facebookincubator/submitit/blob/6f9e1f67178b08b050576fe6bc02e4555568128a/docs/examples.md#job-arrays)
The launcher does wait for all the jobs to finish before it returns, that's a behavior that's consistent across all Hydra launchers. 


>From the docs I think that I should pass all the commands that I want to be submitted before the actual job submission under the setup key. However, I have some commands that need to be executed before the python application, like activating the conda environment, wandb login and providing its API key. How can I do that, where should I pass those command?


Your config looks like it should work. Did you run into any issues?

**Comment by amansouri3476** [comment]
Thanks for your reply.

So if it uses array jobs, I suppose they'll run independently. The fact that the launcher waits for everything to finish confused me. So if a job in the array fails, then the launcher fails (because there's no output from the failing script). However, is it safe to assume if one of the jobs fail, the rest won't be affected on slurm and will continue to run? Or a failure in one of the jobs in the array will cause the whole array jobs to fail as well and stop?

I modified the setup list of commands and made progress, but still get the following error:

```
RuntimeError: Could not figure out which environment the job is runnning in. Known environments: slurm, local, debug.
here’s one such scripts I use:
```

I went down and found one of the submitted scripts:

```
#!/bin/bash

# Parameters
#SBATCH --array=0-4%5
#SBATCH --cpus-per-task=4
#SBATCH --error=/blahblah/.submitit/%A_%a/%A_%a_0_log.err
#SBATCH --gres=gpu:1
#SBATCH --job-name=test
#SBATCH --mem=6GB
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --open-mode=append
#SBATCH --output=/blahblah/%A_%a/%A_%a_0_log.out
#SBATCH --partition=long
#SBATCH --signal=USR1@120
#SBATCH --time=1440
#SBATCH --wckey=submitit

# setup
module unload anaconda
module load miniconda/3
conda activate bb
export WANDB_API_KEY=mykey
wandb login

# command
export SUBMITIT_EXECUTOR=slurm
srun --output /blahblah/%A_%a/%A_%a_%t_log.out --error /%A_%a/%A_%a_%t_log.err --unbuffered /home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/bin/python3 -u -m submitit.core._submit /blahblah/%j

```


And here’s the full traceback

```
[=== Module miniconda/3 loaded ===]
wandb: Currently logged in as: amansouri (use `wandb login --relogin` to force relogin)
Traceback (most recent call last):
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/site-packages/submitit/core/submission.py", line 71, in submitit_main
    process_job(args.folder)
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/site-packages/submitit/core/submission.py", line 36, in process_job
    env = job_environment.JobEnvironment()
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/site-packages/submitit/core/job_environment.py", line 38, in __new__
    return plugins.get_job_environment()
  File "/home/mila/s/sayed.mansouri-tehrani/.conda/envs/bb/lib/python3.7/site-packages/submitit/core/plugins.py", line 82, in get_job_environment
    f"Could not figure out which environment the job is runnning in. Known environments: {', '.join(envs.keys())}."
RuntimeError: Could not figure out which environment the job is runnning in. Known environments: slurm, local, debug.
```

The command I run on the cluster is this:
```python3 test.py seed=1,2,3,4,5 --multirun```

test.py is very simple as I just want to see if everything works successfully on the cluster.

```
import hydra
from omegaconf import DictConfig

# run_name=debug_testing debug=fast_3 +hydra.job.env_set.CUDA_VISIBLE_DEVICES="0"

import submitit
import logging
log = logging.getLogger(__name__)
import os
import time


@hydra.main(config_path="configs", config_name="config")
def main(hydra_config: DictConfig):
    

    env = submitit.JobEnvironment()
    log.info(f"Process ID {os.getpid()} executing task {hydra_config.seed}, with {env}")
    time.sleep(1)
    


if __name__ == "__main__":
    main()
```

Do you know how I can resolve that error?

Many thanks for your help.

**Comment by amansouri3476** [comment]
@jieru-hu Sorry, could you please help me figure out the issue in the above code?
thanks a lot for your help..

**Comment by shagunsodhani** [comment]
Hey @amansouri3476 While I do not have answer for most of the questions you have, I can answer the bit about `Is it safe to assume if one of the jobs fail, the rest won't be affected on slurm and will continue to run? Or a failure in one of the jobs in the array will cause the whole array jobs to fail as well and stop?`. It is safe to assume that one job failing/finishing would not affect the remaining slurm jobs.

**Comment by jieru-hu** [comment]
thanks @shagunsodhani!

hi @amansouri3476. if i understand correctly you are trying to run the example submitit launcher application, right?  I could not repro what you are seeing in our environment. We can try to rule things out first, could you try the following things and let me know if any of them work.

1. comment out all setup commands
2. comment out the wandb login commands.

**Comment by omry** [comment]
Closing this as stale. The discussion here is inconclusive, and it is not clear whether there is still a current Hydra issue to address.

If this is still a real problem on current Hydra, please open a fresh issue with an updated minimal example, the launcher configuration, the exact command being run, and the behavior you expect versus what happens.
