### ISSUE TITLE
[Bug] Overriding the config gives an error

### ISSUE THREAD

**Issue by Anirudh257** [facebookresearch/hydra#1917]
# 🐛 Bug
## Description

Unable to follow the steps in the tutorial and override the config value
## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
1. Follow the steps mentioned in the [tutorial](https://hydra.cc/docs/tutorials/basic/your_first_app/config_file/).
2. Create `my_app.py` and `config.yaml`
3. Run `python3 my_app.py ++db.password=123`
** Stack trace/error message **
```
Traceback (most recent call last):
  File "my_app.py", line 9, in <module>
    my_app()
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/main.py", line 33, in decorated_main
    config_name=config_name,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 362, in _run_hydra
    lambda: hydra.run(
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    raise ex
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 210, in run_and_report
    return func()
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    overrides=args.overrides,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 90, in run
    run_mode=RunMode.RUN,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 524, in compose_config
    from_shell=from_shell,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    from_shell=from_shell,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 166, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 100, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: no viable alternative at input '+'
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

```

## Expected Behavior

The output should have been 
````
db:
 driver: mysql
 user: root
 password: 1234
````
and the password in the `config.yaml` should be updated as well.
## System information
- **Hydra Version** :   `1.1.0dev4`
- **Python version** : Python3.7.7 from Anaconda
- **Virtual environment type and version** : Conda environment and `conda 4.10.3`
- **Operating system** : Ubuntu 20.04.2 LTS (Focal Fossa)

**Comment by Jasha10** [comment]
Hi @Anirudh257,
I am not able to reproduce this issue.
Using the following files, here is what I see:

```python
# my_app.py
from omegaconf import OmegaConf
import hydra

@hydra.main(config_path=".", config_name="config")
def my_app(cfg):
    print(OmegaConf.to_yaml(cfg))

my_app()
```
```yaml
# config.yaml
db:
  driver: mysql
  user: omry
  password: secret
```
```text
$ # At the command line:
$ python my_app.py '++db.password=123'
/Users/jasha10/hydra.git/hydra/_internal/hydra.py:98: UserWarning: Hydra 1.3 will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir for more information.
  ret = run_job(
db:
  driver: mysql
  user: omry
  password: 123
```
What shell are you using? Could you please try running the command with quotes around the `++db.password=123` part?
```text
$ python my_app.py '++db.password=123'
```

**Comment by Anirudh257** [comment]
@Jasha10 Thanks for your response. I tried running 

`$ python my_app.py '++db.password=123'` but this also gives the same error:

```
Traceback (most recent call last):
  File "my_app.py", line 9, in <module>
    my_app()
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/main.py", line 33, in decorated_main
    config_name=config_name,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 362, in _run_hydra
    lambda: hydra.run(
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    raise ex
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 210, in run_and_report
    return func()
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    overrides=args.overrides,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 90, in run
    run_mode=RunMode.RUN,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 524, in compose_config
    from_shell=from_shell,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    from_shell=from_shell,
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 166, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home/mbzuaiser/.local/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 100, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: no viable alternative at input '+'
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

```

I am using this shell: `GNOME Shell 3.36.9`

**Comment by Jasha10** [comment]
I see you mentioned that you are using Hydra version `1.1.0dev4`. Could you please try upgrading to a newer version of Hydra?
Something like this should do the trick:
```text
$ pip install --upgrade 'hydra-core>=1.1.1'
```

**Comment by Anirudh257** [comment]
@Jasha10 Thanks, It works without any error!
