### ISSUE TITLE
Need to use `hydra` settings with `click` CLI command groups

### ISSUE THREAD

**Issue by Felix-neko** [facebookresearch/hydra#1964]
Hi folks! And thank you for your great work.

I want to develop a complex CLI in which I want to use different commands (supported by `click`) and different settings (supported by `hydra`). It will be used in this way

`dummy-gen initdb --config-path="..." --config-name="..." --n_rows=1000000000`
`dummy-gen dropdb --config-path="...", --config-name="..."`
`dummy-gen another_command --config-path="...", --config-name="..." --another-parameter`

Just now I'm doing it with a quick and dirty trick: I run `hydra` processing in `click` command function, but before running `hydra` processing I modify `sys.argv` (I remove the words that correspond `click` command from it).

That's how can it be used now:
```
import datetime
import sys
from dataclasses import dataclass
from typing import Tuple, Union, Optional

import click

import hydra
from hydra.core.config_store import ConfigStore


##############################
# HYDRA SETTINGS PROCESSING
##############################

@dataclass
class RawNoiseDataConfig:

    n_rows: int = 5

    n_string_cols: int = 5
    n_float_cols: int = 5
    n_unique_ids: int = 2

    chunk_size: int = 50_000

    min_timestamp: str = "2000-01-01"
    max_timestamp: str = "2020-01-01"
    sort_event_timestamp: bool = True


@hydra.main(config_path="conf", config_name="config")
def my_app(cfg: RawNoiseDataConfig) -> None:
    print(cfg)


###################################
# CLICK COMMAND GROUP DECLARATION
###################################

@click.group()
def cli():
    pass


def remove_from_argv(n_args: int):
    assert n_args >= 1
    assert n_args < len(sys.argv)
    sys.argv = [sys.argv[0]] + sys.argv[n_args + 1:]


@cli.command(context_settings=dict(ignore_unknown_options=True, allow_extra_args=True))
def initdb():
    click.echo('Initialized the database')

    remove_from_argv(1)

    print(sys.argv)
    cs = ConfigStore.instance()
    # Registering the Config class with the name 'config'.
    cs.store(name="config", node=RawNoiseDataConfig)

    my_app()

@cli.command()
def dropdb():
    click.echo('Dropped the database')


if __name__ == "__main__":
    cli()
```

Can you support such feature officially in future releases? We know that `click` and `hydra` have different specialization, and it will be really cool to use them together: `click` for command and command group declaration and `hydra` for settings processing.

**Comment by Felix-neko** [comment]
Looks interesting! Just now i'm a bit overwhelmed by current work but i'll return to this theme and surely try it.

P.S. Maybe it will be also useful to extend Hydra documentation with a such example of using hydra on top of click...

**Comment by maver1ck** [comment]
@Jasha10 
I'm using compose API. The problem is that IMHO working directory is incorrect. It should be a directory where I'm running my command. Instead of this it's a directory of installed module.

Code:
```
@cli.command()
def entries():
    initialize(config_path=".")
    cfg = compose(config_name="config.yaml")
    print(OmegaConf.to_yaml(cfg))
    print(cfg.abc)
    for e in iter_entry_points('printit.plugins'):
        print(e.name)
```
Stacktrace:
```
Traceback (most recent call last):
  File "/home/maverick/.local/bin/printit", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/maverick/.local/lib/python3.8/site-packages/printit/cli.py", line 44, in entries
    cfg = compose(config_name="config.yaml")
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/compose.py", line 33, in compose
    cfg = gh.hydra.compose_config(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 239, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 747, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 717, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 355, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 454, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 461, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/maverick/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 801, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: Cannot find primary config 'config.yaml'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/maverick/.local/lib/python3.8/site-packages/printit
        provider=schema, path=structured://

 maverick@DESKTOP  /mnt/c/Users/maverick/src/getindata/click-plugins/example/PrintIt/printit  pwd                                                                                                                                                                   
/mnt/c/Users/maverick/src/getindata/click-plugins/example/PrintIt/printit

 maverick@DESKTOP  /mnt/c/Users/maverick/src/getindata/click-plugins/example/PrintIt/printit  ls                                                                                                                                                                      
__init__.py  cli.py  config.yaml  core.py
```

**Comment by Jasha10** [comment]
Hi @maver1ck,

`initialize(config_path=...)` uses a path relative to the file that calls `initialize`. The motivation is to allow config files to be distributed together with the code that calls initialize.

Alternatives to `initialize` are `hydra.initialize_config_module` and `hydra.initialize_config_dir`, both of which use absolute paths.

I assume that, for your use-case, the "config.yaml" file is in the same directory where you are running python. In that case, I'd recommend using `hydra.initialize_config_dir` and passing the absolute path to the current working directory.

```python
import os
from hydra import initialize_config_dir

@cli.command()
def entries():
    initialize_config_dir(config_dir=os.getcwd())
    cfg = compose(config_name="config")
    print(OmegaConf.to_yaml(cfg))
```

**Comment by Jasha10** [comment]
@maver1ck feel free to open another issue with questions or suggestions related to working directory.

**Comment by deephbz** [comment]
> ```python
> ...
> 
> @cli.command(context_settings=dict(ignore_unknown_options=True, allow_extra_args=True))
> def initdb():
>     click.echo('Initialized the database')
> 
>     n_args = 1
>     hydra_args = sys.argv[n_args + 1:]
> 
>     print(hydra_args)
>     cs = ConfigStore.instance()
>     # Registering the Config class with the name 'config'.
>     cs.store(name="config", node=RawNoiseDataConfig)
> 
>     from hydra import initialize, compose
>     with initialize(config_path="conf"):
>         cfg = compose(config_name="config", overrides=hydra_args)
>         # use cfg here...
> 
> ...
> ```

To get the `hydra_args` in a cleaner way:

```python

@cli.command(context_settings=dict(ignore_unknown_options=True, allow_extra_args=True))
@click.pass_context
def custom_cmd_name(ctx):
    hydra_args = ctx.args  # left-over args

    from hydra import initialize, compose
    with initialize(config_path="conf"):
        cfg = compose(config_name="config", overrides=hydra_args)
        # use cfg here...
```

And to mimic the `--config-path` option provided by `hydra.main()`:

```python

@cli.command(context_settings=dict(ignore_unknown_options=True, allow_extra_args=True))
@click.option('--config-path', required=True, type=click.Path(exists=True, resolve_path=True))
@click.pass_context
def custom_cmd_name(ctx, config_path: str):
    hydra_args = ctx.args  # left-over args

    from hydra import initialize, compose
    with initialize_config_dir(config_path="conf"):
        cfg = compose(config_dir=config_path, overrides=hydra_args)
        # use cfg here...
```
