### ISSUE TITLE
[Bug] build error

### ISSUE THREAD

**Issue by fizwit** [facebookresearch/hydra#2024]
# 🐛 Bug
## Description
build error hydra-core-1.1.1 from Pypi
      File "setup.py", line 8, in <module>
        from build_helpers.build_helpers import (
    ModuleNotFoundError: No module named 'build_helpers'

## Checklist
- [ x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
pip install hydra-core

** Stack trace/error message **
```
Processing /app/sources/p/PyTorch-Geometric/extensions/hydra-core-1.1.1.tar.gz
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /app/software/Python/3.8.6-GCCcore-10.2.0/bin/python /app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpy0w202tk
         cwd: /tmp/pip-req-build-qlhgdced
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/build_meta.py", line 248, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/app/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 8, in <module>
        from build_helpers.build_helpers import (
    ModuleNotFoundError: No module named 'build_helpers'
```

## Expected Behavior
pip install should work from Pypi

## System information
- **Hydra Version** :  1.1.1
- **Python version** :  3.8.6
- **Virtual environment type and version** :
- **Operating system** :  Ubuntu 18.04

## Additional context
builds if I manually download the tar file from github. Github and Pypi do not match.

**Comment by pixelb** [comment]
Indeed the build_helpers/ dir is not in the pip tarball.
Though it's not needed at least with pip 19.3.1 on Fedora 32.

The trace above suggests the legacy (non pep 517) backend is in play, which might trigger the compilation of setup.py during pip install.

Could you try to update pip (in your venv), before installing hydra:

```
python3 -m venv hydra-env
source hydra-env/bin/activate
cd hydra-env/
pip install --upgrade pip setuptools wheel   # Didn't need this on Fedora 32 but also works with it 
pip install hydra-core --upgrade
```

**Comment by Jasha10** [comment]
I'm getting a similar `ModuleNotFoundError: No module named 'build_helpers'` when I try to follow the steps from https://hydra.cc/docs/development/release/ to build a wheel.

#### To reproduce with a fresh git clone:
```shell
git clone https://github.com/facebookresearch/hydra hydra_2
cd hydra_2
python3 -m venv hydra-env
source hydra-env/bin/activate
pip install --upgrade pip setuptools wheel build
python -m build
```
<details>
<summary> Output from `python -m build`: </summary>

```text
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for sdist...
running egg_info
creating hydra_core.egg-info
writing hydra_core.egg-info/PKG-INFO
writing dependency_links to hydra_core.egg-info/dependency_links.txt
writing entry points to hydra_core.egg-info/entry_points.txt
writing requirements to hydra_core.egg-info/requires.txt
writing top-level names to hydra_core.egg-info/top_level.txt
writing manifest file 'hydra_core.egg-info/SOURCES.txt'
reading manifest file 'hydra_core.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'hydra_core.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running clean
Generating parsers with antlr4
running antlr
Generating parser for Python3: ['java', '-jar', '/home/rig1/dev/hydra_2/build_helpers/bin/antlr-4.9.3-complete.jar', '-Dlanguage=Python3', '-o', '/home/rig1/dev/hydra_2/hydra/grammar/gen/', '-Xexact-output-dir', '-visitor', '/home/rig1/dev/hydra_2/hydra/grammar/OverrideLexer.g4']
Generating parser for Python3: ['java', '-jar', '/home/rig1/dev/hydra_2/build_helpers/bin/antlr-4.9.3-complete.jar', '-Dlanguage=Python3', '-o', '/home/rig1/dev/hydra_2/hydra/grammar/gen/', '-Xexact-output-dir', '-visitor', '/home/rig1/dev/hydra_2/hydra/grammar/OverrideParser.g4']
running egg_info
writing hydra_core.egg-info/PKG-INFO
writing dependency_links to hydra_core.egg-info/dependency_links.txt
writing entry points to hydra_core.egg-info/entry_points.txt
writing requirements to hydra_core.egg-info/requires.txt
writing top-level names to hydra_core.egg-info/top_level.txt
reading manifest file 'hydra_core.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'hydra_core.egg-info/SOURCES.txt'
running check
creating hydra-core-1.3.0.dev0
creating hydra-core-1.3.0.dev0/hydra
creating hydra-core-1.3.0.dev0/hydra/_internal
creating hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
creating hydra-core-1.3.0.dev0/hydra/_internal/grammar
creating hydra-core-1.3.0.dev0/hydra/_internal/instantiate
creating hydra-core-1.3.0.dev0/hydra/conf
creating hydra-core-1.3.0.dev0/hydra/conf/hydra
creating hydra-core-1.3.0.dev0/hydra/conf/hydra/env
creating hydra-core-1.3.0.dev0/hydra/conf/hydra/help
creating hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_help
creating hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_logging
creating hydra-core-1.3.0.dev0/hydra/conf/hydra/job_logging
creating hydra-core-1.3.0.dev0/hydra/conf/hydra/output
creating hydra-core-1.3.0.dev0/hydra/core
creating hydra-core-1.3.0.dev0/hydra/core/override_parser
creating hydra-core-1.3.0.dev0/hydra/experimental
creating hydra-core-1.3.0.dev0/hydra/extra
creating hydra-core-1.3.0.dev0/hydra/grammar
creating hydra-core-1.3.0.dev0/hydra/grammar/gen
creating hydra-core-1.3.0.dev0/hydra/plugins
creating hydra-core-1.3.0.dev0/hydra/test_utils
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/group
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/hydra
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/hydra/launcher
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/test_hydra
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/test_hydra/launcher
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/db
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/group1
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/group2
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/missing_init_py
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests/group1
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests/group2
creating hydra-core-1.3.0.dev0/hydra/test_utils/configs/top_level_list
creating hydra-core-1.3.0.dev0/hydra_core.egg-info
copying files to hydra-core-1.3.0.dev0...
copying LICENSE -> hydra-core-1.3.0.dev0
copying MANIFEST.in -> hydra-core-1.3.0.dev0
copying README.md -> hydra-core-1.3.0.dev0
copying pyproject.toml -> hydra-core-1.3.0.dev0
copying setup.py -> hydra-core-1.3.0.dev0
copying hydra/__init__.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/compose.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/errors.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/initialize.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/main.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/py.typed -> hydra-core-1.3.0.dev0/hydra
copying hydra/types.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/utils.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/version.py -> hydra-core-1.3.0.dev0/hydra
copying hydra/_internal/__init__.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/callbacks.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/config_loader_impl.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/config_repository.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/config_search_path_impl.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/defaults_list.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/deprecation_warning.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/hydra.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/sources_registry.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/utils.py -> hydra-core-1.3.0.dev0/hydra/_internal
copying hydra/_internal/core_plugins/__init__.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/bash_completion.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/basic_launcher.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/basic_sweeper.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/file_config_source.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/fish_completion.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/importlib_resources_config_source.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/structured_config_source.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/core_plugins/zsh_completion.py -> hydra-core-1.3.0.dev0/hydra/_internal/core_plugins
copying hydra/_internal/grammar/__init__.py -> hydra-core-1.3.0.dev0/hydra/_internal/grammar
copying hydra/_internal/grammar/functions.py -> hydra-core-1.3.0.dev0/hydra/_internal/grammar
copying hydra/_internal/grammar/grammar_functions.py -> hydra-core-1.3.0.dev0/hydra/_internal/grammar
copying hydra/_internal/grammar/utils.py -> hydra-core-1.3.0.dev0/hydra/_internal/grammar
copying hydra/_internal/instantiate/__init__.py -> hydra-core-1.3.0.dev0/hydra/_internal/instantiate
copying hydra/_internal/instantiate/_instantiate2.py -> hydra-core-1.3.0.dev0/hydra/_internal/instantiate
copying hydra/conf/__init__.py -> hydra-core-1.3.0.dev0/hydra/conf
copying hydra/conf/hydra/env/default.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/env
copying hydra/conf/hydra/help/default.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/help
copying hydra/conf/hydra/hydra_help/default.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_help
copying hydra/conf/hydra/hydra_logging/default.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_logging
copying hydra/conf/hydra/hydra_logging/disabled.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_logging
copying hydra/conf/hydra/hydra_logging/hydra_debug.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_logging
copying hydra/conf/hydra/hydra_logging/none.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/hydra_logging
copying hydra/conf/hydra/job_logging/default.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/job_logging
copying hydra/conf/hydra/job_logging/disabled.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/job_logging
copying hydra/conf/hydra/job_logging/none.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/job_logging
copying hydra/conf/hydra/job_logging/stdout.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/job_logging
copying hydra/conf/hydra/output/default.yaml -> hydra-core-1.3.0.dev0/hydra/conf/hydra/output
copying hydra/core/__init__.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/config_loader.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/config_search_path.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/config_store.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/default_element.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/global_hydra.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/hydra_config.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/object_type.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/plugins.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/singleton.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/utils.py -> hydra-core-1.3.0.dev0/hydra/core
copying hydra/core/override_parser/__init__.py -> hydra-core-1.3.0.dev0/hydra/core/override_parser
copying hydra/core/override_parser/overrides_parser.py -> hydra-core-1.3.0.dev0/hydra/core/override_parser
copying hydra/core/override_parser/overrides_visitor.py -> hydra-core-1.3.0.dev0/hydra/core/override_parser
copying hydra/core/override_parser/types.py -> hydra-core-1.3.0.dev0/hydra/core/override_parser
copying hydra/experimental/__init__.py -> hydra-core-1.3.0.dev0/hydra/experimental
copying hydra/experimental/callback.py -> hydra-core-1.3.0.dev0/hydra/experimental
copying hydra/experimental/callbacks.py -> hydra-core-1.3.0.dev0/hydra/experimental
copying hydra/experimental/compose.py -> hydra-core-1.3.0.dev0/hydra/experimental
copying hydra/experimental/initialize.py -> hydra-core-1.3.0.dev0/hydra/experimental
copying hydra/extra/pytest_plugin.py -> hydra-core-1.3.0.dev0/hydra/extra
copying hydra/grammar/.gitignore -> hydra-core-1.3.0.dev0/hydra/grammar
copying hydra/grammar/OverrideLexer.g4 -> hydra-core-1.3.0.dev0/hydra/grammar
copying hydra/grammar/OverrideParser.g4 -> hydra-core-1.3.0.dev0/hydra/grammar
copying hydra/grammar/__init__.py -> hydra-core-1.3.0.dev0/hydra/grammar
copying hydra/grammar/gen/.gitignore -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideLexer.interp -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideLexer.py -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideLexer.tokens -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideParser.interp -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideParser.py -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideParser.tokens -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideParserListener.py -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/grammar/gen/OverrideParserVisitor.py -> hydra-core-1.3.0.dev0/hydra/grammar/gen
copying hydra/plugins/__init__.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/plugins/completion_plugin.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/plugins/config_source.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/plugins/launcher.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/plugins/plugin.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/plugins/search_path_plugin.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/plugins/sweeper.py -> hydra-core-1.3.0.dev0/hydra/plugins
copying hydra/test_utils/__init__.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/a_module.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/completion.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/config_source_common_tests.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/example_app.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/launcher_common_tests.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/test_utils.py -> hydra-core-1.3.0.dev0/hydra/test_utils
copying hydra/test_utils/configs/__init__.py -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/accessing_hydra_config.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/compose.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/conf.zip -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/config.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/config.yml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/custom_resolver.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/db_conf.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/defaults_not_list.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/missing-default.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/missing-optional-default.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/optional-default.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/overriding_output_dir.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/overriding_run_dir.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/schema_key_error.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/schema_validation_error.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/some_config.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/unspecified_mandatory_default.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs
copying hydra/test_utils/configs/completion_test/config.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test
copying hydra/test_utils/configs/completion_test/missing_default.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test
copying hydra/test_utils/configs/completion_test/group/dict.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/group
copying hydra/test_utils/configs/completion_test/group/list.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/group
copying hydra/test_utils/configs/completion_test/hydra/launcher/fairtask.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/hydra/launcher
copying hydra/test_utils/configs/completion_test/test_hydra/launcher/fairtask.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/completion_test/test_hydra/launcher
copying hydra/test_utils/configs/db/mysql.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/db
copying hydra/test_utils/configs/db/postgresql.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/db
copying hydra/test_utils/configs/db/validated_mysql.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/db
copying hydra/test_utils/configs/db/validated_postgresql.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/db
copying hydra/test_utils/configs/group1/abc.cde.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/group1
copying hydra/test_utils/configs/group1/file1.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/group1
copying hydra/test_utils/configs/group1/file2.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/group1
copying hydra/test_utils/configs/group2/file1.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/group2
copying hydra/test_utils/configs/group2/file2.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/group2
copying hydra/test_utils/configs/missing_init_py/.gitignore -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/missing_init_py
copying hydra/test_utils/configs/missing_init_py/test.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/missing_init_py
copying hydra/test_utils/configs/package_tests/__init__.py -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests
copying hydra/test_utils/configs/package_tests/pkg_override.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests
copying hydra/test_utils/configs/package_tests/two_packages_one_group.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests
copying hydra/test_utils/configs/package_tests/group1/option1.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests/group1
copying hydra/test_utils/configs/package_tests/group1/option2.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests/group1
copying hydra/test_utils/configs/package_tests/group2/option1.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests/group2
copying hydra/test_utils/configs/package_tests/group2/option2.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/package_tests/group2
copying hydra/test_utils/configs/top_level_list/file1.yaml -> hydra-core-1.3.0.dev0/hydra/test_utils/configs/top_level_list
copying hydra_core.egg-info/PKG-INFO -> hydra-core-1.3.0.dev0/hydra_core.egg-info
copying hydra_core.egg-info/SOURCES.txt -> hydra-core-1.3.0.dev0/hydra_core.egg-info
copying hydra_core.egg-info/dependency_links.txt -> hydra-core-1.3.0.dev0/hydra_core.egg-info
copying hydra_core.egg-info/entry_points.txt -> hydra-core-1.3.0.dev0/hydra_core.egg-info
copying hydra_core.egg-info/requires.txt -> hydra-core-1.3.0.dev0/hydra_core.egg-info
copying hydra_core.egg-info/top_level.txt -> hydra-core-1.3.0.dev0/hydra_core.egg-info
Writing hydra-core-1.3.0.dev0/setup.cfg
Creating tar archive
removing 'hydra-core-1.3.0.dev0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/home/rig1/dev/hydra_2/hydra-env/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/home/rig1/dev/hydra_2/hydra-env/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/rig1/dev/hydra_2/hydra-env/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-0iwe6wqm/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-0iwe6wqm/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-0iwe6wqm/lib/python3.10/site-packages/setuptools/build_meta.py", line 482, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/build-env-0iwe6wqm/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'build_helpers'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

</details>

I think we can fix this by adding `build_helpers` to our `MANIFEST.in` file.
