### ISSUE TITLE
[Bug] Absolute path for overrides group does not work like defaults list

### ISSUE THREAD

**Issue by AdemFr** [facebookresearch/hydra#2105]
# 🐛 Bug
## Description
Not sure if a bug, or intended behaviour:
The override syntax does not allow for absolute path referencing with `/group/config`. This is possible in the defaults list.
I think it would be nice to have the exact same syntax in both.

## Checklist
- [ x ] I checked on the latest version of Hydra
- [ x ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```python
from dataclasses import dataclass, field
from typing import Any, List

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING


@dataclass
class Base:
    arg: str = MISSING


@dataclass
class SubConf(Base):
    arg: str = "arg1"


@dataclass
class SubConf2(Base):
    arg: str = "arg2"


@dataclass
class MetaConf:
    defaults: List[Any] = field(
        default_factory=lambda: [
            {"/sub/sub_group@sub_group": "SubConf2"},
        ]
    )
    sub_group: Base = MISSING


cs = ConfigStore.instance()
cs.store(group="sub_group", name="SubConf", node=SubConf)
cs.store(group="sub/sub_group", name="SubConf2", node=SubConf2)
cs.store(name="MetaConf", node=MetaConf)


@hydra.main(config_path=None, config_name="MetaConf")  # I would like to rely on the searchpath
def main(config):
    print(config)


if __name__ == "__main__":
    main()
    with hydra.initialize(config_path=None):
        # I would expect the same syntax to work here.
        config = hydra.compose("MetaConf", overrides=["/sub/sub_group@sub_group=SubConf2"])
        print(config)

```

** Stack trace/error message **

```
{'sub_group': {'arg': 'arg2'}}
Traceback (most recent call last):
  File "/Users/ademfrenk/merantix/scaffold/src/scaffold/entrypoints/my_main_example_1.py", line 50, in <module>
    config = hydra.compose("MetaConf", overrides=["/sub/sub_group@sub_group=SubConf2"])
  File "/Users/ademfrenk/merantix/scaffold/.venv/lib/python3.8/site-packages/hydra/compose.py", line 33, in compose
    cfg = gh.hydra.compose_config(
  File "/Users/ademfrenk/merantix/scaffold/.venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/Users/ademfrenk/merantix/scaffold/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/Users/ademfrenk/merantix/scaffold/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 231, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/Users/ademfrenk/merantix/scaffold/.venv/lib/python3.8/site-packages/hydra/core/override_parser/overrides_parser.py", line 96, in parse_overrides
    raise OverrideParseException(
hydra.errors.OverrideParseException: Error parsing override '/sub/sub_group@sub_group=SubConf2'
extraneous input '/' expecting {EQUAL, '~', '+', '@', KEY_SPECIAL, DOT_PATH, ID}
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details
```

## Expected Behavior
Would expect the output to look the same as if I would have use `"sub/sub_group@sub_group=SubConf2"` as an override (without leading `/`):
```
{'sub_group': {'arg': 'arg2'}}
{'sub_group': {'arg': 'arg2'}}
```

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.8.3
- **Virtual environment type and version** : 20.13.2
- **Operating system** : macOS

**Comment by namespace-Pt** [comment]
@jieru-hu But how can I override a config group that is absolute path in the default list?
For example, the config file is
```
default:
- /model: model1
```
and I want to use `model2` instead in the command line:
```
with hydra.initialize(config_path=None):
        config = hydra.compose("config", overrides=["/model=model2"])
```
