### ISSUE TITLE
[Bug] [Doc] outdated release process

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#2118]
this page seems to be outdated https://hydra.cc/docs/development/release/ 
the command `python -m build` fails on both `main` and `1.1_branch`

```
Traceback (most recent call last):
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/private/var/folders/3f/sqf9m9lj7ggdfzm4kddrh_240000gn/T/build-env-qmj38jmz/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/private/var/folders/3f/sqf9m9lj7ggdfzm4kddrh_240000gn/T/build-env-qmj38jmz/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/3f/sqf9m9lj7ggdfzm4kddrh_240000gn/T/build-env-qmj38jmz/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/private/var/folders/3f/sqf9m9lj7ggdfzm4kddrh_240000gn/T/build-env-qmj38jmz/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 8, in <module>
    from build_helpers.build_helpers import (
ModuleNotFoundError: No module named 'build_helpers'

```

**Comment by Jasha10** [comment]
I have been using `tools/release/release.py` to publish the dev releases, which has some documentation in `tools/release/README.md`.

**Comment by chenrui333** [comment]
Any update on this thread, I think the pypi artifact issue is still there.

**Comment by Jasha10** [comment]
Hi @chenrui333,
I believe this issue can be closed now, as I'm no longer able to reproduce the issue that Jieru reported above.

> I think the pypi artifact issue is still there

What issue are you referring to?

**Comment by chenrui333** [comment]
> Hi @chenrui333, I believe this issue can be closed now, as I'm no longer able to reproduce the issue that Jieru reported above.
> 
> > I think the pypi artifact issue is still there
> 
> What issue are you referring to?

I am trying in [this PR](https://github.com/Homebrew/homebrew-core/pull/117775), thanks @Jasha10!

**Comment by omry** [comment]
Closing as part of an automated issue cleanup sweep.

This issue appears to be resolved because #2397 merged the missing build files fix, and a maintainer previously indicated this could be closed. If this is still relevant, or if I closed this by mistake, please comment here with updated details and we can reopen it.
