### ISSUE TITLE
[Bug] Cannot find conf/ dir when outside of packaged app.

### ISSUE THREAD

**Issue by louismartin** [facebookresearch/hydra#2125]
# 🐛 Bug
## Description
Hydra cannot find my `conf/` dir located outside of my python package.

File tree:
```
setup.py  # Sets up mypackage
mypackage/app.py  # contains `hydra.main(config_path="../conf", config_name="default")`
conf/default.yaml
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```
setup.py  # Sets up mypackage (but not conf/)
mypackage/app.py  # contains `hydra.main(config_path="../conf", config_name="default")`
conf/default.yaml
```

```
Cannot find primary config 'default'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=pkg://conf
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
I expected hydra to find the `conf/` dir, similar to the ["Getting Started" example](https://hydra.cc/docs/intro/) and as explicitely mentioned [here](https://github.com/facebookresearch/hydra/blob/5272a1566f42a3c2add373d9f0896bb6359f748c/hydra/main.py#L20):
```
    :param config_path: The config path, a directory relative to the declaring python file.
```

## System information
- **Hydra Version** :  1.1
- **Python version** : 3.9
- **Virtual environment type and version**: miniconda
- **Operating system** : Ubuntu

## Additional context

I found after a long time that I could integrate the config files into my package as per [app_packaging](https://hydra.cc/docs/advanced/app_packaging/), but I think it's not super intuitive if you didn't reach this part of the tutorial.

It seems that [`compute_search_path_dir`](https://github.com/facebookresearch/hydra/blob/a257e87b573d16f0cf9d84706d7c922a92c3f389/hydra/_internal/utils.py#L117) receives `calling_file=None` (and `calling_module=mypackage.app`), hence the search path does not construct an absolute path with `abs_base_dir = realpath(dirname(calling_file))`.

I think either the behaviour should be changed so that the absolute path is created even when the `@hydra.main` declaring file is inside a module or at least update the documentation to explicitely mention that packaged python modules behave differently and require the config dir to be packaged as well.

**Comment by louismartin** [comment]
Referencing #559 which was the issue I stumbled onto when trying to debug.

**Comment by jieru-hu** [comment]
thanks @louismartin for reporting. This looks like a potential duplicate of https://github.com/facebookresearch/hydra/issues/1868

**Comment by kiqo** [comment]
Another related issue: When specifying `--config-dir` option (with an absolute path), the configs directory is not found when the search path of the main provider does not exist, for example: 

`configs` dir exists in `.`: 
`python -m mypkg.myapp --config-dir /path/to/some/dir/configs --info searchpath` 

```
DEBUG - 2022-08-04 21:54:03,083 - hydra - 

DEBUG - 2022-08-04 21:54:03,083 - hydra - Config search path
Config search path
DEBUG - 2022-08-04 21:54:03,083 - hydra - ******************
******************
DEBUG - 2022-08-04 21:54:03,241 - hydra - | Provider     | Search path                                                                        |
| Provider     | Search path                                                                        |
DEBUG - 2022-08-04 21:54:03,241 - hydra - -----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
DEBUG - 2022-08-04 21:54:03,241 - hydra - | hydra        | pkg://hydra.conf                                                                   |
| hydra        | pkg://hydra.conf                                                                   |
DEBUG - 2022-08-04 21:54:03,241 - hydra - | main         | pkg://configs                                                                      |
| main         | pkg://configs                                                                      |
DEBUG - 2022-08-04 21:54:03,241 - hydra - | command-line | file:///path/to/some/dir/configs |
| command-line | file:///path/to/some/dir/configs |
DEBUG - 2022-08-04 21:54:03,242 - hydra - | schema       | structured://                                                                      |
| schema       | structured://                                                                      |
DEBUG - 2022-08-04 21:54:03,242 - hydra - -----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
```


whereas if `configs` dir does not exist in `.`:
```
DEBUG - 2022-08-04 22:03:34,326 - hydra - 

DEBUG - 2022-08-04 22:03:34,326 - hydra - Config search path
Config search path
DEBUG - 2022-08-04 22:03:34,326 - hydra - ******************
******************
Traceback (most recent call last):
  File ".../lib/python3.8/runpy.py", line 200, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File ".../lib/python3.8/runpy.py", line 92, in _run_code
    exec(code, run_globals)
...
hydra.errors.MissingConfigException: Primary config module 'configs' not found.
Check that it's correct and contains an __init__.py file`
```
whereas I would have expected that the configs would be found via the `config-dir` option or elsewise that the exception message makes it clearer that the `config-dir` is more or less ignored here?

**Comment by omry** [comment]
Thanks for reporting this, and sorry for the long delay.

This behavior is intentional. Hydra interprets a relative `config_path` from the location of the Python file that declares `@hydra.main`, not from the current working directory. When the application is loaded through an installed entry point, the path is resolved through the application’s Python package, so the configuration files must be packaged and importable. This is described in the [application packaging documentation](https://hydra.cc/docs/advanced/app_packaging/).

For a primary configuration directory outside the installed package, override `config_path` at runtime with an absolute `--config-path`.

The [config search path documentation](https://hydra.cc/docs/advanced/search_path/) describes more flexible ways to locate configuration files, including filesystem and package sources. These are generally useful for configs composed after Hydra locates the primary config, rather than for replacing the primary config directory.

The later `--config-dir` report is slightly different. `--config-dir` adds another directory to the search path, but does not replace an invalid primary config source. Use `--config-path` when replacing the primary config directory.

I am closing this as intended behavior with supported alternatives.
