### ISSUE TITLE
[Bug] Error locating target during instantiation of python built-in functions

### ISSUE THREAD

**Issue by jzazo** [facebookresearch/hydra#2148]
# 🐛 Bug
## Description
Cannot instantiate a config that has python built-in functions, e.g., `len`, `getattr`.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
>>> from omegaconf import OmegaConf
>>> from hydra.utils import instantiate
>>> cfg = OmegaConf.create({"_target_": "len", "obj": "foo"})
>>> cfg
{'_target_': 'len', 'obj': 'foo'}
>>> instantiate(cfg)
```

** Stack trace/error message **
```
>>> instantiate(cfg)
Traceback (most recent call last):
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 574, in _locate
    obj = import_module(part0)
  File "/home/javier/.pyenv/versions/3.8.10/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 576, in _locate
    raise ImportError(
ImportError: Error loading 'len':
ModuleNotFoundError("No module named 'len'")
Are you sure that module 'len' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'len', see chained exception above.
```

## Expected Behavior
It should instantiate python's built-in function which is in scope.

## System information
- **Hydra Version** :  1.1.2
- **Python version** :  3.8.10
- **Virtual environment type and version** :  poetry 1.1.12
- **Operating system** :  Ubuntu 20.04

**Comment by jzazo** [comment]
If I repeat the experiment adding `builtins` module, I get `TypeError('len() takes no keyword arguments')`:
```
>>> from omegaconf import OmegaConf
>>> from hydra.utils import instantiate
>>> cfg = OmegaConf.create({"_target_": "builtins.len", "obj": "foo"})
>>> cfg
{'_target_': 'builtins.len', 'obj': 'foo'}
>>> instantiate(cfg)
Traceback (most recent call last):
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 86, in _call_target
    return _target_(*args, **kwargs)
TypeError: len() takes no keyword arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 331, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/javier/.cache/pypoetry/virtualenvs/immunocam-workflows-iU6iGQo7-py3.8/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 91, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'builtins.len':
TypeError('len() takes no keyword arguments')
```
Do you know why this happens? Thanks.

**Comment by jzazo** [comment]
OK, figured it out. This solves it:
```
>>> cfg = OmegaConf.create({"_target_": "builtins.len", "_args_": ["foo"]})
>>> cfg
{'_target_': 'builtins.len', '_args_': ['foo']}
>>> instantiate(cfg)
3
```

**Comment by Jasha10** [comment]
Thanks @jzazo; I'm adding some documentation on this in PR #2154.
