### ISSUE TITLE
[Bug] enabling tab completion fails in strict mode

### ISSUE THREAD

**Issue by tamuhey** [facebookresearch/hydra#217]
# 🐛 Bug

hydra version: 0.9.0

```bash
$ eval "$(python my_app.py -sc install=bash)"
```

fails. Stderr:

```
Traceback (most recent call last):
  File "my_app.py", line 8, in <module>
    my_app()
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/hydra/main.py", line 25, in decorated_main
    strict,
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/hydra/_internal/utils.py", line 54, in run_hydra
    hydra.shell_completion(overrides=args.overrides)
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 156, in shell_completion
    cfg = self._load_config(overrides)
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 271, in _load_config
    cfg = self.config_loader.load_configuration(overrides)
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/hydra/_internal/config_loader.py", line 66, in load_configuration
    cfg.merge_with_dotlist(remaining_overrides)
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/omegaconf/config.py", line 240, in merge_with_dotlist
    self.update(key, value)
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/omegaconf/config.py", line 260, in update
    root[last] = value
  File "/Users/my_name/.local/share/virtualenvs/ner4-htIaskrI/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 28, in __setitem__
    raise KeyError("Accessing unknown key in a struct : {}".format(self.get_full_key(key)))
KeyError: 'Accessing unknown key in a struct : install'
```

The content of `my_app.py` is below.

```python
import hydra
  
@hydra.main(config_path='config.yaml')
def my_app(cfg):
    print(cfg.pretty())

if __name__ == "__main__":
    my_app()
```

**Comment by omry** [comment]
Hi, unfortunately the instructions in the website are slightly ahead of 0.9, this will be changed in 0.9.1.
for now, to get the proper command - please use --help.

**Comment by tamuhey** [comment]
@omry Thanks!
