### ISSUE TITLE
[Bug] hydra conf in structured config is not well handled

### ISSUE THREAD

**Issue by ssnl** [facebookresearch/hydra#2262]
# 🐛 Bug
## Description

If one tries to override an `hydra.XXX` entry in structured config, they will encoder this AssertionError:
```py
File "/Users/S_sn/miniconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 114, in run
  assert cfg.hydra.mode == RunMode.RUN
```

Upon inspecting, they will find that `cfg.hydra.mode` is somehow the **string** ``"RUN"`` rather than the enum `RunMode.RUN`. I suspect that this is related to some mishandled string <-> enum conversions in hydra.

Once one explicitly provides `mode=RunMode.RUN` in their override, it works again. 

See the following example.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

<details>
  <summary>

Script `repro.py`</summary>

```py
from typing import *

import sys
import os

import hydra
import attrs
import hydra.types
import hydra.core.config_store
from omegaconf import OmegaConf, DictConfig


@attrs.define(kw_only=True)
class Conf:
    x: int = 3

cs = hydra.core.config_store.ConfigStore.instance()


@attrs.define(kw_only=True)
class ConfWithHydraConf:
    x: int = 3
    hydra: Dict = dict()


@attrs.define(kw_only=True)
class ConfWithHydraConfAndExplicitRunMode:
    x: int = 3
    hydra: Dict = dict(
        mode=hydra.types.RunMode.RUN,
    )

cs.store(name='config', node=Conf())
cs.store(name='config_w_hydra', node=ConfWithHydraConf())
cs.store(name='config_w_hydra_and_explicit_run_mode', node=ConfWithHydraConfAndExplicitRunMode())


HYDRA_CONF_TYPE: str = os.environ.get('HYDRA_CONF_TYPE', 'config')


if __name__ == '__main__':
    print('python: ', sys.version)
    print('hydra: ', hydra.__version__)
    print('HYDRA_CONF_TYPE: ', HYDRA_CONF_TYPE)

    @hydra.main(version_base=None, config_name=HYDRA_CONF_TYPE)
    def main(cfg: DictConfig) -> None:
        print()
        print('config is:')
        print(OmegaConf.to_yaml(cfg))

    main()
```

</details>

<details>
  <summary>

Output of `python repro.py`: Correct case without hydra overrides. </summary>
  
```
python:  3.8.11 (default, Jul 29 2021, 14:57:32)
[Clang 12.0.0 ]
hydra:  1.2.0
HYDRA_CONF_TYPE:  config

config is:
x: 3
```

</details>

<details>
  <summary>

Output of `HYDRA_CONF_TYPE=config_w_hydra python repro.py`: **Wrong** case **with** hydra overrides. 

</summary>
  
```
python:  3.8.11 (default, Jul 29 2021, 14:57:32)
[Clang 12.0.0 ]
hydra:  1.2.0
HYDRA_CONF_TYPE:  config_w_hydra
Traceback (most recent call last):
  File "/Users/S_sn/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/Users/S_sn/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/Users/S_sn/miniconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 114, in run
    assert cfg.hydra.mode == RunMode.RUN
AssertionError
```

</details>

<details>
  <summary>

Output of `HYDRA_CONF_TYPE=config_w_hydra_and_explicit_run_mode python repro.py`: **Workaround** case **with** hydra overrides and explicit `RunMode`. 

</summary>
  
```
python:  3.8.11 (default, Jul 29 2021, 14:57:32)
[Clang 12.0.0 ]
hydra:  1.2.0
HYDRA_CONF_TYPE:  config_w_hydra_and_explicit_run_mode

config is:
x: 3
```

</details>

## System information
- **Hydra Version** :  1.2
- **Python version** :  3.8
- **Virtual environment type and version** : n/a
- **Operating system** : mac

**Comment by omry** [comment]
Thanks for the report, and sorry for the long delay.

The underlying OmegaConf bug has been fixed, and this example now works on current Hydra `main`.

One additional note: `@hydra.main()` is designed to be the entry point of the application and is not designed to be wrapped. If you need to control the application flow, please use the [Compose API](https://hydra.cc/docs/advanced/compose_api/).

I am closing this as completed.
