### ISSUE TITLE
[Bug] instantiate stacktrace does not provide config key info

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#2322]
I think this is an edge case. 
for repro pls check out this OC issue https://github.com/omry/omegaconf/issues/991

in particular, this stack trace for this failure does not have enough info for debugging
```
 % python repro.py             
Traceback (most recent call last):
  File "/Users/jieru/workspace/hydra/examples/tutorials/repro/repro.py", line 30, in <module>
    model = hydra.utils.instantiate(model_conf, _recursive_=False)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 202, in instantiate
    config = OmegaConf.structured(config, flags={"allow_objects": True})
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 123, in structured
    return OmegaConf.create(obj, parent, flags)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 176, in create
    return OmegaConf._create_impl(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 882, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 793, in format_and_raise
    _raise(ex, cause)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 843, in _create_impl
    return DictConfig(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 111, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 94, in __init__
    self._set_value(content, flags=flags)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 649, in _set_value
    raise e
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 646, in _set_value
    self._set_value_impl(value, flags)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 676, in _set_value_impl
    data = get_structured_config_data(value, allow_objects=ao)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 481, in get_structured_config_data
    return get_dataclass_data(obj, allow_objects=allow_objects)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 401, in get_dataclass_data
    d[name] = _maybe_wrap(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1070, in _maybe_wrap
    return _node_wrap(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1028, in _node_wrap
    elif issubclass(ref_type, Enum):
omegaconf.errors.ConfigTypeError: issubclass() arg 1 must be a class
    full_key: 
    object_type=None
```

**Comment by jieru-hu** [comment]
@Jasha10 i think you spent some time working on the stacktrace info? could you take a look at this?

**Comment by Jasha10** [comment]
Will do!

**Comment by omry** [comment]
Fixed upstream in omry/omegaconf#993. Verified that the original repro passes with current Hydra and OmegaConf. Closing as completed.
