### ISSUE TITLE
[Bug] hydra/launcher=rq  _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by paantya** [facebookresearch/hydra#2338]
# 🐛 Error
## Description

when running `hydra/launcher=rq` , after all the workers have calculated everything and should have returned the result, the following error is thrown ``` _pickle.UnpicklingError: pickle data was truncated```.

The launch takes place within the framework of one machine, and within the framework of one running docker container.

When launched without `hydra/launcher=rq` , multirun runs fine.

## Control List
- [ ] I checked the latest version of Hydra
- [ ] I created a minimal reproducible (see [this] (https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To play
train_error.py
```python
import hydra
from omegaconf import DictConfig, OmegaConf


@hydra.main(version_base=None, config_path="conf", config_name="config_error")
def my_app(cfg: DictConfig) -> None:

    print(f"OmegaConf.to_yaml(cfg): \n{OmegaConf.to_yaml(cfg)}")
    print(f"ALL OK!")
    return 42

if __name__ == "__main__":
    my_app()
```

conf/config_error.yaml
``` yaml
defaults:
  - _self_

base:
  hypothesis: null
  task: null
  seed: 42
  model_checkpoint: false
  log_level: 20
```

** Script launch code **
```
HYDRA_FULL_ERROR=1 python3.7 train_error.py -m hydra/launcher=rq hydra.launcher.queue=g3080 base.hypothesis=0,1,2,3,4,5,6
```

** Stack trace/error message **
```
[2022-08-12 12:32:13,256][HYDRA] Enqueued 831f0e7d-203b-4831-8510-aba17fa45bbf
[2022-08-12 12:32:13,256][HYDRA] #7 : base.hypothesis=6
[2022-08-12 12:32:13,256][HYDRA] Finished enqueuing
[2022-08-12 12:32:13,256][HYDRA] Polling job statuses every 1.0 sec
Traceback (most recent call last):
  File "train_error.py", line 23, in <module>
    my_app()
  File "/usr/local/lib/python3.7/dist-packages/hydra/main.py", line 95, in decorated_main
    config_name=config_name,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 396, in _run_hydra
    overrides=overrides,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 461, in _run_app
    lambda: hydra.multirun(
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 464, in <lambda>
    overrides=overrides,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 178, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/usr/local/lib/python3.7/dist-packages/hydra_plugins/hydra_rq_launcher/rq_launcher.py", line 45, in launch
    launcher=self, job_overrides=job_overrides, initial_job_idx=initial_job_idx
  File "/usr/local/lib/python3.7/dist-packages/hydra_plugins/hydra_rq_launcher/_core.py", line 156, in launch
    result = job.result if job.result is not None else None
  File "/usr/local/lib/python3.7/dist-packages/rq/job.py", line 539, result
    self._result = self.serializer.loads(rv)
_pickle.UnpicklingError: pickle data was truncated

```

## Expected behavior
will work as it did before, on completion, without this error

## System information
- **Hydra Version**:
hydra.__version__
'1.2.0'
- **Python version**:
Python 3.7.5 (default, Dec 9 2021, 17:04:37)
[GCC 8.4.0] on linux
- **Docker and default env**:
- **Ubuntu18.04** (Docker: `FROMnvidia/cuda:11.7.0-devel-ubuntu18.04` ):

**Comment by paantya** [comment]
@jieru-hu FYI

**Comment by Timurff** [comment]
I have exact same problems, haven't find a solution yet

**Comment by EspenHa** [comment]
I also encountered this issue, and I believe I managed to fix it.
First, make sure to start your rq workers with a serializer based on cloudpickle, like this:
`rq worker default -S src.task_queue.CloudSerializer`, and `src/task_queue.py` defined as follows:
```python
# src/task_queue.py

import cloudpickle

class CloudSerializer:
    dumps = cloudpickle.dumps
    loads = cloudpickle.loads
```

I then encountered another error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 182, in sweep
    _ = r.return_value
AttributeError: 'NoneType' object has no attribute 'return_value'
```
Which I fixed by changing the following line: https://github.com/facebookresearch/hydra/blob/9a7a0941f358e3c202e784ad58f7c77fa84c28a2/plugins/hydra_rq_launcher/hydra_plugins/hydra_rq_launcher/_core.py#L155-L157

to 
```python
for job in jobs: 
    result = job 
    runs.append(result)
```
