### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#2348]
# 🐛 Bug
## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```python
# repro.py
from dataclasses import dataclass, field
from typing import Any, Dict
import hydra
from hydra.core.config_store import ConfigStore

@dataclass
class MyAppConfig:
    req_int: int
    opt_str: str = "Default String"
    opt_float: float = 3.14

    hydra: Dict[str, Any] = field(default_factory=lambda: {"job": {"chdir": False}})

cs = ConfigStore.instance()
# Registering the Config class with the name 'base_config'.
cs.store(name="base_config", node=MyAppConfig)

@hydra.main(version_base=None, config_name="base_config")
def my_app(cfg: MyAppConfig) -> None:
    print(cfg)

if __name__ == "__main__":
    my_app()
```
```python
$ python repro.py
Traceback (most recent call last):
  File "/home/rig1/dev/hydra/hydra/_internal/utils.py", line 217, in run_and_report
    return func()
  File "/home/rig1/dev/hydra/hydra/_internal/utils.py", line 457, in <lambda>
    lambda: hydra.run(
  File "/home/rig1/dev/hydra/hydra/_internal/hydra.py", line 115, in run
    assert cfg.hydra.mode == RunMode.RUN
AssertionError
```

## System information
- **Python version** : 3.10
- **Hydra version** : `main` branch HEAD (commit 98a051d36a)

## Additional context
The assertion error in the traceback happens because the value of `cfg.hydra.mode` is the string `"RUN"`, which is not equal to the enum member `RunMode.RUN`.
There might be an underlying OmegaConf issue here.

**Comment by Jasha10** [comment]
I've opened omegaconf issue https://github.com/omry/omegaconf/issues/998 which causes this issue.

**Comment by cifkao** [comment]
Is there any workaround?

It seems that when using a top-level dataclass, configuring Hydra there is actually necessary in order to specify `searchpath`, which needs to be specified in the primary config.

**Comment by omry** [comment]
This appears to be fixed on current `main` with the OmegaConf line used by Hydra 1.4. The linked upstream issue, omry/omegaconf#998, is also closed as completed.

I verified the original repro locally and it no longer hits the `cfg.hydra.mode` assertion. Closing as completed.
