### ISSUE TITLE
[Bug] Cannot override group and group variable at the same time

### ISSUE THREAD

**Issue by camall3n** [facebookresearch/hydra#2390]
# 🐛 Bug
## Description
Cannot override group and group variable at the same time.

For example:
```text
 python main.py car=vw car/color=black
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Directory structure:
```text
├── conf
│   ├── car
│   │   └── vw.yaml
│   └── config.yaml
└── main.py
```

main.py:
```python
import hydra

@hydra.main(config_path="./conf", config_name='config', version_base=None)

def main(cfg):
    pass

main()
```

conf/config.yaml:
```yaml
defaults:
  - _self_
  - car: null

name: Alice
car: ???
```

conf/car/vw.yaml:
```yaml
make: vw
model: beetle
color: red
```

I can print the default config and optionally override the `car` with `vw` or a dictionary that sets the `color` field, but when I try to set both the `car=vw` and the `car/color=black` at the same time, it fails.
```text
$ python main.py --cfg job
name: Alice
car: ???

$ python main.py car=vw --cfg job
name: Alice
car:
  make: vw
  model: beetle
  color: red

$ python main.py car="{make:bmw,model:3series,color:black}" --cfg job
name: Alice
car:
  make: bmw
  model: 3series
  color: black

$ python main.py car=vw car/color=black --cfg job
Could not override 'car/color'.
To append to your config use +car/color=black
Key 'car/color' is not in struct
    full_key: car/color
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/Users/cam/dev/hydra/hydra/_internal/config_loader_impl.py", line 384, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 729, in update
    root.__setattr__(last_key, value)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 337, in __setattr__
    raise e
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 334, in __setattr__
    self.__set_impl(key, value)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 547, in _set_item_impl
    self._validate_set(key, value)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/Users/cam/dev/hydra/venv/lib/python3.9/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'car/color' is not in struct
    full_key: car/color
    object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cam/dev/factored-reps/hydra-test/main.py", line 7, in <module>
    main()
  File "/Users/cam/dev/hydra/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/Users/cam/dev/hydra/hydra/_internal/utils.py", line 403, in _run_hydra
    run_and_report(
  File "/Users/cam/dev/hydra/hydra/_internal/utils.py", line 220, in run_and_report
    raise ex
  File "/Users/cam/dev/hydra/hydra/_internal/utils.py", line 217, in run_and_report
    return func()
  File "/Users/cam/dev/hydra/hydra/_internal/utils.py", line 404, in <lambda>
    lambda: hydra.show_cfg(
  File "/Users/cam/dev/hydra/hydra/_internal/hydra.py", line 195, in show_cfg
    cfg = self.compose_config(
  File "/Users/cam/dev/hydra/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/Users/cam/dev/hydra/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/Users/cam/dev/hydra/hydra/_internal/config_loader_impl.py", line 270, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/Users/cam/dev/hydra/hydra/_internal/config_loader_impl.py", line 386, in _apply_overrides_to_config
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: Could not override 'car/color'.
To append to your config use +car/color=black
```

## Expected Behavior
The `car` group info should come from vw.yaml, and the `color` field should be 'black':
```text
$ python main.py car=vw --cfg job
name: Alice
car:
  make: vw
  model: beetle
  color: black
```

**Note:** Overriding the variable using `+car/color=black` also doesn't work:
```text
$ python main.py car=vw +car/color=black --cfg job
name: Alice
car:
  make: vw
  model: beetle
  color: red
car/color: black
```

## System information
- **Hydra Version** : 1.3.0.dev - 92a53421
- **Python version** : 3.9.13
- **Virtual environment type and version** : python venv + pip (22.1.1)
- **Operating system** : macOS 10.15.7

**Comment by Jasha10** [comment]
Give this a try:
```python
python main.py car=vw car.color=black
```

**Comment by Jasha10** [comment]
The syntax `'foo/bar=value'` is used for modifying the defaults list (e.g. for appending to the defaults list or overriding an existing entry in the defaults list). Meanwhile, the syntax `'foo.bar=value'` directly modifies the composed config object.

Ref: [Hydra's Override grammar](https://hydra.cc/docs/1.2/advanced/override_grammar/basic/#basic-examples)

**Comment by camall3n** [comment]
Ah, that works! Thank you.
