### ISSUE TITLE
[Bug] Interpolation Key error when using absolute path

### ISSUE THREAD

**Issue by MathKlim** [facebookresearch/hydra#2405]
# 🐛 Bug
## Description
This might be Omegaconf related, but this happens when I use the Hydra `defaults` list option. Here's the architecture of the project for the record.

```
.
├── bug
│   ├── config.py
│   ├── configs
│   │   ├── data_sources
│   │   │   └── sources.yaml
│   │   ├── params.yaml
│   │   └── training
│   │       └── custom.yaml
│   └── __init__.py
└── requirements.txt
```

When I try to use absolute path to do interpolation in config file which are in the default list I get an InterpolationKey error.

```yaml
# params.yaml
---
defaults:
    - _self_
    - data_sources: sources
    - training: custom

monitoring:
    name: test
    exp: ${monitoring.name}_exp

hydra:
    job:
        chdir: false
    run:
        dir: outputs/hydra/${now:%Y-%m-%d_%H-%M-%S}
```

For example, with `data_cources/sources.yaml` I am forced to use relative path so that the resolution of the config with `initialize` is successful, i.e. like 

```yaml
# sources.yaml
data:
      data_dir: /path
raw:
      data_dir_raw: ${..data.data_dir}/raw1
      data_dir_raw2: ${.data_dir_raw}/raw2
test: ${training.lr}
```
 then, with 

```python
# config.py
from hydra import compose, initialize
from omegaconf import OmegaConf, DictConfig
import hydra

with initialize(version_base="1.2", config_path="./configs/"):
    cfg = compose(config_name="params")
    print(OmegaConf.to_yaml(cfg, resolve=True))


    print(f"{cfg.data_sources.raw.data_dir_raw}")
    print(f"{cfg.data_sources.data.data_dir}")
```

I have a successful interpolation, 

```shell
❯ python bug/config.py
monitoring:
  name: test
  exp: test_exp
data_sources:
  data:
    data_dir: /path
  raw:
    data_dir_raw: /path/raw1
    data_dir_raw2: /path/raw1/raw2
  test: 0.003
training:
  lr: 0.003

/path/raw1
/path
```

But, if I put absolute paths

```yaml
#sources.yaml
data:
      data_dir: /path
raw:
      data_dir_raw: ${data.data_dir}/raw1
      data_dir_raw2: ${raw.data_dir_raw}/raw2
test: ${training.lr}
```
I get the following error.

```shell
...
    raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'data.data_dir' not found
    full_key: data_sources.raw.data_dir_raw
    object_type=dict
```

I was thinking, maybe it's because `data` defines another dictionary than `raw`, but even with this configuration, where the absolute path refers to a path in the same dictionary, it fails.

```yaml
data:
      data_dir: /path
raw:
      data_dir_raw: ${..data.data_dir}/raw1
      data_dir_raw2: ${raw.data_dir_raw}/raw2
test: ${training.lr}
```

I was certain I could use absolute path like that in older versions of Hydra, but now I'm confused. Did I miss something ?

## Checklist
- [x] I checked on the latest version of Hydra : I'm using Hydra 1.2
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips). : Here's the link to a repo with the code, [click here](https://github.com/MathKlim/hydra_compose_behavior).

## To reproduce

1. git clone the [repo](https://github.com/MathKlim/hydra_compose_behavior).
2. Install the requirements (hydra-core==1.2.0)
3. Launch `python bug/config.py` to see everything goes well.
4. Change `data_sources/sources.yaml` to
```yaml
data:
      data_dir: /path
raw:
      data_dir_raw: ${data.data_dir}/raw1
      data_dir_raw2: ${raw.data_dir_raw}/raw2
test: ${training.lr}
```
5. Launch `python bug/config.py` to see it fail.

** Stack trace/error message **
```shell
❯ python bug/config.py
Traceback (most recent call last):
  File "bug/config.py", line 7, in <module>
    print(OmegaConf.to_yaml(cfg, resolve=True))
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 747, in to_yaml
    container = OmegaConf.to_container(cfg, resolve=resolve, enum_to_str=True)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 561, in to_container
    return BaseContainer._to_content(
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 292, in _to_content
    value = get_node_value(key)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 247, in get_node_value
    value = BaseContainer._to_content(
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 292, in _to_content
    value = get_node_value(key)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 247, in get_node_value
    value = BaseContainer._to_content(
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 292, in _to_content
    value = get_node_value(key)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 244, in get_node_value
    conf._format_and_raise(key=key, value=None, cause=e)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 242, in get_node_value
    node = node._dereference_node()
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 246, in _dereference_node
    node = self._dereference_node_impl(throw_on_resolution_failure=True)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 277, in _dereference_node_impl
    return parent._resolve_interpolation_from_parse_tree(
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 921, in accept
    return visitor.visitInterpolationNode(self)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 745, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/home/vorph/miniconda3/envs/bug/lib/python3.8/site-packages/omegaconf/base.py", line 676, in _resolve_node_interpolation
    raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'raw.data_dir_raw' not found
    full_key: data_sources.raw.data_dir_raw2
    object_type=dict
```

## Expected Behavior
The configuration should be resolved whether I use absolute path or relative path.

## System information
- **Hydra Version** :  1.2
- **Python version** :  3.8
- **Virtual environment type and version** :  conda
- **Operating system** : Ubuntu 20.04

**Comment by Jasha10** [comment]
You can add a print statement to `config.py` to get a hint at what's going on:
```python
...
with initialize(version_base="1.2", config_path="./configs/"):
    cfg = compose(config_name="params")
    print(cfg)  # new print statement before calling OmegaConf.to_yaml
    # alternatively, call OmegaConf.to_yaml with resolve=False
    print(OmegaConf.to_yaml(cfg, resolve=Fase))
...
```

Here's the result of calling `OmegaConf.to_yaml` with `resolve=False`:
```yaml
monitoring:
  name: test
  exp: ${monitoring.name}_exp
data_sources:
  data:
    data_dir: /path
  raw:
    data_dir_raw: ${data.data_dir}/raw1
    data_dir_raw2: ${raw.data_dir_raw}/raw2
  test: ${training.lr}
training:
  lr: 0.003
```
It is now clear why the absolute paths `data.data_dir` and `raw.data_dir_raw` fail to resolve: there is no `data` key at the top-level of the config, nor is there a `raw` key. You'll need to use `${data_sources.data.data_dir}` and `${data_sources.raw.data_dir_raw}`.

**Comment by MathKlim** [comment]
Ok, thanks for clarifying things.

**Comment by Jasha10** [comment]
You're welcome!
