### ISSUE TITLE
submitit_local : torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by praksharma** [facebookresearch/hydra#2465]
I use `submitit_local` inside an interactive session on a HPC cluster to avoid `gres` and `srun` settings, still use multiple GPUs in parallel. There is something wrong with my config file.

```yaml
defaults:
  - override hydra/launcher: submitit_local

hydra:
    mode: MULTIRUN
    sweeper:
        params:
            +n: 5,10,15
            +a_lims: "{a_lower : 0.5, a_upper : 1.1, a : 0.91},{a_lower : 0.7, a_upper : 1.15, a : 1.05}, {a_lower : 0.9, a_upper : 1.15, a : 1.09}"
            +pde_coeff: 0.1, 1.0
    launcher:
        _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
        submitit_folder: ${hydra.sweep.dir}/.submitit/%j
        timeout_min: 60
        cpus_per_task: 4
        gpus_per_node: 2
        tasks_per_node: 1
        nodes: 1
        name: ${hydra.job.name}
```

I am using 2 x RTX A100 40GB. The code works fine without Hydra and with the default launcher on a single GPU. Whenever I run code with above config using either `python file.py` or `mpirun -np 2 python file.py` I get the following error:

```text
[s.1915438@scs2046(sunbird) 9. multi gpu]$ mpirun -np 2 python 1.single_notebook.py 
[2022-11-15 10:20:47,440][HYDRA] Submitit 'local' sweep output dir : multirun/2022-11-15/10-20-45
[2022-11-15 10:20:47,444][HYDRA]        #0 : +n=5 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=0.1
[2022-11-15 10:20:47,456][HYDRA]        #1 : +n=5 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=1.0
[2022-11-15 10:20:47,467][HYDRA]        #2 : +n=5 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=0.1
[2022-11-15 10:20:47,478][HYDRA]        #3 : +n=5 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=1.0
[2022-11-15 10:20:47,489][HYDRA]        #4 : +n=5 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=0.1
[2022-11-15 10:20:47,501][HYDRA]        #5 : +n=5 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=1.0
[2022-11-15 10:20:47,509][HYDRA]        #6 : +n=10 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=0.1
[2022-11-15 10:20:47,523][HYDRA] Submitit 'local' sweep output dir : multirun/2022-11-15/10-20-45
[2022-11-15 10:20:47,525][HYDRA]        #0 : +n=5 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=0.1
[2022-11-15 10:20:47,526][HYDRA]        #7 : +n=10 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=1.0
[2022-11-15 10:20:47,537][HYDRA]        #1 : +n=5 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=1.0
[2022-11-15 10:20:47,540][HYDRA]        #8 : +n=10 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=0.1
[2022-11-15 10:20:47,548][HYDRA]        #2 : +n=5 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=0.1
[2022-11-15 10:20:47,562][HYDRA]        #3 : +n=5 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=1.0
[2022-11-15 10:20:47,577][HYDRA]        #4 : +n=5 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=0.1
[2022-11-15 10:20:47,592][HYDRA]        #5 : +n=5 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=1.0
[2022-11-15 10:20:47,600][HYDRA]        #6 : +n=10 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=0.1
[2022-11-15 10:20:47,606][HYDRA]        #7 : +n=10 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=1.0
[2022-11-15 10:20:47,613][HYDRA]        #8 : +n=10 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=0.1
[2022-11-15 10:20:47,617][HYDRA]        #9 : +n=10 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=1.0
[2022-11-15 10:20:47,634][HYDRA]        #10 : +n=10 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=0.1
[2022-11-15 10:20:47,651][HYDRA]        #11 : +n=10 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=1.0
[2022-11-15 10:20:47,667][HYDRA]        #12 : +n=15 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=0.1
[2022-11-15 10:20:47,680][HYDRA]        #13 : +n=15 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=1.0
[2022-11-15 10:20:47,692][HYDRA]        #14 : +n=15 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=0.1
[2022-11-15 10:20:47,694][HYDRA]        #9 : +n=10 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=1.0
[2022-11-15 10:20:47,705][HYDRA]        #10 : +n=10 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=0.1
[2022-11-15 10:20:47,708][HYDRA]        #15 : +n=15 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=1.0
[2022-11-15 10:20:47,716][HYDRA]        #11 : +n=10 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=1.0
[2022-11-15 10:20:47,722][HYDRA]        #16 : +n=15 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=0.1
[2022-11-15 10:20:47,728][HYDRA]        #12 : +n=15 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=0.1
[2022-11-15 10:20:47,738][HYDRA]        #17 : +n=15 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=1.0
[2022-11-15 10:20:47,739][HYDRA]        #13 : +n=15 +a_lims={a_lower:0.5,a_upper:1.1,a:0.91} +pde_coeff=1.0
[2022-11-15 10:20:47,750][HYDRA]        #14 : +n=15 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=0.1
[2022-11-15 10:20:47,761][HYDRA]        #15 : +n=15 +a_lims={a_lower:0.7,a_upper:1.15,a:1.05} +pde_coeff=1.0
[2022-11-15 10:20:47,773][HYDRA]        #16 : +n=15 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=0.1
[2022-11-15 10:20:47,789][HYDRA]        #17 : +n=15 +a_lims={a_lower:0.9,a_upper:1.15,a:1.09} +pde_coeff=1.0
Error executing job with overrides: ['+n=5', '+a_lims={a_lower:0.5,a_upper:1.1,a:0.91}', '+pde_coeff=0.1']
Error executing job with overrides: ['+n=5', '+a_lims={a_lower:0.5,a_upper:1.1,a:0.91}', '+pde_coeff=0.1']
Traceback (most recent call last):
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 182, in sweep
    _ = r.return_value
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

CUDA call was originally invoked at:

['  File "/scratch/s.1915438/modulus/lib/python3.9/runpy.py", line 197, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n', '  File "/scratch/s.1915438/modulus/lib/python3.9/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/_submit.py", line 11, in <module>\n    submitit_main()\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/submission.py", line 72, in submitit_main\n    process_job(args.folder)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/submission.py", line 51, in process_job\n    delayed = utils.DelayedSubmission.load(paths.submitted_pickle)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/utils.py", line 149, in load\n    obj = pickle_load(filepath)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/utils.py", line 226, in pickle_load\n    return pickle.load(ifile)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/cloudpickle/cloudpickle.py", line 649, in subimport\n    __import__(name)\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 850, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/torch/__init__.py", line 772, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 850, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/torch/cuda/__init__.py", line 179, in <module>\n    _lazy_call(_check_capability)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/torch/cuda/__init__.py", line 177, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']
Traceback (most recent call last):
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 182, in sweep
    _ = r.return_value
  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

CUDA call was originally invoked at:

['  File "/scratch/s.1915438/modulus/lib/python3.9/runpy.py", line 197, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n', '  File "/scratch/s.1915438/modulus/lib/python3.9/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/_submit.py", line 11, in <module>\n    submitit_main()\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/submission.py", line 72, in submitit_main\n    process_job(args.folder)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/submission.py", line 51, in process_job\n    delayed = utils.DelayedSubmission.load(paths.submitted_pickle)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/utils.py", line 149, in load\n    obj = pickle_load(filepath)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/submitit/core/utils.py", line 226, in pickle_load\n    return pickle.load(ifile)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/cloudpickle/cloudpickle.py", line 649, in subimport\n    __import__(name)\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 850, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/torch/__init__.py", line 772, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 850, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/torch/cuda/__init__.py", line 179, in <module>\n    _lazy_call(_check_capability)\n', '  File "/scratch/s.1915438/env/modulus/lib/python3.9/site-packages/torch/cuda/__init__.py", line 177, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']
[s.1915438@scs2046(sunbird) 9. multi gpu]$ 
```

My GPUs are configured as follows:
```sh
[s.1915438@scs2046(sunbird) 9. multi gpu]$ nvidia-smi
Tue Nov 15 10:21:02 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:43:00.0 Off |                   On |
| N/A   42C    P0    36W / 250W |     48MiB / 40960MiB |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  Off  | 00000000:44:00.0 Off |                   On |
| N/A   42C    P0    36W / 250W |     45MiB / 40960MiB |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| MIG devices:                                                                |
+------------------+----------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
|      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
|                  |                      |        ECC|                       |
|==================+======================+===========+=======================|
|  0    3   0   0  |     15MiB /  9856MiB | 28      0 |  2   0    1    0    0 |
|                  |      0MiB / 16383MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+
|  0    4   0   1  |     13MiB /  9856MiB | 28      0 |  2   0    1    0    0 |
|                  |      0MiB / 16383MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+
|  1    3   0   0  |     13MiB /  9856MiB | 28      0 |  2   0    1    0    0 |
|                  |      0MiB / 16383MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+
|  1    5   0   1  |     13MiB /  9856MiB | 28      0 |  2   0    1    0    0 |
|                  |      0MiB / 16383MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Jasha10** [comment]
@praksharma can you please make a minimal reproducible example?

**Comment by BramVanroy** [comment]
@praksharma How did you solve this?

**Comment by praksharma** [comment]
> @praksharma How did you solve this?

The problem was that I was using all the GPU's on the node. For example, if I have 8 GPUs on the node and I allocated only 3. So this was problematic `device > num_gpus `.
* So, i ended up storing the GPU numbers of all available GPU in a txt file, and GPU number of the GPU used to run the last instance. 
* Number of concurrent jobs were equal to the number of available GPU.
* I created a function that respects all above points and runs a job on free GPU.
I know this is not a good solution, but it worked for me.

**Comment by BramVanroy** [comment]
@praksharma Thanks for getting back to me! After looking further it would seem that in my case we are having a faulty GPU in our cluster, leading to poor initialization.

**Comment by hume-brian** [comment]
Throwing my hat in the ring here: if you're using GKE for hosting your GPUs, you can't request multiple GPUs for your pod/deployment. 

> A pod can only consume up to one multi-instance GPU instance.

https://cloud.google.com/kubernetes-engine/docs/how-to/gpus-multi
