### ISSUE TITLE
[Bug] Cannot override @_global_ package from CLI

### ISSUE THREAD

**Issue by jbaczek** [facebookresearch/hydra#2628]
# 🐛 Bug
## Description
I have a config file like this:
```yaml
defaults:
  - model: ???
  - optional overrides@_global_:  # Empty by default
```
In hydra 1.1.1 I used the overrides package to override values in other branches of tree (for example with the best values for model parameters). If I wanted to do a bunch of overrides at once I used `python my_app.py model=foo overrides=best` which worked fine. But since hydra 1.2.0 this behavior has changed and now hydra yells at me with
```
Could not override 'overrides'.
Did you mean to override overrides@_global_?
To append to your default list use +overrides=best
```
The previous behavior can be achieved by introducing `# @package _global_` at the beginning of each override file. But this is cumbersome, because it can be easily overlooked. It was easier to put `@_global_` once in the defaults list.
Is this behavior intended?

## Checklist
- [ x] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
** Minimal Code/Config snippet to reproduce **
Config structure:
```
conf
├── config.yaml
├── model
│   ├── bar.yaml
│   └── foo.yaml
└── overrides
    └── best.yaml
```
File content:
/conf/model/foo.yaml
```yaml
config:
  hdim: 4
  cdim: 8
```
./conf/model/bar.yaml
```yaml
config:
  hdim: 2
  cdim: 16
```
./conf/overrides/best.yaml
```yaml
config:
  hdim: 3
```
./conf/config.yaml
```yaml
defaults:
  - model: ???
  - optional overrides@_global_: # Empty by default
```
```python
# my_app.py
from omegaconf import OmegaConf
import hydra

@hydra.main(config_path="conf", config_name="config")
def my_app(cfg) -> None:
    print(OmegaConf.to_yaml(cfg))

my_app()
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "my_app.py", line 9, in <module>
    my_app()
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/defaults_list.py", line 753, in create_defaults_list
    overrides.ensure_overrides_used()
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/defaults_list.py", line 168, in ensure_overrides_used
    raise ConfigCompositionException(msg)
hydra.errors.ConfigCompositionException: Could not override 'overrides'.
Did you mean to override overrides@_global_?
To append to your default list use +overrides=best
```

## Expected Behavior
A correct substitution should take place at _global_ level. The output of running `python my_app.py model=foo overrides=best` should be
```
model:        
  config:                                                                                                                                    
    hdim: 3
    cdim: 8 
```
## System information
- **Hydra Version** : 1.3.0 
- **Python version** : 3.8.10
- **Virtual environment type and version** : Docker container
- **Operating system** : Linux jbaczek-ws 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## Additional context
https://github.com/facebookresearch/hydra/issues/1784
https://github.com/facebookresearch/hydra/pull/1791

**Comment by omry** [comment]
This change is intentional as is the solution of some ambiguity if I remember correctly.
Does using `overrides@_global_=foo` in the command line, as suggested - solves your problem?
Alternatively, as you pointed out - you can add `# @package _global_` at the top of your override files, which is the command approach (as documented [here](https://hydra.cc/docs/patterns/configuring_experiments/).
