### ISSUE TITLE
[Bug] OmegaConf produces hydra interpolation error in ddp_spawn training in PyTorch Lightning

### ISSUE THREAD

**Issue by libokj** [facebookresearch/hydra#2629]
# 🐛 Bug
## Description
omegaconf produces an interpolation error in ddp_spawn training in PyTorch Lightning 1.9.4 when interpolating strings with hydra resolver `${hydra:...}`

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
trainer.yaml for PL trainer
```
_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 50
check_val_every_n_epoch: 1
deterministic: False
strategy: ddp_spawn
accelerator: gpu
devices: 4
num_nodes: 1
sync_batchnorm: True
```

** Stack trace/error message **
```
[2023-01-04 16:34:17,037][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/nvme/louzekun/playground/lightning-hydra-template-1.5.0/src/utils/utils.py", line 38, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
######## (This part is about multiprocessing)
  File "/nvme/louzekun/miniconda3/envs/ml/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/nvme/louzekun/miniconda3/envs/ml/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
######## (This part is about omegaconf)
  File "/nvme/louzekun/miniconda3/envs/ml/lib/python3.10/site-packages/omegaconf/base.py", line 703, in _evaluate_custom_resolver
    raise UnsupportedInterpolationType(
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type hydra
    full_key: trainer.default_root_dir
    object_type=dict

[2023-01-04 16:34:17,039][src.utils.utils][INFO] - Output dir: /nvme/louzekun/playground/lightning-hydra-template-1.5.0/logs/train/runs/2023-01-04_16-34-10
[2023-01-04 16:34:17,039][src.utils.utils][INFO] - Closing loggers...
Error executing job with overrides: ['trainer=ddp', 'trainer.max_epochs=5', 'logger=csv']
Traceback (most recent call last):
  File "/nvme/louzekun/playground/lightning-hydra-template-1.5.0/src/train.py", line 122, in main
    metric_dict, _ = train(cfg)
######## (This part repeated the same errors as above)
  File "/nvme/louzekun/miniconda3/envs/ml/lib/python3.10/site-packages/omegaconf/base.py", line 703, in _evaluate_custom_resolver
    raise UnsupportedInterpolationType(
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type hydra
    full_key: trainer.default_root_dir
    object_type=dict
```

## Expected Behavior
The hydra resolver should not cause omegaconf error `Unsupported interpolation type` 

## System information
- **Hydra Version** :  1.31
- **Python version** : 3.9
- **Virtual environment type and version** : conda 22.11.0
- **Operating system** : Windows 11

## Additional context
Multiple reports of this error were received by users of the lightning-hydra-template project:
https://github.com/ashleve/lightning-hydra-template/issues/495
Potentially related issue: https://github.com/facebookresearch/hydra/issues/2070

**Comment by omry** [comment]
Please reopen once you have provided a minimal repro.

**Comment by nqhq-lou** [comment]
I have encountered the same problem, see https://github.com/ashleve/lightning-hydra-template/issues/495
