### ISSUE TITLE
Instantiations within instantiations

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/hydra#2679]
I'm using instantiations of objects which instantiate other objects (using Hydra's `instantiate()`) within a pip package. All of this seems to result in the nested instantiations throwing this error:

`InstantiationException("Error locating target 'Path.To.Target', set env var HYDRA_FULL_ERROR=1 to see chained exception.)`

However, the top-level instantiations still work.

**Comment by Jasha10** [comment]
@slerman12 could you give an example an object that fails to instantiate?

**Comment by slerman12** [comment]
I wasn't getting this error with hydra 1.1. If it's alright, I'd like to change my question. Why do I get this error with Hydra 1.1 (after updating some dependencies)?

```
Traceback (most recent call last):
  File "/Users/sam/Code/Builder/src/UnifiedML/Run.py", line 5, in <module>
    import hydra
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 11, in <module>
    from hydra._internal.utils import _locate
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/_internal/utils.py", line 17, in <module>
    from hydra.core.utils import get_valid_filename, validate_config_path
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/core/utils.py", line 19, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/core/hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/conf/__init__.py", line 45, in <module>
    class JobConf:
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/site-packages/hydra/conf/__init__.py", line 70, in JobConf
    @dataclass
     ^^^^^^^^^
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/miniconda3/envs/Sam/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory
```

**Comment by omry** [comment]
You are still missing a minimal reproducible example of your issue.

**Comment by slerman12** [comment]
Install Python 11.3.

Install Hydra 1.1. 

Run any code with Hydra. 


It doesn't matter anyway.

**Comment by Jasha10** [comment]
> I wasn't getting this error with hydra 1.1. 

Python 3.11 is incompatible with older versions of Hydra.
You should either:
- downgrade to python 3.10 or earlier, or
- upgrade to Hydra 1.3.0 or later.

**Comment by slerman12** [comment]
Okay, here's a really good minimal example of the original bug. Create a file called `original_bug.py` and run this:

```
import hydra


class Inception:
    def __init__(self):
        hydra.utils.instantiate({'_target_': 'original_bug.Cow'})


@hydra.main(config_path=None)
def main(*_):
    hydra.utils.instantiate({'_target_': 'original_bug.Inception'})


if __name__ == '__main__':
    main()
```

**Comment by omry** [comment]
Please reopen if you still see the problem after following the advice from Jasha.
