### ISSUE TITLE
[Bug] submitit and structured config.

### ISSUE THREAD

**Issue by manuel-delverme** [facebookresearch/hydra#2697]
# 🐛 Bug
## Description

The error:

SlurmQueueConf is not a subclass of SlurmQueueConf

is confusing me, it seems the class SlurmQueueConf is redefined at some point?

SlurmQueueConf.__module__ is the same for source and target but the memory addresses differ, also if i inherit from the SlurmQueueConf class, the other class has no elements in it's __subclass__  

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
import dataclasses
import logging
import os
import time
from typing import Dict

import hydra
import submitit
from hydra.core.config_store import ConfigStore
from hydra_plugins.hydra_submitit_launcher.config import SlurmQueueConf
from omegaconf import DictConfig

log = logging.getLogger(__name__)


@dataclasses.dataclass
class Config:
    defaults = [
        {"hydra/launcher": "submitit_slurm"}
    ]
    hydra: Dict[str, SlurmQueueConf] = dataclasses.field(default_factory=lambda: {
        "launcher": SlurmQueueConf(partition="main")
    })


cs = ConfigStore.instance()
cs.store(
    name="config",
    node=Config,
    provider=__file__,
)


@hydra.main(version_base=None, config_path=".", config_name="config")
def my_app(cfg: DictConfig) -> None:
    env = submitit.JobEnvironment()
    log.info(f"Process ID {os.getpid()} executing task {cfg.task}, with {env}")
    time.sleep(1)


if __name__ == "__main__":
    my_app()

```
** Stack trace/error message **
```
(venv) ➜  traces_llm git:(libraries) ✗ HYDRA_FULL_ERROR=1 python myapp.py hydra/launcher=submitit_slurm 
Traceback (most recent call last):
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 542, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 372, in _map_merge
    dest_node._validate_merge(value=src_node)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 239, in _validate_merge
    raise ValidationError(msg)
omegaconf.errors.ValidationError: Merge error: SlurmQueueConf is not a subclass of SlurmQueueConf. value: {'submitit_folder': '${hydra.sweep.dir}/.submitit/%j', 'timeout_min': 60, 'cpus_per_task': None, 'gpus_per_node': None, 'tasks_per_node': 1, 'mem_gb': None, 'nodes': 1, 'name': '${hydra.job.name}', 'stderr_to_stdout': False, '_target_': 'hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher', 'partition': 'main', 'qos': None, 'comment': None, 'constraint': None, 'exclude': None, 'gres': None, 'cpus_per_gpu': None, 'gpus_per_task': None, 'mem_per_gpu': None, 'mem_per_cpu': None, 'account': None, 'signal_delay_s': 120, 'max_num_timeout': 0, 'additional_parameters': {}, 'array_parallelism': 256, 'setup': None}
    full_key: 
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delverme/projects/traces_llm/myapp.py", line 42, in <module>
    my_app()
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 263, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 544, in _compose_config_from_defaults_list
    raise ConfigCompositionException(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 542, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 372, in _map_merge
    dest_node._validate_merge(value=src_node)
  File "/home/delverme/projects/venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 239, in _validate_merge
    raise ValidationError(msg)
hydra.errors.ConfigCompositionException: In 'config': ValidationError raised while composing config:
Merge error: SlurmQueueConf is not a subclass of SlurmQueueConf. value: {'submitit_folder': '${hydra.sweep.dir}/.submitit/%j', 'timeout_min': 60, 'cpus_per_task': None, 'gpus_per_node': None, 'tasks_per_node': 1, 'mem_gb': None, 'nodes': 1, 'name': '${hydra.job.name}', 'stderr_to_stdout': False, '_target_': 'hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher', 'partition': 'main', 'qos': None, 'comment': None, 'constraint': None, 'exclude': None, 'gres': None, 'cpus_per_gpu': None, 'gpus_per_task': None, 'mem_per_gpu': None, 'mem_per_cpu': None, 'account': None, 'signal_delay_s': 120, 'max_num_timeout': 0, 'additional_parameters': {}, 'array_parallelism': 256, 'setup': None}
    full_key: 
    object_type=dict

```

## System information
- **Hydra Version** :  
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by shagunsodhani** [comment]
@manuel-delverme could you update the issue with system information ?

**Comment by manuel-delverme** [comment]
Done

**Comment by omry** [comment]
Thanks for the report. I reproduced the original failure with Hydra 1.3.2 and `hydra-submitit-launcher` 1.2.0:

```text
Merge error: SlurmQueueConf is not a subclass of SlurmQueueConf
```

The same repro now composes successfully on current `main` / the Hydra 1.4 line, including `--cfg hydra -p hydra.launcher` with the `partition` override preserved.

Closing this as fixed in Hydra 1.4.
