### ISSUE TITLE
[Bug] Reproducing a Hydra run from previous Hydra job configs - WITH SCHEMA

### ISSUE THREAD

**Issue by noamgot** [facebookresearch/hydra#2720]
# 🐛 Bug
## Description
This is a particular case of the issue raised in #1805  - except in this case, my yaml config file has a defined schema.

The problem is that the saved config yaml file does not contain the schema, and when using `Omegacong.to_object` on the dict config, it converts it into a vanilla dict, instead of the desired dataclass.

## Checklist
- [v] I checked on the latest version of Hydra
- [v] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Consider this minimal example:

**yaml file - config.yaml**
```yaml
# config.yaml
defaults:
  - config_schema
  - _self_

x: 123
y: 456
```

**code - main.py**
```python
from dataclasses import dataclass

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import DictConfig, OmegaConf


@dataclass
class Foo:
    x: int = 0
    y: int = 1


cs = ConfigStore.instance()
cs.store(name="config_schema", node=Foo)


@hydra.main(config_name="config", config_path=".", version_base=None)
def main(config: DictConfig):
    config_obj: Foo = OmegaConf.to_object(config)
    print(config_obj.x)
    print(config_obj.y)


if __name__ == '__main__':
    main()

```
_Assume that `main.py` and `config.yaml` are located in the same directory._

When running:
```sh
python main.py 
```
There's no problem, and it prints:
```sh
123
456
```

But when I try to reproduce this file (naively) with this command:
```sh
python main.py --config-path /..../outputs/.../.hydra/ --config-name=config
```

** Stack trace/error message **
```
AttributeError: 'dict' object has no attribute 'x'
```

## Expected Behavior
From my point of view, I believe that the config.yaml should be saved with the original schema. If it's rather a feature than a bug - I'd love to hear what's the correct way to reproduce a hydra run in such cases.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.7
- **Virtual environment type and version** : conda env
- **Operating system** : Linux

**Comment by Jasha10** [comment]
@noamgot this is a know limitation.
Have you seen the [Re-run](https://hydra.cc/docs/experimental/rerun/) feature?
(Note there is an error on that webpage:
it should be `_target_: hydra.experimental.callbacks.PickleJobInfoCallback` instead of `_target_: hydra.experimental.pickle_job_info_callback.PickleJobInfoCallback`)

```yaml
$ cat config.yaml
# config.yaml
defaults:
  - config_schema
  - _self_

x: 123
y: 456

hydra:
  callbacks:
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback
```
```
$ python main.py
[2023-07-20 09:32:45,374][hydra.experimental.callbacks.PickleJobInfoCallback][INFO] - Saving job configs in /home/homestar/dev/hydra/outputs/2023-07-20/09-32-45/.hydra/config.pickle
123
456
[2023-07-20 09:32:45,375][hydra.experimental.callbacks.PickleJobInfoCallback][INFO] - Saving job_return in /home/homestar/dev/hydra/outputs/2023-07-20/09-32-45/.hydra/job_return.pickle
```
```
$ python main.py --experimental-rerun outputs/2023-07-20/09-33-17/.hydra/config.pickle
/home/homestar/dev/hydra/hydra/main.py:24: UserWarning: Experimental rerun CLI option, other command line args are ignored.
  warnings.warn(msg, UserWarning)
123
456
```

**Comment by noamgot** [comment]
@Jasha10 No, I wasn't aware of that. thanks!
You said that it's a known limitation, but is there a plan to fix this in the future? Or do you plan to use the (currently experimental) rerun method you demonstrated?

**Comment by omry** [comment]
This is not a limitation.
Why are you converting to a primitive dictionary if you want to access using attribute (`cfg.x`)?
Just use the config directly.

**Comment by omry** [comment]
This is not a limitation.
You can use the config object as is without converting it and it would allow you to access `cfg.x`.

**Comment by noamgot** [comment]
@omry Maybe I should clarify myself: my goal here is to reproduce an existing run (e.g., for debugging), using the auto-generated config file (withing the `.hydra` directory). But using it directly (as demonstrated above) causes this behavior (as I pointed out, it does not contain the `defaults` section, and that's why the `to_object` method returns a dict rather than the desired object). Does it make sense now?

**Comment by asimukaye** [comment]
```
$ python main.py --experimental-rerun ./outputs/2023-10-16/09-33-37_/.hydra/job_return.pickle
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    run_feduciary()
  File "~/.conda/envs/fed_ml/lib/python3.10/site-packages/hydra/main.py", line 88, in decorated_main
    cfg = _get_rerun_conf(args.experimental_rerun, args.overrides)
  File "~/.conda/envs/fed_ml/lib/python3.10/site-packages/hydra/main.py", line 35, in _get_rerun_conf
    configure_log(config.hydra.job_logging, config.hydra.verbose)
AttributeError: 'JobReturn' object has no attribute 'hydra'
```

Hi, I am running into this error when I have custom hydra configurations defined alongside app configs in my master config file. Is this a limitation of experimental rerun or am I missing something here?

**Comment by omry** [comment]
Thanks for the report. This is a real limitation of replaying `.hydra/config.yaml` directly: the saved YAML is a value snapshot and does not preserve the structured config schema, so `OmegaConf.to_object()` returns a plain `dict`.

I opened #3248 to track a more Hydra-native rerun path: recompose from the original config and saved `.hydra/overrides.yaml`, then overlay the saved `.hydra/config.yaml` values. That preserves structured config/schema semantics while still using the saved run values.

Closing this as superseded by #3248.
