### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tbukic** [facebookresearch/hydra#2738]
# 🐛 Bug
## Checklist
- [x ] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
# example/test-hydra.py
import hydra
from attrs import define
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING, OmegaConf

@define
class Child2:
    xx: float | bool = 1.0

@define
class ChildConfig:
    name: str = "Child"
    c2: Child2 = MISSING

@define
class Config:
    ef: float = 8.0
    child: ChildConfig = MISSING

cs = ConfigStore.instance()
cs.store(name="root_config", node=Config)

@hydra.main(config_path="../config-float", config_name="config", version_base=None)
def my_app(cfg : Config) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

```
#config-float/config.yaml
defaults:
  - root_config
  - child: c1
  - _self_

ef: 5.0
```
```
#config-float/child/c1.yaml
defaults:
  - c2: c22

name: child
```

```
#config-float/child/c2/c22.yaml
xx: 2.0
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 263, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "test-hydra/.venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 542, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 358, in _map_merge
    expand(dest)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 342, in expand
    node._set_value(val)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 647, in _set_value
    raise e
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 644, in _set_value
    self._set_value_impl(value, flags)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 677, in _set_value_impl
    self.__setitem__(k, v)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 314, in __setitem__
    self._format_and_raise(key=key, value=value, cause=e)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 535, in _set_item_impl
    if self._get_root() is value._get_root():
  File "test-hydra/.venv/lib/python3.10/site-packages/omegaconf/base.py", line 289, in _get_root
    assert isinstance(self, Container)
AssertionError
```

## Expected Behavior
Config was supposed to be read. If you remove `| bool` from the definition of `Child2` everything works fine. It seems that this kind of union fails when the config tree is deep enough. This also fails when `Enum` is used instead of `bool`. Works fine with `None`.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.10.12
- **Virtual environment type and version** :  Poetry 1.5.1
- **Operating system** :  WSL2 Ubuntu 22.10

**Comment by Jasha10** [comment]
Thanks for the bug report, @tbukic. I am able to reproduce the `AssertionError` when I run the example you provided.

**Comment by omry** [comment]
This is already fixed in the Hydra 1.4 development line.

I verified the repro from this issue on current `main` with Hydra 1.4 and OmegaConf 2.4, and it now composes successfully.
