### ISSUE TITLE
[Bug] Built in resolvers unsupported with multiprocessing

### ISSUE THREAD

**Issue by teddykoker** [facebookresearch/hydra#2772]
# 🐛 Bug
## Description

Built in [resolvers provided by Hydra](https://hydra.cc/docs/configure_hydra/intro/#resolvers-provided-by-hydra), e.g. `hydra` and `now`, are not accessible when config is passed to a `multiprocessing.Process()`. 

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

`main.py`:
```python
import traceback
import multiprocessing

import hydra

def print_cfg(cfg):
    for key in cfg.keys():
        try:
            print(key, cfg[key])
        except Exception as e:
            traceback.print_exc()

@hydra.main(config_path="./", config_name="config.yaml", version_base=None)
def main(cfg):
    if cfg.processes == 0:
        print_cfg(cfg)

    else:
        for _ in range(cfg.processes):
            process = multiprocessing.Process(target=print_cfg, args=(cfg,))
            process.start()

        for _ in range(cfg.processes):
            process.join()

if __name__ == "__main__":
    main()
```

`config.yaml`:
```yaml
run_dir: ${hydra:run.dir}
time: ${now:%H-%M-%S}
processes: 0
```

Running `python main.py` prints the config as expected:

```
run_dir outputs/2023-10-18/12-34-43
time 12-34-43
processes 0
```

However, **running with a spawned process, `python main.py processes=1`, results in an error:**

```
Traceback (most recent call last):
  File "<user path>/main.py", line 9, in print_cfg
    print(key, cfg[key])
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 98, in _resolve_with_default
    resolved_node = self._maybe_resolve_interpolation(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "<user path>/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "<user path>/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "<user path>/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 702, in _evaluate_custom_resolver
    raise UnsupportedInterpolationType(
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type hydra
    full_key: run_dir
    object_type=dict
Traceback (most recent call last):
  File "<user path>/main.py", line 9, in print_cfg
    print(key, cfg[key])
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 98, in _resolve_with_default
    resolved_node = self._maybe_resolve_interpolation(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "<user path>/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "<user path>/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "<user path>/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "<user path>/venv/lib/python3.8/site-packages/omegaconf/base.py", line 702, in _evaluate_custom_resolver
    raise UnsupportedInterpolationType(
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type now
    full_key: time
    object_type=dict
processes 1
```

Note the `UnsupportedInterpolationType` error for both `now` and `hydra`.

## Expected Behavior

We would expect the resolvers to be available within the process, so running `python main.py processes=1` should simply print the config without error, as it does for `python main.py processes=0`.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.8.17
- **Virtual environment type and version** : Created with `python -m venv ./venv`
- **Operating system** :  Reproduced on Ubuntu and MacOS

## Additional context

A workaround is manually getting the problematic keys prior to spawning the process:

```python
# ...
        cfg.run_dir = cfg.run_dir
        cfg.time = cfg.time
        for _ in range(cfg.processes):
            process = multiprocessing.Process(target=print_cfg, args=(cfg,))
            process.start()
# ...
```

This is likely related to #2629, which was closed due to lack of a minimal reproducible example.

**Comment by odelalleau** [comment]
Looks like Hydra isn't properly initialized when spawning a new process, since we don't go through `hydra.main()` or any of the Compose API initialization functions ([doc](https://hydra.cc/docs/advanced/compose_api/)). Here's how you can get it to work (note that you also need to set the Hydra config manually, which is related to #2017):

```python
import traceback
import multiprocessing

import hydra
from hydra.core.hydra_config import HydraConfig
from omegaconf import OmegaConf


def print_cfg(cfg, hydra_cfg):
    hydra.initialize(version_base=None)
    HydraConfig.instance().set_config(OmegaConf.create({"hydra": hydra_cfg}))
    for key in cfg.keys():
        try:
            print(key, cfg[key])
        except Exception as e:
            traceback.print_exc()

@hydra.main(config_path="./", config_name="config_2772.yaml", version_base=None)
def main(cfg):
    if cfg.processes == 0:
        print_cfg(cfg)

    else:
        hydra_cfg = HydraConfig.get()
        for _ in range(cfg.processes):
            process = multiprocessing.Process(target=print_cfg, args=(cfg, hydra_cfg))
            process.start()

        for _ in range(cfg.processes):
            process.join()

if __name__ == "__main__":
    main()
```

One somewhat tricky point is the resolver cache: we can't ensure for instance that `${now:...}` will return the same timestamp for all processes, which might lead to potentially surprising results. Even if we were able to somehow initialize the resolver cache when spawning a new process, this won't work if the value hasn't been cached yet. So I don't think that's something we can really get working, and it's best to just resolve these settings manually (e.g. as in your workaround) before spawning a new process.

**Comment by teddykoker** [comment]
Thanks @odelalleau! This makes sense. If the processes don't have a HydraConfig set then the resolvers will not work, and your fix manually populates this within each process. I agree that instantiating the `${now:...}` values separately per process could be problematic; is there a reason to not just cache all of the values internally? 

In practice I have been recursively caching the entire config, as it can be difficult to have to modify the code itself if you want to use `${now:...}` somewhere new in the config:

```python
def cache_cfg(cfg: DictConfig):
    for k in cfg.keys():
        if isinstance(cfg[k], DictConfig):
            cache_cfg(cfg[k])
        else:
            cfg[k] = cfg[k]


@hydra.main(config_path="./", config_name="config.yaml", version_base=None)
def main(cfg):
    if cfg.processes == 0:
        print_cfg(cfg)

    else:
        cache_cfg(cfg)
        for _ in range(cfg.processes):
            process = multiprocessing.Process(target=print_cfg, args=(cfg,))
            process.start()

        for _ in range(cfg.processes):
            process.join()
```

I assume this wouldn't be ideal to do automatically if the user has a large config?

**Comment by odelalleau** [comment]
> I agree that instantiating the `${now:...}` values separately per process could be problematic; is there a reason to not just cache all of the values internally?

It's actually a feature of OmegaConf that config values may change dynamically, so we shouldn't cache everything by default. This can happen due to interpolations towards other nodes whose values are modified, or due to non-deterministic resolvers (which can be intended, for instance to sample random numbers).

> In practice I have been recursively caching the entire config (...)

You should probably call `OmegaConf.resolve(cfg)` which will do a slightly better job at this (including support for `ListConfig` in particular).

**Comment by teddykoker** [comment]
I see, thank you for the clarification! I guess the original issue falls under expected behavior?

**Comment by odelalleau** [comment]
> I see, thank you for the clarification! I guess the original issue falls under expected behavior?

It's expected given the current implementation, and it may be difficult to address it in a fully transparent way, but it should be possible to provide helper functions to simplify the proper communication of the config when spawning a new process. So I think it's worth leaving this issue open.

**Comment by omry** [comment]
Thanks for the clear report and reproduction.

This is not a supported way to parallelize Hydra applications. A config produced by Hydra can contain lazy interpolations that depend on process-local Hydra/OmegaConf state, such as registered resolvers, resolver caches, and `HydraConfig`. When that config is passed directly to a new `multiprocessing` process, the child process has not gone through Hydra's launcher/job lifecycle, so that state is not available.

The supported path for parallel execution is to use Hydra launchers and sweepers. Those go through the Hydra job lifecycle and set up the relevant runtime state for each job.

If you still want to manage multiprocessing directly, this becomes internal/unsupported integration work. The important pieces are:

- register Hydra's OmegaConf resolvers in the child process;
- copy the OmegaConf resolver cache if you need cached values such as `${now:...}` to remain consistent;
- populate `HydraConfig` in the child process if you need `${hydra:...}` interpolations.

<details>
<summary>Unsupported workaround sketch</summary>

```python
import copy
import multiprocessing

import hydra
from hydra.core.hydra_config import HydraConfig
from hydra.core.utils import setup_globals  # internal, unsupported
from omegaconf import DictConfig, OmegaConf


def worker(cfg: DictConfig, hydra_cfg: DictConfig, resolver_cache: dict) -> None:
    # Registers Hydra's OmegaConf resolvers in this child process.
    setup_globals()

    # Preserves cached resolver values from the parent, e.g. ${now:...}.
    OmegaConf.set_cache(cfg, resolver_cache)

    # Provides the backing Hydra runtime config for ${hydra:...}.
    HydraConfig.instance().set_config(OmegaConf.create({"hydra": hydra_cfg}))

    print(cfg.run_dir)  # ${hydra:run.dir}
    print(cfg.time)     # ${now:%H-%M-%S}


@hydra.main(version_base=None, config_path=".", config_name="config")
def main(cfg: DictConfig) -> None:
    # Force cached resolvers such as ${now:...} to resolve in the parent.
    _ = cfg.time

    # Copy the parent process HydraConfig for child-side ${hydra:...}.
    hydra_cfg = copy.deepcopy(HydraConfig.get())

    # Copy resolver cache so cached values remain consistent in the child.
    resolver_cache = copy.deepcopy(OmegaConf.get_cache(cfg))

    process = multiprocessing.Process(
        target=worker,
        args=(cfg, hydra_cfg, resolver_cache),
    )
    process.start()
    process.join()


if __name__ == "__main__":
    main()
```

</details>

This is intentionally not something I want to turn into a general Hydra helper right now. There are many gotchas around resolver state, caching semantics, nondeterministic resolvers, and process boundaries, and the benefit seems too narrow compared with using Hydra's launcher/sweeper mechanism.

Closing as not planned.
