### ISSUE TITLE
Getting error when requesting A100 GPU using submitit launcher[Bug]

### ISSUE THREAD

**Issue by qsimeon** [facebookresearch/hydra#2818]
Here is the hydra part of my config file where I define explicitly the launcher parameters to use:
```
hydra:
  # Hydra mode:
  #   - RUN: Run a single job
  #   - MULTIRUN: Run multiple jobs, each with different parameters
  #               defined by the sweeper. If running locally, multi-run
  #               runs the jobs serially. If in the cluster, multi-run
  #               submits the jobs in parallel.
  mode: MULTIRUN

  # Hydra job:
  #   - chdir: Change the working directory to the log directory.
  #            This is important for the pipeline to work.
  job:
    chdir: true

  # Hydra run:
  #   This is the RUN configuration.
  #   - dir: Directory to save the RUN results.
  run:
    dir: logs/hydra/${now:%Y_%m_%d_%H_%M_%S}

  # Hydra sweep:
  #   This is the MULTIRUN configuration.
  #   - dir: Directory to save the MULTIRUN results.
  #   - subdir: Subdirectory to save each run result.
  sweep:
    dir: logs/hydra/${now:%Y_%m_%d_%H_%M_%S}
    subdir: exp${hydra.job.num}

  # Hydra launcher:
  #   These are the launcher parameters for the SubmitIt plugin.
  #   Comment the partition if working locally.
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 1440  # Job timeout in minutes
    cpus_per_task: 1  # Number of CPU cores per task
    gpus_per_node: 1  # Number of GPUs per node
    tasks_per_node: 1  # Number of tasks to run on each node
    mem_gb: 32  # Memory required per node in GB
    nodes: 1  # Number of nodes to use
    partition: yanglab  #normal # Partition to submit to
    qos: null  # Quality of Service level
    comment: null  # Comment to pass to the job
    constraint: high-capacity  # Constraint specification
    exclude: dgx001, dgx002, node031, node034, node055  # Hosts to exclude
    gres: gpu:a100:1  # Generic resources to request
    cpus_per_gpu: null  # Number of CPUs per GPU
    gpus_per_task: null  # Number of GPUs per task
    mem_per_gpu: null  # Memory per GPU
    mem_per_cpu: null  # Memory per CPU
    account: null  # Account to charge
    signal_delay_s: 120  # Delay for sending signal before timeout
    max_num_timeout: 0  # Maximum number of timeouts
    additional_parameters: {}  # Additional parameters for Slurm
    array_parallelism: 256  # Max number of simultaneous jobs
    ```
    
    Calling my python app (main.py) produces this .sh file:
    ```
    #!/bin/bash

# Parameters
#SBATCH --array=0-1%2
#SBATCH --constraint=high-capacity
#SBATCH --cpus-per-task=1
#SBATCH --error=/net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/logs/hydra/2023_12_17_18_51_56/.submitit/%A_%a/%A_%a_0_log.err
#SBATCH --exclude='dgx001, dgx002, node031, node034, node055'
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:a100:1
#SBATCH --job-name=main
#SBATCH --mem=32GB
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --open-mode=append
#SBATCH --output=/net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/logs/hydra/2023_12_17_18_51_56/.submitit/%A_%a/%A_%a_0_log.out
#SBATCH --partition=yanglab
#SBATCH --signal=USR2@120
#SBATCH --time=1440
#SBATCH --wckey=submitit

# command
export SUBMITIT_EXECUTOR=slurm
srun --unbuffered --output /net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/logs/hydra/2023_12_17_18_51_56/.submitit/%A_%a/%A_%a_%t_log.out --error /net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/logs/hydra/2023_12_17_18_51_56/.submitit/%A_%a/%A_%a_%t_log.err /om2/user/qsimeon/miniconda3/envs/worm-graph/bin/python -u -m submitit.core._submit /net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/logs/hydra/2023_12_17_18_51_56/.submitit/%j
```

But I am getting this error:
```
(base) qsimeon@node112 /om2/user/qsimeon/worm-graph$ python main.py +experiment=default_multirun &
[2] 3056546
(base) qsimeon@node112 /om2/user/qsimeon/worm-graph$ CUDA device found.
[2023-12-17 18:51:56,766][HYDRA] Submitit 'slurm' sweep output dir : logs/hydra/2023_12_17_18_51_56
[2023-12-17 18:51:56,768][HYDRA]        #0 : experiment.seed=0 submodule.model.type=LinearRegression +experiment=default_multirun
[2023-12-17 18:51:56,774][HYDRA]        #1 : experiment.seed=0 submodule.model.type=FeatureFFNN +experiment=default_multirun
sbatch: error: Invalid GRES specification (with and without type identification)
subprocess.CalledProcessError: Command '['sbatch', '/net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/logs/hydra/2023_12_17_18_51_56/.submitit/submission_file_0f9891e42f1148279b539cfcf09c0084.sh']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/net/vast-storage/scratch/vast/yanglab/qsimeon/worm-graph/main.py", line 113, in <module>
    pipeline()
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 177, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 145, in launch
    jobs = executor.map_array(self, *zip(*job_params))
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/submitit/core/core.py", line 771, in map_array
    return self._internal_process_submissions(submissions)
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/submitit/auto/auto.py", line 218, in _internal_process_submissions
    return self._executor._internal_process_submissions(delayed_submissions)
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/submitit/slurm/slurm.py", line 336, in _internal_process_submissions
    first_job: core.Job[tp.Any] = array_ex._submit_command(self._submitit_command_str)
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/submitit/core/core.py", line 934, in _submit_command
    output = utils.CommandFunction(command_list, verbose=False)()  # explicit errors
  File "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/submitit/core/utils.py", line 354, in __call__
    raise FailedJobError(stderr) from subprocess_error
submitit.core.utils.FailedJobError: sbatch: error: Invalid GRES specification (with and without type identification)
```

**Comment by qsimeon** [comment]
I found that  setting`gpus_per_node: null` fixed my problem.
