### ISSUE TITLE
[Bug]  Unexpected Behavior when Using _target_: "load_pickle"

### ISSUE THREAD

**Issue by e-yi** [facebookresearch/hydra#2831]
# 🐛 Bug
## Description

When employing `hydra.instantiate()` to invoke a custom function responsible for reading a pickle file, it results in the `omegaconf.errors.KeyValidationError: Incompatible key type error`. I'm not quite familar with hydra, so I'm not entirely certain if this is an expected outcome or not. I just spent some time debugging my code and identified this issue.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```python
import pickle

from hydra.utils import instantiate
from omegaconf import OmegaConf


def load_pickle(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

class A:
    pass

a = A()

path = "./test.pkl"
with open(path, 'wb') as f:
    d = {a: None}
    pickle.dump(d, f)

cfg = OmegaConf.create({
    "test": {
        "_target_": "__main__.load_pickle",
        "path": "./test.pkl"
    }
})


print(OmegaConf.to_yaml(cfg))

obj = instantiate(cfg)
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "debug.py", line 33, in <module>
    obj = instantiate(cfg)
  File "X\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "X\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 366, in instantiate_node
    cfg[key] = instantiate_node(
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 314, in __setitem__
    self._format_and_raise(key=key, value=value, cause=e)
  File "X\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "X\lib\site-packages\omegaconf\_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "X\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "X\lib\site-packages\omegaconf\basecontainer.py", line 620, in _set_item_impl
    self._wrap_value_and_set(key, value, target_type_hint)
  File "X\lib\site-packages\omegaconf\basecontainer.py", line 628, in _wrap_value_and_set
    wrapped = _maybe_wrap(
  File "X\lib\site-packages\omegaconf\omegaconf.py", line 1105, in _maybe_wrap
    return _node_wrap(
  File "X\lib\site-packages\omegaconf\omegaconf.py", line 1004, in _node_wrap
    node = DictConfig(
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 111, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "X\lib\site-packages\omegaconf\_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "X\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 109, in __init__
    self._set_value(content, flags=flags)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 647, in _set_value
    raise e
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 644, in _set_value
    self._set_value_impl(value, flags)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 690, in _set_value_impl
    self.__setitem__(k, v)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 314, in __setitem__
    self._format_and_raise(key=key, value=value, cause=e)
  File "X\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "X\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "X\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 317, in __set_impl
    key = self._validate_and_normalize_key(key)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 275, in _validate_and_normalize_key
    return self._s_validate_and_normalize_key(self._metadata.key_type, key)
  File "X\lib\site-packages\omegaconf\dictconfig.py", line 282, in _s_validate_and_normalize_key
    raise KeyValidationError("Incompatible key type '$KEY_TYPE'")
omegaconf.errors.KeyValidationError: Incompatible key type 'A'
    full_key: 
    object_type=dict

Process finished with exit code 1
```

## Expected Behavior

Given that I'm using pickle, I assume I should be able to use any data type as a dictionary key, right?

## System information
- **Hydra Version** :  1.3.2
- **Python version** :  3.10.0
- **Virtual environment type and version** : 
- **Operating system** : windows

**Comment by odelalleau** [comment]
Did you mean to do instead
```
obj = instantiate(cfg.test)
```
?

**Comment by e-yi** [comment]
Thank you for reply, @odelalleau. Quite silly of me. What I need here is 
```python
cfg = OmegaConf.create({
   "_target_":"builtins.dict",   # add this line 
    "test": {
        "_target_": "__main__.load_pickle",
        "path": "./test.pkl"
    }
})
```

**Comment by e-yi** [comment]
Though the original case was a bit more complex, something like the following. But I get it now.
```python
import pickle

from hydra.utils import instantiate
from omegaconf import OmegaConf


def load_pickle(path):
    with open(path, 'rb') as f:
        return pickle.load(f)


class C:
    def __init__(self, **kwargs):
        self.kwargs = kwargs


class A:
    pass


a = A()

path = "./test.pkl"
with open(path, 'wb') as f:
    d = {a: None}
    pickle.dump(d, f)

cfg = OmegaConf.create({
    "_target_": "__main__.C",
    "x": {
        "test": {
            "_target_": "__main__.load_pickle",
            "path": "./test.pkl"
        }
    }
})

print(OmegaConf.to_yaml(cfg))

obj = instantiate(cfg)
```
