### ISSUE TITLE
[Bug] Failed to override configuration nodes in `--multirun`

### ISSUE THREAD

**Issue by acherstyx** [facebookresearch/hydra#2888]
# 🐛 Bug
## Description

As described in https://hydra.cc/docs/patterns/configuring_experiments, running experiments from a list of configs is great, but I'm facing some problems while trying to overwrite some config nodes. I cannot overwrite a config node which does not exist in the initial default list.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Taking the example at https://github.com/facebookresearch/hydra/tree/main/examples/patterns/configuring_experiments as initial:

Run `python3 my_app.py --multirun '+experiment=glob(*)' server.port=8081` yields the following outputs as expected:

```text
python3 my_app.py --multirun '+experiment=glob(*)' server.port=8081
[2024-04-09 07:40:09,161][HYDRA] Launching 2 jobs locally
[2024-04-09 07:40:09,161][HYDRA] 	#0 : +experiment=aplite server.port=8081
db:
  name: sqlite
server:
  name: apache
  port: 8081

[2024-04-09 07:40:09,324][HYDRA] 	#1 : +experiment=nglite server.port=8081
db:
  name: sqlite
server:
  name: nginx
  port: 8081
```

Then I made the following modification to the config:

1. Add a new config `conf/server/default.yaml`:

```yaml
name: default
# do not contains a `port` option
```

2. Change the default list in `conf/config.yaml`:

```
defaults:
  - db: mysql
  - server: default # apache -> default
```

Running the same command throws an error:

```
python3 my_app.py --multirun '+experiment=glob(*)' server.port=8081
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 390, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File ".../lib/python3.9/site-packages/omegaconf/omegaconf.py", line 741, in update
    root.__setattr__(last_key, value)
  File ".../lib/python3.9/site-packages/omegaconf/dictconfig.py", line 337, in __setattr__
    raise e
  File ".../lib/python3.9/site-packages/omegaconf/dictconfig.py", line 334, in __setattr__
    self.__set_impl(key, value)
  File ".../lib/python3.9/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File ".../lib/python3.9/site-packages/omegaconf/basecontainer.py", line 549, in _set_item_impl
    self._validate_set(key, value)
  File ".../lib/python3.9/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File ".../lib/python3.9/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File ".../lib/python3.9/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File ".../lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File ".../lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File ".../lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'port' is not in struct
    full_key: server.port
    object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../hydra/examples/patterns/configuring_experiments/my_app.py", line 13, in <module>
    my_app()
  File ".../lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File ".../lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File ".../lib/python3.9/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File ".../lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File ".../lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File ".../lib/python3.9/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File ".../lib/python3.9/site-packages/hydra/_internal/hydra.py", line 143, in multirun
    cfg = self.compose_config(
  File ".../lib/python3.9/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File ".../lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File ".../lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 276, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File ".../lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 392, in _apply_overrides_to_config
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: Could not override 'server.port'.
To append to your config use +server.port=8081
```

## Expected Behavior

In `conf/experiment/aplite.yaml` and `conf/experiment/nglite.yaml`,`apache` and `nginx` are set as server and the `server.port` is exists and should be able to be overridden.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.9
- **Virtual environment type and version** : 
- **Operating system** : linux

## Additional context
None

**Comment by odelalleau** [comment]
Looking into it, this is because sweep overrides are ignored when building the initial config before actually starting the multirun. So at this point it uses your `default` server which has no port (and thus can't be overridden on the command line).

I don't see an easy fix to this: unless I'm missing something, we need this initial config (because the sweeper relies on it), and we can't use e.g. the first sweep value to build this initial config (because we need the sweeper to provide it).

So the workaround to this issue is to make sure that your default config can be built with your (non-sweep) command-line overrides. In your specific example, you could e.g. either use `++server.port=8081` or define `port: ???` in `default`.

**Comment by omry** [comment]
Thanks for the report.

I agree with Olivier’s analysis above. This is expected multirun staging behavior rather than a Hydra bug.

Hydra needs to compose the initial sweep-level config before the sweeper can expand and launch the individual swept jobs. That means non-sweep command-line overrides such as `server.port=8081` are validated against the initial/default config, not against each later swept experiment config. In your example, the initial `server: default` config does not define `port`, so `server.port=8081` is rejected before the swept `apache` / `nginx` choices are applied.

The appropriate workarounds are the ones Olivier mentioned:

- use `++server.port=8081` if you intentionally want to create the field, or
- define `port: ???` in the default server config so the initial config declares that field.

Closing this as not a bug.
