### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by nxlitvin** [facebookresearch/hydra#2913]
# 🐛 Bug
## Description
`hydra.utils.instantiate` fails when trying to instantiate a class that uses a resolver that return a `list` in a package defined in the defaults list.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
`main.py`:
```py
import hydra.utils
from omegaconf import DictConfig, OmegaConf


@hydra.main(version_base="1.3", config_name="config.yaml", config_path=".")
def main(cfg: DictConfig):
    hydra.utils.instantiate(cfg.model)  # omegaconf.errors.UnsupportedValueType: Value 'list' is not a supported primitive type


if __name__ == "__main__":
    def _return_list():
        return [1, 2, 3]

    OmegaConf.register_new_resolver("return_list", _return_list)
    main()
```

`config.yaml`:
```yaml
defaults:
  - pkg: sub
  - _self_

model:
  obj: ${..pkg}


## Strangely, this would work just fine (without using defaults):
#model:
#  obj:
#    _target_: collections.defaultdict
#    x: ${return_list:}
```

`pkg/sub.yaml`:
```yaml
_target_: collections.defaultdict
x: ${return_list:}
```

** Stack trace/error message **
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ml/.config/JetBrains/PyCharmCE2024.1/scratches/scratch_121.py", line 15, in <module>
    main()
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ml/.config/JetBrains/PyCharmCE2024.1/scratches/scratch_121.py", line 7, in main
    hydra.utils.instantiate(cfg.model)  # omegaconf.errors.UnsupportedValueType: Value 'list' is not a supported primitive type
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 220, in instantiate
    OmegaConf.resolve(config)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 785, in resolve
    omegaconf._impl._resolve(cfg)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/_impl.py", line 40, in _resolve
    _resolve_container_value(cfg, k)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/_impl.py", line 19, in _resolve_container_value
    _resolve(resolved)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/_impl.py", line 40, in _resolve
    _resolve_container_value(cfg, k)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/_impl.py", line 23, in _resolve_container_value
    node._set_value(_get_value(resolved))
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/nodes.py", line 46, in _set_value
    self._val = self.validate_and_convert(value)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/nodes.py", line 76, in validate_and_convert
    return self._validate_and_convert_impl(value)
  File "/home/ml/venvs/venv310_20240311/lib/python3.10/site-packages/omegaconf/nodes.py", line 154, in _validate_and_convert_impl
    raise UnsupportedValueType(
omegaconf.errors.UnsupportedValueType: Value 'list' is not a supported primitive type
```

## Expected Behavior
No crash.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.10.12
- **Virtual environment type and version** : pip 22.0.2
- **Operating system** : Ubuntu 22.04 LTS

## Additional context
-

**Comment by omry** [comment]
Instantiates operate on the composed config is is not sensitive to the defaults list.
Can you check see if there is a difference between your config objects in the two cases?

**Comment by omry** [comment]
Also, please give the bug a proper title.

**Comment by nxlitvin** [comment]
The composed config is:
```
{'pkg': {'_target_': 'collections.defaultdict', 'x': '${return_list:}'}, 'model': {'obj': '${..pkg}'}}
```

Or in yaml style:
```
pkg:
  _target_: collections.defaultdict
  x: ${return_list:}
model:
  obj: ${..pkg}
```

Fixed the title, sorry about that.

**Comment by mamaj** [comment]
+1 this
In my case, when a resolver returns a list I get  
`omegaconf.errors.UnsupportedValueType: Value 'list' is not a supported primitive type`
only with `-c job --ressolve`.

hydra version 1.3.2

**Comment by omry** [comment]
Thanks for the good repro, and sorry for the long delay.

I reproduced this on Hydra 1.3.2 with the corresponding OmegaConf 2.3 line. I also checked the same repro on current `main`, which is using the upcoming Hydra 1.4 / OmegaConf 2.4 line, and it no longer reproduces there.

So I am closing this as fixed by the upcoming 1.4 release line.
