### ISSUE TITLE
[Bug] Naming multi-opbjective experiment `optuna.py` causes failure to import optuna samplers  

### ISSUE THREAD

**Issue by m-yaghini** [facebookresearch/hydra#2924]
# 🐛 Bug
## Description
Naming multi-opbjective experiment `optuna.py` causes failure to import optuna samplers  

## Checklist
- [x ] I checked on the latest version of Hydra
- [NA] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Clone repo. Rename [`multi-objective.py`](https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_optuna_sweeper/example/multi-objective.py) to 
`optuna.py` and run the example as instructed in the docs:
```bash
>> python optuna.py --multirun
```

** Minimal Code/Config snippet to reproduce **
As above

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1319, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'optuna.samplers'; 'optuna' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'optuna.samplers.NSGAIISampler':
ModuleNotFoundError("No module named 'optuna.samplers'; 'optuna' is not a package")
Are you sure that 'samplers' is importable from module 'optuna'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mohammad/work/hydra/plugins/hydra_optuna_sweeper/example/optuna.py", line 19, in <module>
    binh_and_korn()
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
            ^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 153, in multirun
    sweeper = Plugins.instance().instantiate_sweeper(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/core/plugins.py", line 138, in instantiate_sweeper
    sweeper = self._instantiate(config.hydra.sweeper)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/core/plugins.py", line 112, in _instantiate
    plugin = instantiate(config=config, _target_=clazz)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammad/work/fair_dp_sgd/fair-dp-sgd/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'optuna.samplers.NSGAIISampler', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: hydra.sweeper.sampler
```

## Expected Behavior

Any filename including `optuna.py` should work; or at least a meaningful error/warning should be shown. 

## System information
- **Hydra Version** :  
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** : 

## Additional context
This is clearly a trivial issue. The cause is that the local file `optuna.py` is considered a  module and python tries to import the sampler from this file.  But the yaml setup abstracts this process. A warning would be appreciated.

**Comment by omry** [comment]
This is not an issue we can fix. By naming your file optuna it's likely that you are shadowing the optuna module.
