### ISSUE TITLE
[Bug]RQ Launcher Plugin under Python 3.11 got ValueError: mutable default for field enqueue is not allowed: use default_factory

### ISSUE THREAD

**Issue by twoyoung** [facebookresearch/hydra#2939]
# 🐛 Bug
## Description
Under the environment of Python 3.11, integrating RQ Launcher Plugin reports `ValueError: mutable default <class 'hydra_plugins.hydra_rq_launcher.config.EnqueueConf'> for field enqueue is not allowed: use default_factory`

## Checklist

- [*] I checked on the latest version of Hydra
yes

- [*] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

with the example code under Python 3.11: https://github.com/facebookresearch/hydra/tree/main/plugins/hydra_rq_launcher/example

** Stack trace/error message **
```
~> python -m my_app                      (py311) 
Traceback (most recent call last):
  File "/csse/users/ubuntu/miniconda3/envs/py311/bin/my_app", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/_internal/utils.py", line 337, in _run_hydra
    search_path = create_automatic_config_search_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/_internal/utils.py", line 190, in create_automatic_config_search_path
    return create_config_search_path(search_path_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/_internal/utils.py", line 203, in create_config_search_path
    search_path_plugins = Plugins.instance().discover(SearchPathPlugin)
                          ^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/core/plugins.py", line 46, in instance
    ret = Singleton.instance(Plugins, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/core/singleton.py", line 17, in instance
    return cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/core/singleton.py", line 13, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/core/plugins.py", line 54, in __init__
    self._initialize()
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/core/plugins.py", line 71, in _initialize
    scanned_plugins, self.stats = self._scan_all_plugins(modules=top_level)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra/core/plugins.py", line 197, in _scan_all_plugins
    spec.loader.exec_module(loaded_mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/hydra_plugins/hydra_rq_launcher/config.py", line 45, in <module>
    @dataclass
     ^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csse/users/ubuntu/miniconda3/envs/py311/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra_plugins.hydra_rq_launcher.config.EnqueueConf'> for field enqueue is not allowed: use default_factory
```

## System information
- **Hydra Version** :  1.3.2
- **Python version** :  3.11
- **Operating system** :  Linux

**Comment by omry** [comment]
Thanks for reporting this. This is fixed on `main` and will be published as part of an upcoming dev release.
