### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghaith-mq** [facebookresearch/hydra#2989]
I am getting this error even if I remove all params from  the sweeper. Tried unistalling hydra and reinstalling it again, but didn't work.
```
[2024-11-18 21:25:24,018][HYDRA] 	#0 : model.litmodule.loss=SIGLIP datamodule.seed=4224422 launcher=icb
Error executing job with overrides: ['model.litmodule.loss=SIGLIP', 'datamodule.seed=4224422', 'launcher=icb']
Traceback (most recent call last):
 File "/ictstr01/home/icb/ghaith.mqawass/projs/phenoclip/experiments/pretrain/./experiment.py", line 85, in <module>
  main()
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
  _run_hydra(
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
  _run_app(
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/utils.py", line 465, in _run_app
  run_and_report(
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
  raise ex
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
  return func()
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
  lambda: hydra.multirun(
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
  ret = sweeper.sweep(arguments=task_overrides)
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 181, in sweep
  _ = r.return_value
 File "/home/icb/ghaith.mqawass/miniconda3/envs/gen/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
  raise self._return_value
TypeError
```
I tried uninstalling and reinstalling hydra but it didn't work.

**Comment by omry** [comment]
Thanks for reporting this.

I am going to close this as incomplete because there is not enough information here to diagnose a Hydra bug. This does not include the information requested by the bug report template: Hydra version, Python version, environment/OS information, expected behavior, and a minimal code/config reproduction.

The traceback above only shows Hydra re-raising the failed job result later; it does not show the original failure that would allow me to diagnose a Hydra issue.

Please feel free to reopen with a complete bug report if you can provide enough information to investigate, ideally with a minimal Hydra reproduction that does not depend on your private application setup.
