### ISSUE TITLE
Improve error on incorrect command line argument or composition problems

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#349]
This is very verbose:
```
$ python examples/tutorial/5_composition/my_app.py foo=bar
Traceback (most recent call last):
  File "examples/tutorial/5_composition/my_app.py", line 11, in <module>
    my_app()
  File "c:\users\omry\pycharmprojects\hydra\hydra\main.py", line 31, in decorated_main
    strict=strict,
  File "c:\users\omry\pycharmprojects\hydra\hydra\_internal\utils.py", line 194, in run_hydra
    overrides=args.overrides,
  File "c:\users\omry\pycharmprojects\hydra\hydra\_internal\hydra.py", line 96, in run
    config_file=config_file, overrides=overrides, with_log_configuration=True
  File "c:\users\omry\pycharmprojects\hydra\hydra\_internal\hydra.py", line 393, in compose_config
    config_file=config_file, overrides=overrides, strict=strict
  File "c:\users\omry\pycharmprojects\hydra\hydra\_internal\config_loader.py", line 93, in load_configuration
    cfg.merge_with_dotlist(remaining_overrides)
  File "C:\tools\miniconda3\lib\site-packages\omegaconf\basecontainer.py", line 154, in merge_with_dotlist
    self.update_node(key, value)
  File "C:\tools\miniconda3\lib\site-packages\omegaconf\basecontainer.py", line 179, in update_node
    root[last] = value
  File "C:\tools\miniconda3\lib\site-packages\omegaconf\dictconfig.py", line 100, in __setitem__
    self._validate_access(key)
  File "C:\tools\miniconda3\lib\site-packages\omegaconf\dictconfig.py", line 302, in _validate_access
    raise AttributeError(msg)
AttributeError: Accessing unknown key in a struct : foo
```

**Comment by omry** [comment]
cc @chaton

**Comment by mdrofiahmed** [comment]
Nice

**Comment by omry** [comment]
## Improved form
### Command line errors:
```
$ python examples/tutorial/5_composition/my_app.py db.foo=bar
Error merging overrides
Key 'foo' in not in struct
        full_key: db.foo
        reference_type=Optional[Dict[Any, Any]]
        object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace
```
### Errors merging a specific config file:
```
$ python examples/structured_configs_tutorial/5_structured_config_schema/my_app.py 
Error merging database=mysql
Value 'dads' could not be converted to Integer
        full_key: db.port
        reference_type=Optional[MySQLConfig]
        object_type=MySQLConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace
```
