### ISSUE TITLE
[Bug] Cannot override default constructor parameters without duplicating them in config

### ISSUE THREAD

**Issue by erip** [facebookresearch/hydra#454]
# 🐛 Bug

When using `hydra.utils.instantiate`, if the class to be constructed has default params it cannot be overridden unless the params are duplicated in config:

## To reproduce

```python
# app/my_class.py
class MyClass:
    def __init__(self, a: int=42, b: str="hello"):
        self.a = a
        self.b = b
```

```yaml
# conf/conf.yaml
model:
    class: app.my_class.MyClass
    params:
```

# `my_app.py`
```python
#!/usr/bin/env python3

import hydra
from omegaconf import DictConfig

@hydra.main(config_path="conf/conf.yaml")
def my_app(cfg: DictConfig) -> None:
    my_class = hydra.utils.instantiate(cfg.model)
    print(my_class.a, my_class.b)

if __name__ == "__main__":
    my_app()
```

** Stack trace/error message **
```
$ ./my_app.py model.params.a=1
Traceback (most recent call last):
  File "./my_app.py", line 12, in <module>
    my_app()
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 79, in run
    config_file=config_file, overrides=overrides, with_log_configuration=True
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 343, in compose_config
    config_file=config_file, overrides=overrides, strict=strict
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/hydra/_internal/config_loader.py", line 82, in load_configuration
    cfg.merge_with_dotlist(remaining_overrides)
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/omegaconf/config.py", line 278, in merge_with_dotlist
    self.update(key, value)
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/omegaconf/config.py", line 299, in update
    root[last] = value
  File "/Users/erip/miniconda3/envs/hydra/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 41, in __setitem__
    "Accessing unknown key in a struct : {}".format(self.get_full_key(key))
KeyError: 'Accessing unknown key in a struct : model.params.a'
```

## System information
- **Hydra Version** :  `hydra-core==0.11.3`
- **Python version** :  Python 3.6.10 :: Anaconda, Inc.
- **Virtual environment type and version** : conda version : 4.8.2
- **Operating system** : OS X

## Additional context

Removing `model.params` yields a similar issue.

**Comment by omry** [comment]
This is actually expected.
Your config is in strict mode (see the docs), and you are trying to add a field that is not defined there.

Try this:
```yaml
model:
    class: app.my_class.MyClass
    params:
      a: ???
```

`???` is "mandatory missing" values. see [this](https://omegaconf.readthedocs.io/en/latest/usage.html#mandatory-values).

Another option is to set the value to null (`a: null`), and at the case Python would get None for it if it's not specified and you can apply your own logic.

**Comment by omry** [comment]
I am not sure how those two options would interact with your default values.
Generally my position is that those code default values should be minimized and be in config instead (that people can freely override).

**Comment by omry** [comment]
This can be used to take function default value into account:
https://stackoverflow.com/questions/12627118/get-a-function-arguments-default-value

PR welcome (but keep in mind that this will have to go to master).

**Comment by omry** [comment]
@erip, Looks like this is already working correctly on master (see tests in PR).

Can you try on master and see if you get a repro?
