### ISSUE TITLE
Use of required fields leads to RecursionError

### ISSUE THREAD

**Issue by cmnrd** [facebookresearch/hydra#493]
# 🐛 Bug

## To reproduce

I have a conf directory that contains `conf/default.yaml`:
```
defaults:
  - x: default

out_file: "${x.name}.txt"
```

and `conf/x/default.yaml`:
```
x:
  name: ???
```

The python script I am running is this one: `test.py`
```
import hydra

@hydra.main("conf/default.yaml")
def main(cfg):
    with open(cfg["out_file"], "w") as f:
        f.write("Hello Hydra!")

if __name__ == "__main__":
    main()
```

Running `python test.py -c job` gives:
``` 
out_file: ${x.name}.txt
x:
  name: ???
``` 

** Stack trace/error message **

Running `python test.py` produces a RecursionError exception:
```
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 141, in __contains__
    self._resolve_with_default(key, node, None)
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/config.py", line 151, in _resolve_with_default
    raise MissingMandatoryValue(self.get_full_key(key))
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/config.py", line 168, in get_full_key
    for parent_key, v in parent.items():
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 185, in items
    return MyItems(self)
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 156, in __init__
    self.iterator = iter(m)
RecursionError: maximum recursion depth exceeded!
```

Running `python test.py x.name=test -c job` also produces a RecursionError exception:
```
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/config.py", line 168, in get_full_key
    for parent_key, v in parent.items():
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 162, in __next__
    k, v = self._next_pair()
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 177, in _next_pair
    v = self.map.get(k)
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 99, in get
    default_value=default_value,
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/config.py", line 153, in _resolve_with_default
    return self._resolve_single(value) if isinstance(value, str) else value
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/site-packages/omegaconf/config.py", line 479, in _resolve_single
    match_list = list(re.finditer(key_prefix + legal_characters, value))
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/re.py", line 230, in finditer
    return _compile(pattern, flags).finditer(string)
  File "/home/cmenard/virtualenvs/hydra/lib/python3.7/re.py", line 273, in _compile
    if isinstance(flags, RegexFlag):
RecursionError: maximum recursion depth exceeded while calling a Python object
```
Note that I shortened the trace and only included the last lines since they are very long due to the recursion.

## Expected Behavior

Running `python test.py` is expected to fail as `x.name` is not set. I would expect, however, a clear error message instead of RecursionError. Moreover, I expect the script to work when `x.name` is set via command line parameter, but both `python test.py x.name=test` and `python test.py x.name=test -c job` fail with an RecursionError.

## System information
- **Hydra Version** :  0.11.3
- **Python version** : 3.7
- **Virtual environment type and version** : virtualenv 16.1.0
- **Operating system** : Manjaro Linux

**Comment by omry** [comment]
Thanks for reporting.
This is already addressed in the master branch which is not yet released.

Can you try to use that instead?

**Comment by omry** [comment]
```
(hydra38) omry@omry-fedora:~/dev/tmp$ cat main.py 
import hydra

@hydra.main("config.yaml")
def main(cfg):
    print(cfg.pretty())
    cfg.out_file

if __name__ == "__main__":
    main()
(hydra38) omry@omry-fedora:~/dev/tmp$ cat config.yaml 
out_file: ${x.name}.txt
x:
  name: ???

(hydra38) omry@omry-fedora:~/dev/tmp$ python main.py 
out_file: ${x.name}.txt
x:
  name: ???

Traceback (most recent call last):
...
omegaconf.errors.MissingMandatoryValue: x.name
```

**Comment by cmnrd** [comment]
That works indeed. Thanks! I am looking forward to the next release then!

**Comment by omry** [comment]
Feel free to try to use it. I would actually appreciate any early feedback.
I am still working on some new features and a lot of internal changes, but master is always stable and passing tests.
