### ISSUE TITLE
[Bug] config access errors in the code should include stack trace

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#647]
When the user is making a config access error in the code the stack trace should include the offending file+line.

**Comment by omry** [comment]
Application with a runtime error:
```python
def foo(cfg: DictConfig) -> None:
    cfg.foo = "bar" # this does not exist in the config

@hydra.main(config_name="config")
def my_app(cfg: DictConfig) -> None:
    foo(cfg)


if __name__ == "__main__":
    my_app()
```

Running this only shows the interesting stack frames:
```text
$ python my_app.py 
Traceback (most recent call last):
  File "my_app.py", line 13, in my_app
    foo(cfg)
  File "my_app.py", line 8, in foo
    cfg.foo = "bar"  # does not exist in the config
omegaconf.errors.ConfigAttributeError: Key 'foo' is not in struct
        full_key: foo
        reference_type=Optional[Dict[Any, Any]]
        object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

You can still get the whole thing if you want to dig deeper:
```text
$ HYDRA_FULL_ERROR=1 python my_app.py 
Traceback (most recent call last):
  File "/home/omry/dev/hydra/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/omry/dev/hydra/hydra/_internal/utils.py", line 333, in <lambda>
    overrides=args.overrides,
  File "/home/omry/dev/hydra/hydra/_internal/hydra.py", line 109, in run
    job_subdir_key=None,
  File "/home/omry/dev/hydra/hydra/core/utils.py", line 123, in run_job
    ret.return_value = task_function(task_cfg)
  File "my_app.py", line 13, in my_app
    foo(cfg)
  File "my_app.py", line 8, in foo
    cfg.foo = "bar"  # does not exist in the config
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 295, in __setattr__
    raise e
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 292, in __setattr__
    self.__set_impl(key, value)
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 276, in __set_impl
    self._set_item_impl(key, value)
  File "/home/omry/dev/omegaconf/omegaconf/basecontainer.py", line 366, in _set_item_impl
    self._validate_set(key, value)
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 135, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 168, in _validate_set_merge_impl
    target = self._get_node(key)
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 397, in _get_node
    self._validate_get(key)
  File "/home/omry/dev/omegaconf/omegaconf/dictconfig.py", line 128, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/omry/dev/omegaconf/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/omry/dev/omegaconf/omegaconf/_utils.py", line 669, in format_and_raise
    raise_(ex, cause)
  File "/home/omry/dev/omegaconf/omegaconf/_utils.py", line 594, in raise_
    raise ex
omegaconf.errors.ConfigAttributeError: Key 'foo' is not in struct
        full_key: foo
        reference_type=Optional[Dict[Any, Any]]
        object_type=dict
```

**Comment by omry** [comment]
I solved it by committing a fix to the repository.

**Comment by wangxiao5791509** [comment]
@omry   I just delete that line: print(args.pretty()) .... and the code runs smoothly ... 

[](https://github.com/qq456cvb/Point-Transformers/blob/676d18a0cb77b79de3a11e95966f5f3274c546ee/train_cls.py#L52)

**Comment by wangxiao5791509** [comment]
https://github.com/qq456cvb/Point-Transformers/blob/676d18a0cb77b79de3a11e95966f5f3274c546ee/train_cls.py#L52

**Comment by omry** [comment]
Which proves that your report has **nothing at all** to do with this issue.
`cfg.pretty()` was deprecated in OmegaConf 2.0 and removed in OmegaConf 2.1.
Use `OmegaConf.to_yaml(cfg)` instead.

**Comment by wangxiao5791509** [comment]
@omry  Yes. you are right. Thanks for your feedback.
