### ISSUE TITLE
[Bug] Crash when using postponed evaluation of annotations

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#770]
# 🐛 Bug

Structured configs seem not to work with the upcoming postponed evaluation of annotations (https://www.python.org/dev/peps/pep-0563/) which will be the default in Python 3.10.

Obviously not really a problem yet but flagging it now as a FYI.

## To reproduce

** Minimal Code/Config snippet to reproduce **

Start from https://github.com/facebookresearch/hydra/blob/master/examples/tutorials/structured_configs/1_minimal/my_app.py and add on the first line:

```
from __future__ import annotations
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    cs.store(name="config", node=MySQLConfig)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/hydra/core/config_store.py", line 85, in store
    cfg = OmegaConf.structured(node)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 134, in structured
    return OmegaConf.create(obj, parent)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 171, in create
    return OmegaConf._create_impl(obj=obj, parent=parent)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 220, in _create_impl
    element_type=element_type,
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 74, in __init__
    self._set_value(content)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 546, in _set_value
    data = get_structured_config_data(value)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/_utils.py", line 258, in get_structured_config_data
    return get_dataclass_data(obj)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/_utils.py", line 202, in get_dataclass_data
    ref_type=type_, is_optional=is_optional, key=name, value=value, parent=None,
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 681, in _maybe_wrap
    key=key,
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 641, in _node_wrap
    elif issubclass(type_, Enum):
TypeError: issubclass() arg 1 must be a class
```

## Expected Behavior
Same as without the added import.

## System information
- **Hydra Version** :  1.0.0rc2
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Linux

**Comment by odelalleau** [comment]
Ah shoot, this is again an `OmegaConf` issue, will move it there...

**Comment by odelalleau** [comment]
Moved to https://github.com/omry/omegaconf/issues/303
