### ISSUE TITLE
[Bug] Can't use overrides containing an asterisk

### ISSUE THREAD

**Issue by greaber** [facebookresearch/hydra#798]
# 🐛 Bug

It seems like it is not possible to use an override that contains an asterisk.  The lexer generates a token recognition error.  I didn't dig into the grammar to understand why though.

## To reproduce
```
import hydra

@hydra.main()
def foo():
    pass

foo()
```
```
$ python test.py +bar=\*
```

** Stack trace/error message **
```
$ python test.py +bar=\*

  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/atn/LexerATNSimulator.py", line 99, in match
    return self.execATN(input, dfa.s0)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/atn/LexerATNSimulator.py", line 191, in execATN
    return self.failOrAccept(self.prevAccept, input, s.configs, t)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/atn/LexerATNSimulator.py", line 250, in failOrAccept
    raise LexerNoViableAltException(self.recog, input, self.startIndex, reach)
antlr4.error.Errors.LexerNoViableAltException: LexerNoViableAltException('*')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 559, in parse_overrides
    parsed = self.parse_rule(override, "override")
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 544, in parse_rule
    tree = getattr(parser, rule)()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/grammar/gen/OverrideParser.py", line 229, in override
    self.match(OverrideParser.T__0)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/Parser.py", line 116, in match
    self.consume()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/Parser.py", line 340, in consume
    self.getInputStream().consume()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/BufferedTokenStream.py", line 99, in consume
    if self.sync(self.index + 1):
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/BufferedTokenStream.py", line 111, in sync
    fetched = self.fetch(n)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/BufferedTokenStream.py", line 123, in fetch
    t = self.tokenSource.nextToken()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/Lexer.py", line 130, in nextToken
    self.notifyListeners(e)             # report error
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/Lexer.py", line 285, in notifyListeners
    listener.syntaxError(self, None, self._tokenStartLine, self._tokenStartColumn, msg, e)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/antlr4/error/ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 485, in syntaxError
    raise HydraException(msg)
hydra.errors.HydraException: token recognition error at: '*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 336, in <lambda>
    overrides=args.overrides,
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 102, in run
    run_mode=RunMode.RUN,
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    from_shell=from_shell,
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 174, in _load_configuration
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home/grant/miniconda3/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 562, in parse_overrides
    f"Error parsing override '{override}' : {e}"
hydra.errors.HydraException: Error parsing override '+bar=*' : token recognition error at: '*'
See https://hydra.cc/docs/next/advanced/command_line_syntax for details
```

## System information
- **Hydra Version** :  latest dev version
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by omry** [comment]
Thanks for reporting.
1. There is an issue with the error itself.
2. For now, you can quote the *.
See example below. Note that the shell interprets the outer quotes:
```shell
"+foo='*'"
```

**Comment by omry** [comment]
@greaber:
I am improving the error reporting but would like to know more about the use case:

```
omry@Coronadev:~/dev/hydra$ python examples/tutorials/basic/your_first_hydra_app/1_simple_cli/my_app.py +bar=*
LexerNoViableAltException: +bar=*
                                ^
See https://hydra.cc/docs/next/advanced/command_line_syntax for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

There are multiple characters that are intentionally reserved for future use in the grammar, * is one of them (A possible use case is to use * as an indicator in sweep for "all config group options".
The decision to allow individual special characters to the grammar is done on a case by case basis.
The escape hatch to allow those characters anyway is quoting as I explained above. A quoted string can contain all characters.

Can you give more context about the use case for *?

**Comment by greaber** [comment]
In one of our models, you tell it which files to process (for inference) by supplying a string that it uses as a glob expression.

**Comment by omry** [comment]
Alright. I will add *, but there is a small (under 10%) chance that I will have to remove it in the future if it conflicts with some other features.
If that happens, the alternative would be to quote it as I shown you above.

**Comment by greaber** [comment]
All right, thanks.
