### ISSUE TITLE
[Bug] instatinate hides root cause of an import error

### ISSUE THREAD

**Issue by shaolinkhoa** [facebookresearch/hydra#799]
# 🐛 Bug

Hydra rc1 and rc2 scan all the error in code and raise an error but it doesn't a correct error.

## To reproduce
**Minimal Code/Config snippet to reproduce**
Folder structure:
`code/example_code.py`
```
import pytorch_lightning.metrics.functional as plm

class sample_fucntion:
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def run(self):
        print(self.a)
        print(self.b)
        print(self.c)
```

`conf/code/code_python.yaml`
```yaml
# @package _group_
name: sample_fucntion
target: code.example_code.sample_fucntion
params:
  a: 1
  b: 2
  c: 3
```
`conf/config.yaml`
```yaml
defaults:
  - code: code_python
```
`my_app.py`

```python
import hydra
from omegaconf import DictConfig

@hydra.main(config_path="conf", config_name="config")
def my_app(cfg: DictConfig) -> None:

    python_class = hydra.utils.instantiate(cfg.code)
    python_class.run()

if __name__ == "__main__":
    my_app()
```

**Stack trace/error message**
My environment doesn't have `pytorch_lightning`. If I use `import pytorch_lightning.metrics.functional as plm` in `code/example_code.py`
It will generate the error
```
Traceback (most recent call last):
  File "C:\Users\khoa\Anaconda3\envs\py3\lib\site-packages\hydra\utils.py", line 33, in call
    type_or_callable = _locate(cls)
  File "C:\Users\khoa\Anaconda3\envs\py3\lib\site-packages\hydra\_internal\utils.py", line 520, in _locate
    raise ImportError(f"Could not locate '{path}'")
ImportError: Could not locate 'code.example_code.sample_fucntion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "my_app.py", line 15, in my_app
    python_class = hydra.utils.instantiate(cfg.code)
  File "C:\Users\khoa\Anaconda3\envs\py3\lib\site-packages\hydra\utils.py", line 40, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'code.example_code.sample_fucntion' : Could not locate 'code.example_code.sample_fucntion'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.```

##Expected Behavior
It should show I'm missing the `pytorch_lightning` package, instead of the error above

## System information
- **Hydra Version** :  rc2 and previous
- **Python version** : 3.7
- **Operating system** : linux

**Comment by shagunsodhani** [comment]
* `codes` should be a module. Add `__init__.py`

* New Error (with `HYDRA_FULL_ERROR=0`):

```(hydra38) (mtrl) ➜  hydra_debug HYDRA_FULL_ERROR=0 python my_app.py
Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 523, in _locate
    import_module(mod)
  File "/private/home/sodhani/.conda/envs/hydra38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/home/sodhani/hydra_debug/code/example_code.py", line 1, in <module>
    import pytorch_lightning.metrics.functional as plm
ModuleNotFoundError: No module named 'pytorch_lightning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/utils.py", line 33, in call
    type_or_callable = _locate(cls)
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 525, in _locate
    raise ImportError(
ImportError: Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "my_app.py", line 7, in my_app
    python_class = hydra.utils.instantiate(cfg.code)
  File "/private/home/sodhani/projects/hydra/hydra/utils.py", line 40, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'code.example_code.sample_fucntion' : Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

* New Error (with `HYDRA_FULL_ERROR=1`):

```
(hydra38) (mtrl) ➜  hydra_debug HYDRA_FULL_ERROR=1 python my_app.py
Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 523, in _locate
    import_module(mod)
  File "/private/home/sodhani/.conda/envs/hydra38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/home/sodhani/hydra_debug/code/example_code.py", line 1, in <module>
    import pytorch_lightning.metrics.functional as plm
ModuleNotFoundError: No module named 'pytorch_lightning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/utils.py", line 33, in call
    type_or_callable = _locate(cls)
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 525, in _locate
    raise ImportError(
ImportError: Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 333, in <lambda>
    lambda: hydra.run(
  File "/private/home/sodhani/projects/hydra/hydra/_internal/hydra.py", line 105, in run
    return run_job(
  File "/private/home/sodhani/projects/hydra/hydra/core/utils.py", line 123, in run_job
    ret.return_value = task_function(task_cfg)
  File "my_app.py", line 7, in my_app
    python_class = hydra.utils.instantiate(cfg.code)
  File "/private/home/sodhani/projects/hydra/hydra/utils.py", line 40, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'code.example_code.sample_fucntion' : Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'
```

**Comment by Yevgnen** [comment]
@shagunsodhani How about if `code` is single `.py` instead of  a directory?

**Comment by Jasha10** [comment]
@Yevgnen it should still work.
