### ISSUE TITLE
[Bug] Submitit Launcher throws error for `cls` argument

### ISSUE THREAD

**Issue by jgbos** [facebookresearch/hydra#803]
# 🐛 Bug

PyPI version is at `1.0.0rc3` and therefore fails with latest hydra-core rc2 release.

## To reproduce

Run 

`pip install hydra-core --pre`

and then

`pip install hydra-submitit-launcher --pre`

Then try to run an example, you get the following error:

```bash
Traceback (most recent call last):
  File "my_app.py", line 9, in <module>
    my_app()
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/main.py", line 29, in decorated_main
    args = get_args_parser()
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/_internal/utils.py", line 436, in get_args_parser
    help=f"Install or Uninstall shell completion:\n{_get_completion_help()}",
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/_internal/utils.py", line 384, in _get_completion_help
    completion_plugins = Plugins.instance().discover(CompletionPlugin)
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/core/plugins.py", line 35, in instance
    ret = Singleton.instance(Plugins, *args, **kwargs)
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/core/singleton.py", line 14, in instance
    return cls(*args, **kwargs)
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/core/singleton.py", line 10, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/core/plugins.py", line 43, in __init__
    self._initialize()
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/core/plugins.py", line 56, in _initialize
    self.plugin_type_to_subclass_list, self.stats = self._scan_all_plugins(
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra/core/plugins.py", line 168, in _scan_all_plugins
    loaded_mod = m.load_module(modname)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jgbos/.conda/envs/testing/lib/python3.8/site-packages/hydra_plugins/hydra_submitit_launcher/config.py", line 70, in <module>
    node=ObjectConf(
TypeError: __init__() got an unexpected keyword argument 'cls'
```

## Expected Behavior

Version should be at `1.0.0rc4` for running `pip install hydra-submitit-launcher --pre`

## System information
- Hydra version 1.0.0rc2

**Comment by omry** [comment]
Should be solved, try again.
