### ISSUE TITLE
Improving the exception handling in instantiate method

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#807]
Points from Omry: The exceptions should be compact and containing only interesting stack frames, and not a million chained exceptions.

_Originally posted by @omry in https://github.com/facebookresearch/hydra/pull/800#issuecomment-662171016_

**Comment by shagunsodhani** [comment]
**Original**

```
(hydra38) (mtrl) ➜  hydra_debug python my_app.py
Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 526, in _locate
    import_module(mod)
  File "/private/home/sodhani/.conda/envs/hydra38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/home/sodhani/hydra_debug/code/example_code.py", line 1, in <module>
    import pytorch_lightning.metrics.functional as plm
ModuleNotFoundError: No module named 'pytorch_lightning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/sodhani/projects/hydra/hydra/utils.py", line 33, in call
    type_or_callable = _locate(cls)
  File "/private/home/sodhani/projects/hydra/hydra/_internal/utils.py", line 528, in _locate
    raise ImportError(
ImportError: Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "my_app.py", line 7, in my_app
    python_class = hydra.utils.instantiate(cfg.code)
  File "/private/home/sodhani/projects/hydra/hydra/utils.py", line 40, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'code.example_code.sample_fucntion' : Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Proposed**

```
(hydra38) ➜  hydra_debug python my_app.py
Error calling 'code.example_code.sample_fucntion's
Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

```
(hydra38) ➜  hydra_debug HYDRA_FULL_ERROR=1 python my_app.py
Traceback (most recent call last):
  File "/Users/sodhani/projects/hydra/hydra/_internal/utils.py", line 534, in _locate
    import_module(mod)
  File "/Users/sodhani/miniconda3/envs/hydra38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sodhani/hydra_debug/code/example_code.py", line 1, in <module>
    import pytorch_lightning.metrics.functional as plm
ModuleNotFoundError: No module named 'pytorch_lightning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sodhani/projects/hydra/hydra/utils.py", line 33, in call
    type_or_callable = _locate(cls)
  File "/Users/sodhani/projects/hydra/hydra/_internal/utils.py", line 536, in _locate
    raise ImportError(
ImportError: Encountered error: `No module named 'pytorch_lightning'` when loading module 'code.example_code.sample_fucntion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sodhani/projects/hydra/hydra/_internal/utils.py", line 203, in run_and_report
    return func()
  File "/Users/sodhani/projects/hydra/hydra/_internal/utils.py", line 345, in <lambda>
    lambda: hydra.run(
  File "/Users/sodhani/projects/hydra/hydra/_internal/hydra.py", line 105, in run
    return run_job(
  File "/Users/sodhani/projects/hydra/hydra/core/utils.py", line 123, in run_job
    ret.return_value = task_function(task_cfg)
  File "my_app.py", line 7, in my_app
    python_class = hydra.utils.instantiate(cfg.code)
  File "/Users/sodhani/projects/hydra/hydra/utils.py", line 40, in call
    raise InstantiateErrorException(f"Error calling '{cls}'s") from e
hydra.errors.InstantiateErrorException: Error calling 'code.example_code.sample_fucntion's
```

**Comment by omry** [comment]
Not blocking Hydra 1.0

**Comment by omry** [comment]
is this done?

**Comment by shagunsodhani** [comment]
No. Havent made any progress on this :(

**Comment by omry** [comment]
I think the current behavior is not so bad (as of Hydra 1.1).
Closing.
