### ISSUE TITLE
Add docker example for Ray launcher.

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#841]
Add a docker example app for ray launcher. Add test for it.

**Comment by scottilee** [comment]
@jieru-hu Are you just looking for an example Dockerfile that would run the [simple example](https://github.com/facebookresearch/hydra/tree/master/plugins/hydra_ray_launcher/examples/simple)?

**Comment by jieru-hu** [comment]
hi @scottilee !

Not necessarily. The goal is to have a  minimal example that runs on docker and works out of the box, it doesn't have to be tied with the simple example.

Wanna give it a try? :)

**Comment by scottilee** [comment]
Sure, I have the following Dockerfile loaded with the simple example:
```
FROM python:3.8.8-slim

RUN apt-get update && apt-get install -y libc-dev gcc

RUN pip install hydra-core hydra-ray-launcher ray

WORKDIR /app

COPY . /app

CMD HYDRA_FULL_ERROR=1 python3 my_app.py --multirun hydra/launcher=ray
```

When I run it I get the following error:
```
Traceback (most recent call last):
  File "my_app.py", line 18, in <module>
    my_app()
  File "/usr/local/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 123, in multirun
    cfg = self.compose_config(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 256, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 805, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 777, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load override hydra/launcher/ray_aws
```

It runs without error when I run it locally (`python3 my_app.py --multirun hydra/launcher=ray`) and I don't get why it's complaining about ray_aws. I get a similar error, `Could not load override hydra/launcher/ray`, if I update config.yaml to `override hydra/launcher: ray`. Any idea what might be causing this?

**Comment by jieru-hu** [comment]
Sorry @scottilee for the late response! Somehow I missed your previous comment.

could you share the version of Hydra and the launcher you are using? The docker support was recently fixed in the latest ray-launcher release.

**Comment by scottilee** [comment]
@jieru-hu Ah, that helps! If I ping hydra-core to version 1.1.0.dev4 it seems to work. I will send a PR shortly.

**Comment by jieru-hu** [comment]
@scottilee  this should also work with Hydra 1.0 though, the hydra-ray-launcher's version should be the one that's making the difference, could you try with 1.0 as well?

**Comment by scottilee** [comment]
If I use `hydra-core==1.0`, or if I don't specify a version it installs `1.0.6` by default, and with either one I get the following error:
```
/usr/local/lib/python3.8/site-packages/omegaconf/omegaconf.py:572: UserWarning: update() merge flag is is not specified, defaulting to False.
For more details, see https://github.com/omry/omegaconf/issues/367
  warnings.warn(
Traceback (most recent call last):
  File "/app/my_app.py", line 18, in <module>
    my_app()
  File "/usr/local/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 363, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 210, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 207, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 364, in <lambda>
    lambda: hydra.multirun(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 123, in multirun
    cfg = self.compose_config(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 148, in load_configuration
    return self._load_configuration(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 250, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 797, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 769, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 707, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load override hydra/launcher/ray_aws
```

**Comment by jieru-hu** [comment]
Thanks @scottlee for looking into this. 
I think we were able to address your question on running the ray app during our offline chats (sorry I forgot to update this issue after our chat). 
Please feel free to ping me if you still run into issues running the plugin.

**Comment by omry** [comment]
Closing this as not planned.

The intended scope here was specifically an example that launches a Dockerized workload on AWS through `ray_aws`, with an automated test, rather than just a Dockerfile for running Ray locally. [PR #1479](https://github.com/facebookresearch/hydra/pull/1479) explored this but did not produce a maintainable version.

Hydra no longer has the AWS infrastructure needed to validate this continuously. [PR #3299](https://github.com/facebookresearch/hydra/pull/3299) disabled automatic Ray AWS test collection, and `ray_aws` is now maintained on a best-effort basis. I do not want to add a cloud example that we cannot verify and that is likely to become stale.

A reproducible, isolated cloud validation environment could make this worth reconsidering later. [Reploy](https://reploy.yadan.net/) may be one way to provide that infrastructure, but I am parking the idea for now.
