### ISSUE TITLE
[Bug] Custom OmegaConf resolvers registered at module level aren't propagated to submitit launcher processes

### ISSUE THREAD

**Issue by calebho** [facebookresearch/hydra#861]
# 🐛 Bug
## Description
Not sure whether this is expected behavior. If it is, it should be documented somewhere. If you register a custom OmegaConf resolver at module scope, they won't be propagated to the launcher processes. Thus when you try to access a config node which uses a custom resolver, you get an exception.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce
```python
# foo.py
import hydra
from omegaconf import OmegaConf


def my_custom_resolver():
    return "foo"


OmegaConf.register_resolver("my_custom_resolver", my_custom_resolver)


@hydra.main(config_name="foo")
def main(cfg):
    assert cfg.x == "foo"


if __name__ == "__main__":
    main()
```
```yaml
# foo.yaml
x: ${my_custom_resolver:}
```
Regular run works fine:
```
$ python foo.py
```
Multirun with submitit throws an exception:
```
$ python foo.py -m hydra/launcher=submitit_local
[2020-08-10 19:56:14,485][HYDRA] Submitit 'local' sweep output dir : multirun/2020-08-10/19-56-14
[2020-08-10 19:56:14,487][HYDRA] 	#0 :
Traceback (most recent call last):
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/utils.py", line 344, in <lambda>
    overrides=args.overrides,
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 135, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 149, in launch
    return [j.results()[0] for j in jobs]
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 149, in <listcomp>
    return [j.results()[0] for j in jobs]
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/submitit/core/core.py", line 291, in results
    raise job_exception  # pylint: disable=raising-bad-type
submitit.core.utils.FailedJobError: Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/submitit/core/submission.py", line 47, in process_job
    result = delayed.result()
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/submitit/core/utils.py", line 123, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 80, in __call__
    job_subdir_key="hydra.sweep.subdir",
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/core/utils.py", line 123, in run_job
    ret.return_value = task_function(task_cfg)
  File "foo.py", line 14, in main
    assert cfg.x == "foo"
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 315, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/omegaconf/_utils.py", line 669, in format_and_raise
    _raise(ex, cause)
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/omegaconf/_utils.py", line 583, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type my_custom_resolver
	full_key: x
	reference_type=Optional[Dict[Any, Any]]
	object_type=dict

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /private/home/calebh/scratch/hydra-bug/multirun/2020-08-10/19-56-14/.submitit/34113/34113_0_log.err
  - /private/home/calebh/scratch/hydra-bug/multirun/2020-08-10/19-56-14/.submitit/34113/34113_0_log.out
```

Moving `OmegaConf.register_resolver` inside `main` works:
```diff
--- foo.py	2020-08-10 19:51:10.401891000 -0700
+++ foo_fixed.py	2020-08-10 19:58:19.693452000 -0700
@@ -6,11 +6,9 @@
     return "foo"


-OmegaConf.register_resolver("my_custom_resolver", my_custom_resolver)
-
-
 @hydra.main(config_name="foo")
 def main(cfg):
+    OmegaConf.register_resolver("my_custom_resolver", my_custom_resolver)
     assert cfg.x == "foo"
```

## System information
- **Hydra Version**: 
    ```
    pip list | grep hydra
    hydra-core              1.0.0rc2
    hydra-submitit-launcher 1.0.0rc4
    ```
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.8.3
- **Operating system** : Ubuntu 18.04.3

## Additional context
I think this is an issue with how submitit is serializing the Python interpreter state to the worker processes. Might require a non-trivial change in its design

**Comment by omry** [comment]
Thanks for reporting, will look into it.

**Comment by samuelstanton** [comment]
I'm having the same problem. Any suggestions for a temporary workaround?

**Comment by calebho** [comment]
@samuelstanton You can move the `register_resolver` inside `main` as I mentioned in the bug report

**Comment by thoth291** [comment]
@calebho, simply moving it inside the `main` will not work perfectly - it will break normal `basic launcher` with `multirun`.
Moreover, the same behavior is happening with `joblib` - so it's not specific to `submitit` - maybe renaming an issue would help.

I had similar issue few days ago but went around it by doing this in my `main`:
```python
if OmegaConf.get_resolver("my_custom_resolver") is None:
        OmegaConf.register_resolver("my_custom_resolver", my_custom_resolver)
```
I forgot to report it - that would save some of your time - sorry.
